/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-15 -add-include "krml/internal/compat.h" -bundle CLRS.Ch13.RBTree.Main=CLRS.Ch13.RBTree.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch13_RBTree_Main.krml _output/CLRS_Ch13_RBTree_ImplTest.krml _output/CLRS_Ch13_RBTree_Impl.krml _output/CLRS_Ch13_RBTree_Spec.krml _output/FStar_Pervasives_Native.krml _output/FStar_Pervasives.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_CLRS_Ch13_RBTree_Main_H
#define internal_CLRS_Ch13_RBTree_Main_H

#include "krmllib.h"

#include "../CLRS_Ch13_RBTree_Main.h"
#include "krml/internal/compat.h"

#define CLRS_Ch13_RBTree_Spec_Red 0
#define CLRS_Ch13_RBTree_Spec_Black 1

typedef uint8_t CLRS_Ch13_RBTree_Spec_color;

typedef struct CLRS_Ch13_RBTree_Impl_rb_node_s CLRS_Ch13_RBTree_Impl_rb_node;

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node__tags;

typedef struct FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node__s
{
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node__tags tag;
  CLRS_Ch13_RBTree_Impl_rb_node *v;
}
FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_;

typedef struct CLRS_Ch13_RBTree_Impl_rb_node_s
{
  krml_checked_int_t key;
  CLRS_Ch13_RBTree_Spec_color color;
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ left;
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ right;
}
CLRS_Ch13_RBTree_Impl_rb_node;

typedef struct FStar_Pervasives_Native_option__krml_checked_int_t_s
{
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node__tags tag;
  krml_checked_int_t v;
}
FStar_Pervasives_Native_option__krml_checked_int_t;

FStar_Pervasives_Native_option__krml_checked_int_t
CLRS_Ch13_RBTree_Impl_rb_search(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
);

FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
CLRS_Ch13_RBTree_Impl_rb_ins(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
);

FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
CLRS_Ch13_RBTree_Impl_rb_fuse(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
);

FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
CLRS_Ch13_RBTree_Impl_rb_del(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
);

void
CLRS_Ch13_RBTree_Impl_free_rbtree(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree
);


#define internal_CLRS_Ch13_RBTree_Main_H_DEFINED
#endif /* internal_CLRS_Ch13_RBTree_Main_H */
