/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch22.ImplTestMain=CLRS.Ch22.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/csrc _output/CLRS_Ch22_ImplTestMain.krml _output/CLRS_Ch22_BFS_ImplTest.krml _output/CLRS_Ch22_DFS_ImplTest.krml _output/CLRS_Ch22_TopologicalSort_ImplTest.krml _output/CLRS_Ch22_BFS_Impl.krml _output/CLRS_Ch22_DFS_Impl.krml _output/CLRS_Ch22_TopologicalSort_Impl.krml _output/CLRS_Ch22_TopologicalSort_Impl_Defs.krml _output/CLRS_Ch22_Graph_Common.krml _output/CLRS_Ch22_TopologicalSort_Spec.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_PulseCore_Prims_H
#define internal_FStar_Pulse_PulseCore_Prims_H

#include "krmllib.h"

#include "krml/internal/compat.h"
#include "fstar_support.h"

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_FStar_Pulse_PulseCore_Prims_H_DEFINED
#endif /* internal_FStar_Pulse_PulseCore_Prims_H */
