/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch15.RodCutting.ImplTest+CLRS.Ch15.RodCutting.Impl=CLRS.Ch15.RodCutting.ImplTest,CLRS.Ch15.RodCutting.Impl[rename=RodCutting_ImplTest] -bundle CLRS.Ch15.LCS.ImplTest+CLRS.Ch15.LCS.Impl=CLRS.Ch15.LCS.ImplTest,CLRS.Ch15.LCS.Impl[rename=LCS_ImplTest] -bundle CLRS.Ch15.MatrixChain.ImplTest+CLRS.Ch15.MatrixChain.Impl=CLRS.Ch15.MatrixChain.ImplTest,CLRS.Ch15.MatrixChain.Impl[rename=MatrixChain_ImplTest] -bundle FStar.*,Pulse.*,PulseCore.*,Prims,CLRS.Ch15.RodCutting.Spec,CLRS.Ch15.RodCutting.Lemmas,CLRS.Ch15.LCS.Spec,CLRS.Ch15.LCS.Lemmas,CLRS.Ch15.MatrixChain.Spec,CLRS.Ch15.MatrixChain.Lemmas,CLRS.Ch15.MatrixChain.Complexity[rename=Support] -tmpdir _extract _output/CLRS_Ch15_RodCutting_ImplTest.krml _output/CLRS_Ch15_RodCutting_Impl_full.krml _output/CLRS_Ch15_LCS_ImplTest.krml _output/CLRS_Ch15_LCS_Impl_full.krml _output/CLRS_Ch15_MatrixChain_ImplTest.krml _output/CLRS_Ch15_MatrixChain_Impl_full.krml
  F* version: <unknown>
  KaRaMeL version: 7bdb6cb2fd7661f4a0dade9ccae810451cb51746
 */

#include "LCS_ImplTest.h"

#include "internal/Support.h"

bool CLRS_Ch15_LCS_ImplTest_test_lcs(void)
{
  krml_checked_int_t *xv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *x_arr = xv;
  x_arr[0U] = (krml_checked_int_t)1;
  x_arr[1U] = (krml_checked_int_t)2;
  x_arr[2U] = (krml_checked_int_t)3;
  krml_checked_int_t *yv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *y_arr = yv;
  y_arr[0U] = (krml_checked_int_t)2;
  y_arr[1U] = (krml_checked_int_t)3;
  y_arr[2U] = (krml_checked_int_t)4;
  krml_checked_int_t result = CLRS_Ch15_LCS_Impl_lcs(x_arr, y_arr, (size_t)3U, (size_t)3U);
  bool pass = result == (krml_checked_int_t)2;
  KRML_HOST_FREE(yv);
  KRML_HOST_FREE(xv);
  return pass;
}

krml_checked_int_t
CLRS_Ch15_LCS_Impl_lcs(krml_checked_int_t *x, krml_checked_int_t *y, size_t m, size_t n)
{
  if (m == (size_t)0U || n == (size_t)0U)
    return (krml_checked_int_t)0;
  else
  {
    size_t m_plus_1 = m + (size_t)1U;
    size_t n_plus_1 = n + (size_t)1U;
    size_t table_size = m_plus_1 * n_plus_1;
    KRML_CHECK_SIZE(sizeof (krml_checked_int_t), table_size);
    krml_checked_int_t *table = KRML_HOST_CALLOC(table_size, sizeof (krml_checked_int_t));
    size_t i = (size_t)0U;
    size_t __anf00 = i;
    bool cond = __anf00 <= m;
    while (cond)
    {
      size_t vi = i;
      size_t j = (size_t)0U;
      size_t __anf0 = j;
      bool cond0 = __anf0 <= n;
      while (cond0)
      {
        size_t vj = j;
        size_t idx = vi * (n + (size_t)1U) + vj;
        size_t safe_vi_m1;
        if (vi > (size_t)0U)
          safe_vi_m1 = vi - (size_t)1U;
        else
          safe_vi_m1 = vi;
        size_t safe_vj_m1;
        if (vj > (size_t)0U)
          safe_vj_m1 = vj - (size_t)1U;
        else
          safe_vj_m1 = vj;
        size_t idx_diag = safe_vi_m1 * (n + (size_t)1U) + safe_vj_m1;
        size_t idx_up = safe_vi_m1 * (n + (size_t)1U) + vj;
        size_t idx_left = vi * (n + (size_t)1U) + safe_vj_m1;
        krml_checked_int_t val_diag = table[idx_diag];
        krml_checked_int_t val_up = table[idx_up];
        krml_checked_int_t val_left = table[idx_left];
        krml_checked_int_t xi = x[safe_vi_m1];
        krml_checked_int_t yj = y[safe_vj_m1];
        krml_checked_int_t value_to_store;
        if (vi == (size_t)0U || vj == (size_t)0U)
          value_to_store = (krml_checked_int_t)0;
        else if (xi == yj)
        {
          krml_checked_int_t
          (*op_Plus)(krml_checked_int_t x0, krml_checked_int_t x1) =
            Pulse_Lib_BoundedIntegers_bounded_int_int.op_Plus;
          value_to_store = op_Plus(val_diag, (krml_checked_int_t)1);
        }
        else
        {
          bool
          (*op_Greater_Equals)(krml_checked_int_t x0, krml_checked_int_t x1) =
            Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater_Equals;
          if (op_Greater_Equals(val_up, val_left))
            value_to_store = val_up;
          else
            value_to_store = val_left;
        }
        table[idx] = value_to_store;
        j = vj + (size_t)1U;
        size_t __anf0 = j;
        cond0 = __anf0 <= n;
      }
      i = vi + (size_t)1U;
      size_t __anf00 = i;
      cond = __anf00 <= m;
    }
    size_t result_idx = m * (n + (size_t)1U) + n;
    krml_checked_int_t result = table[result_idx];
    KRML_HOST_FREE(table);
    return result;
  }
}

