/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch15.RodCutting.ImplTest+CLRS.Ch15.RodCutting.Impl=CLRS.Ch15.RodCutting.ImplTest,CLRS.Ch15.RodCutting.Impl[rename=RodCutting_ImplTest] -bundle CLRS.Ch15.LCS.ImplTest+CLRS.Ch15.LCS.Impl=CLRS.Ch15.LCS.ImplTest,CLRS.Ch15.LCS.Impl[rename=LCS_ImplTest] -bundle CLRS.Ch15.MatrixChain.ImplTest+CLRS.Ch15.MatrixChain.Impl=CLRS.Ch15.MatrixChain.ImplTest,CLRS.Ch15.MatrixChain.Impl[rename=MatrixChain_ImplTest] -bundle FStar.*,Pulse.*,PulseCore.*,Prims,CLRS.Ch15.RodCutting.Spec,CLRS.Ch15.RodCutting.Lemmas,CLRS.Ch15.LCS.Spec,CLRS.Ch15.LCS.Lemmas,CLRS.Ch15.MatrixChain.Spec,CLRS.Ch15.MatrixChain.Lemmas,CLRS.Ch15.MatrixChain.Complexity[rename=Support] -tmpdir _extract _output/CLRS_Ch15_RodCutting_ImplTest.krml _output/CLRS_Ch15_RodCutting_Impl_full.krml _output/CLRS_Ch15_LCS_ImplTest.krml _output/CLRS_Ch15_LCS_Impl_full.krml _output/CLRS_Ch15_MatrixChain_ImplTest.krml _output/CLRS_Ch15_MatrixChain_Impl_full.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "MatrixChain_ImplTest.h"

#include "internal/Support.h"

bool CLRS_Ch15_MatrixChain_ImplTest_test_matrix_chain(void)
{
  krml_checked_int_t *dv = KRML_HOST_MALLOC(sizeof (krml_checked_int_t) * (size_t)4U);
  if (dv != NULL)
    for (uint32_t _i = 0U; _i < (size_t)4U; ++_i)
      dv[_i] = (krml_checked_int_t)10;
  krml_checked_int_t *dims = dv;
  dims[0U] = (krml_checked_int_t)10;
  dims[1U] = (krml_checked_int_t)30;
  dims[2U] = (krml_checked_int_t)5;
  dims[3U] = (krml_checked_int_t)60;
  krml_checked_int_t result = CLRS_Ch15_MatrixChain_Impl_matrix_chain_order(dims, (size_t)3U);
  bool pass = result == (krml_checked_int_t)4500;
  KRML_HOST_FREE(dv);
  return pass;
}

krml_checked_int_t
CLRS_Ch15_MatrixChain_Impl_matrix_chain_order(krml_checked_int_t *dims, size_t n)
{
  size_t table_size = n * n;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), table_size);
  krml_checked_int_t *m = KRML_HOST_CALLOC(table_size, sizeof (krml_checked_int_t));
  size_t l = (size_t)2U;
  size_t __anf00 = l;
  bool cond = __anf00 <= n;
  while (cond)
  {
    size_t vl = l;
    size_t i = (size_t)0U;
    size_t __anf00 = i;
    bool cond0 = __anf00 < n - vl + (size_t)1U;
    while (cond0)
    {
      size_t vi = i;
      size_t j = vi + vl - (size_t)1U;
      krml_checked_int_t min_cost = (krml_checked_int_t)1000000000;
      size_t k = vi;
      size_t __anf0 = k;
      bool cond = __anf0 < j;
      while (cond)
      {
        size_t vk = k;
        krml_checked_int_t vmin_cost = min_cost;
        size_t idx_ik = vi * n + vk;
        size_t idx_k1j = (vk + (size_t)1U) * n + j;
        krml_checked_int_t cost_ik = m[idx_ik];
        krml_checked_int_t cost_k1j = m[idx_k1j];
        krml_checked_int_t dim_i = dims[vi];
        krml_checked_int_t dim_k1 = dims[vk + (size_t)1U];
        krml_checked_int_t dim_j1 = dims[j + (size_t)1U];
        krml_checked_int_t mult_cost = Prims_op_Multiply(Prims_op_Multiply(dim_i, dim_k1), dim_j1);
        krml_checked_int_t
        (*op_Plus)(krml_checked_int_t x0, krml_checked_int_t x1) =
          Pulse_Lib_BoundedIntegers_bounded_int_int.op_Plus;
        krml_checked_int_t
        q = Pulse_Lib_BoundedIntegers_bounded_int_int.op_Plus(op_Plus(cost_ik, cost_k1j), mult_cost);
        bool
        (*op_Less)(krml_checked_int_t x0, krml_checked_int_t x1) =
          Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less;
        krml_checked_int_t new_min;
        if (op_Less(q, vmin_cost))
          new_min = q;
        else
          new_min = vmin_cost;
        min_cost = new_min;
        k = vk + (size_t)1U;
        size_t __anf0 = k;
        cond = __anf0 < j;
      }
      krml_checked_int_t final_min_cost = min_cost;
      size_t idx_ij = vi * n + j;
      m[idx_ij] = final_min_cost;
      i = vi + (size_t)1U;
      size_t __anf00 = i;
      cond0 = __anf00 < n - vl + (size_t)1U;
    }
    l = vl + (size_t)1U;
    size_t __anf0 = l;
    cond = __anf0 <= n;
  }
  size_t result_idx = n - (size_t)1U;
  krml_checked_int_t result = m[result_idx];
  KRML_HOST_FREE(m);
  return result;
}

