/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch15.RodCutting.ImplTest+CLRS.Ch15.RodCutting.Impl=CLRS.Ch15.RodCutting.ImplTest,CLRS.Ch15.RodCutting.Impl[rename=RodCutting_ImplTest] -bundle CLRS.Ch15.LCS.ImplTest+CLRS.Ch15.LCS.Impl=CLRS.Ch15.LCS.ImplTest,CLRS.Ch15.LCS.Impl[rename=LCS_ImplTest] -bundle CLRS.Ch15.MatrixChain.ImplTest+CLRS.Ch15.MatrixChain.Impl=CLRS.Ch15.MatrixChain.ImplTest,CLRS.Ch15.MatrixChain.Impl[rename=MatrixChain_ImplTest] -bundle FStar.*,Pulse.*,PulseCore.*,Prims,CLRS.Ch15.RodCutting.Spec,CLRS.Ch15.RodCutting.Lemmas,CLRS.Ch15.LCS.Spec,CLRS.Ch15.LCS.Lemmas,CLRS.Ch15.MatrixChain.Spec,CLRS.Ch15.MatrixChain.Lemmas,CLRS.Ch15.MatrixChain.Complexity[rename=Support] -tmpdir _extract _output/CLRS_Ch15_RodCutting_ImplTest.krml _output/CLRS_Ch15_RodCutting_Impl_full.krml _output/CLRS_Ch15_LCS_ImplTest.krml _output/CLRS_Ch15_LCS_Impl_full.krml _output/CLRS_Ch15_MatrixChain_ImplTest.krml _output/CLRS_Ch15_MatrixChain_Impl_full.krml
  F* version: <unknown>
  KaRaMeL version: 7bdb6cb2fd7661f4a0dade9ccae810451cb51746
 */

#include "RodCutting_ImplTest.h"

#include "internal/Support.h"

bool CLRS_Ch15_RodCutting_ImplTest_test_rod_cutting(void)
{
  krml_checked_int_t *pv = KRML_HOST_CALLOC((size_t)4U, sizeof (krml_checked_int_t));
  krml_checked_int_t *prices_arr = pv;
  prices_arr[0U] = (krml_checked_int_t)1;
  prices_arr[1U] = (krml_checked_int_t)5;
  prices_arr[2U] = (krml_checked_int_t)8;
  prices_arr[3U] = (krml_checked_int_t)9;
  krml_checked_int_t result = CLRS_Ch15_RodCutting_Impl_rod_cutting(prices_arr, (size_t)4U);
  bool pass = result == (krml_checked_int_t)10;
  KRML_HOST_FREE(pv);
  return pass;
}

krml_checked_int_t CLRS_Ch15_RodCutting_Impl_triangle(krml_checked_int_t n)
{
  return
    Prims_op_Division(Prims_op_Multiply(n, Prims_op_Addition(n, (krml_checked_int_t)1)),
      (krml_checked_int_t)2);
}

krml_checked_int_t CLRS_Ch15_RodCutting_Impl_rod_cutting(krml_checked_int_t *prices, size_t n)
{
  size_t n_plus_1 = n + (size_t)1U;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), n_plus_1);
  krml_checked_int_t *r = KRML_HOST_CALLOC(n_plus_1, sizeof (krml_checked_int_t));
  size_t j = (size_t)1U;
  size_t __anf00 = j;
  bool cond = __anf00 <= n;
  while (cond)
  {
    size_t vj = j;
    krml_checked_int_t q = (krml_checked_int_t)0;
    size_t i = (size_t)1U;
    size_t __anf0 = i;
    bool cond0 = __anf0 <= vj;
    while (cond0)
    {
      size_t vi = i;
      krml_checked_int_t vq = q;
      size_t idx_price = vi - (size_t)1U;
      krml_checked_int_t price_i = prices[idx_price];
      krml_checked_int_t r_j_minus_i = r[vj - vi];
      krml_checked_int_t
      (*op_Plus)(krml_checked_int_t x0, krml_checked_int_t x1) =
        Pulse_Lib_BoundedIntegers_bounded_int_nat.op_Plus;
      krml_checked_int_t candidate = op_Plus(price_i, r_j_minus_i);
      bool
      (*op_Greater)(krml_checked_int_t x0, krml_checked_int_t x1) =
        Pulse_Lib_BoundedIntegers_bounded_int_nat.op_Greater;
      krml_checked_int_t new_q;
      if (op_Greater(candidate, vq))
        new_q = candidate;
      else
        new_q = vq;
      q = new_q;
      i = vi + (size_t)1U;
      size_t __anf0 = i;
      cond0 = __anf0 <= vj;
    }
    krml_checked_int_t final_q = q;
    r[vj] = final_q;
    j = vj + (size_t)1U;
    size_t __anf00 = j;
    cond = __anf00 <= n;
  }
  krml_checked_int_t result = r[n];
  KRML_HOST_FREE(r);
  return result;
}

