/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch15.RodCutting.ImplTest+CLRS.Ch15.RodCutting.Impl=CLRS.Ch15.RodCutting.ImplTest,CLRS.Ch15.RodCutting.Impl[rename=RodCutting_ImplTest] -bundle CLRS.Ch15.LCS.ImplTest+CLRS.Ch15.LCS.Impl=CLRS.Ch15.LCS.ImplTest,CLRS.Ch15.LCS.Impl[rename=LCS_ImplTest] -bundle CLRS.Ch15.MatrixChain.ImplTest+CLRS.Ch15.MatrixChain.Impl=CLRS.Ch15.MatrixChain.ImplTest,CLRS.Ch15.MatrixChain.Impl[rename=MatrixChain_ImplTest] -bundle FStar.*,Pulse.*,PulseCore.*,Prims,CLRS.Ch15.RodCutting.Spec,CLRS.Ch15.RodCutting.Lemmas,CLRS.Ch15.LCS.Spec,CLRS.Ch15.LCS.Lemmas,CLRS.Ch15.MatrixChain.Spec,CLRS.Ch15.MatrixChain.Lemmas,CLRS.Ch15.MatrixChain.Complexity[rename=Support] -tmpdir _extract _output/CLRS_Ch15_RodCutting_ImplTest.krml _output/CLRS_Ch15_RodCutting_Impl_full.krml _output/CLRS_Ch15_LCS_ImplTest.krml _output/CLRS_Ch15_LCS_Impl_full.krml _output/CLRS_Ch15_MatrixChain_ImplTest.krml _output/CLRS_Ch15_MatrixChain_Impl_full.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/Support.h"

Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_int;

Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_nat;

