/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch06.Heap.ImplTest=CLRS.Ch06.Heap.*,Pulse.Lib.BoundedIntegers -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch06_Heap_Impl.krml _output/CLRS_Ch06_Heap_ImplTest.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_CLRS_Ch06_Heap_ImplTest_H
#define internal_CLRS_Ch06_Heap_ImplTest_H

#include "krmllib.h"

#include "../CLRS_Ch06_Heap_ImplTest.h"
#include "krml/internal/compat.h"

typedef struct Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t_s
{
  krml_checked_int_t (*op_Plus)(krml_checked_int_t x0, krml_checked_int_t x1);
  krml_checked_int_t (*op_Subtraction)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Less)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Less_Equals)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Greater)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Greater_Equals)(krml_checked_int_t x0, krml_checked_int_t x1);
  krml_checked_int_t (*op_Percent)(krml_checked_int_t x0, krml_checked_int_t x1);
  krml_checked_int_t (*op_Slash)(krml_checked_int_t x0, krml_checked_int_t x1);
}
Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t;

extern Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_int;

void CLRS_Ch06_Heap_Impl_max_heapify(krml_checked_int_t *a, size_t idx, size_t heap_size);


#define internal_CLRS_Ch06_Heap_ImplTest_H_DEFINED
#endif /* internal_CLRS_Ch06_Heap_ImplTest_H */
