/*****************************************************************************
 * HANDWRITTEN FILE — This is NOT generated by F* or KaRaMeL.
 *
 * Shim for FStar.SizeT conversions used in KaRaMeL-extracted C code.
 * Provides inline helpers that map between size_t and krml_checked_int_t.
 *****************************************************************************/

#ifndef FSTAR_SIZET_SHIM_H
#define FSTAR_SIZET_SHIM_H

#include "krmllib.h"

static inline size_t FStar_SizeT_uint_to_t(krml_checked_int_t x) {
  return (size_t)x;
}

static inline krml_checked_int_t FStar_SizeT_v(size_t x) {
  return (krml_checked_int_t)x;
}

#endif
