/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch08.CountingSort.ImplTest+CLRS.Ch08.CountingSort.Impl=CLRS.Ch08.CountingSort.ImplTest,CLRS.Ch08.CountingSort.Impl[rename=ImplTest] -bundle FStar.*,Pulse.*,PulseCore.*,Prims,CLRS.Ch08.CountingSort.Spec,CLRS.Ch08.CountingSort.Lemmas,CLRS.Ch08.CountingSort.StableLemmas,CLRS.Ch08.CountingSort.DigitSortLemmas,CLRS.Ch08.RadixSort.* -add-early-include "fstar_sizet_shim.h" -tmpdir _output _output/CLRS_Ch08_CountingSort_ImplTest.krml _output/CLRS_Ch08_CountingSort_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef ImplTest_H
#define ImplTest_H

#include "fstar_sizet_shim.h"

#include "krmllib.h"

#include "krml/internal/compat.h"

void CLRS_Ch08_CountingSort_ImplTest_test_counting_sort_inplace(void);

void CLRS_Ch08_CountingSort_ImplTest_test_counting_sort_impl(void);

void
CLRS_Ch08_CountingSort_Impl_counting_sort_impl(
  krml_checked_int_t *a,
  krml_checked_int_t *b,
  size_t len,
  size_t k_val
);

void
CLRS_Ch08_CountingSort_Impl_counting_sort_inplace(
  krml_checked_int_t *a,
  size_t len,
  size_t k_val
);


#define ImplTest_H_DEFINED
#endif /* ImplTest_H */
