/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch08.CountingSort.ImplTest+CLRS.Ch08.CountingSort.Impl=CLRS.Ch08.CountingSort.ImplTest,CLRS.Ch08.CountingSort.Impl[rename=ImplTest] -bundle FStar.*,Pulse.*,PulseCore.*,Prims,CLRS.Ch08.CountingSort.Spec,CLRS.Ch08.CountingSort.Lemmas,CLRS.Ch08.CountingSort.StableLemmas,CLRS.Ch08.CountingSort.DigitSortLemmas,CLRS.Ch08.RadixSort.* -add-early-include "fstar_sizet_shim.h" -tmpdir _output _output/CLRS_Ch08_CountingSort_ImplTest.krml _output/CLRS_Ch08_CountingSort_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "ImplTest.h"

#include "internal/FStar_Pulse_PulseCore_Prims_CLRS_Ch08_CountingSort_Spec_CLRS_Ch08_CountingSort_Lemmas_CLRS_Ch08_CountingSort_StableLemmas_CLRS_Ch08_CountingSort_DigitSortLemmas_CLRS_Ch08_RadixSort.h"

void CLRS_Ch08_CountingSort_ImplTest_test_counting_sort_inplace(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  CLRS_Ch08_CountingSort_Impl_counting_sort_inplace(arr, (size_t)3U, (size_t)4U);
  KRML_HOST_FREE(v);
}

void CLRS_Ch08_CountingSort_ImplTest_test_counting_sort_impl(void)
{
  krml_checked_int_t *va = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *a = va;
  a[0U] = (krml_checked_int_t)3;
  a[1U] = (krml_checked_int_t)1;
  a[2U] = (krml_checked_int_t)2;
  krml_checked_int_t *vb = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *b = vb;
  CLRS_Ch08_CountingSort_Impl_counting_sort_impl(a, b, (size_t)3U, (size_t)3U);
  KRML_HOST_FREE(va);
  KRML_HOST_FREE(vb);
}

void
CLRS_Ch08_CountingSort_Impl_counting_sort_impl(
  krml_checked_int_t *a,
  krml_checked_int_t *b,
  size_t len,
  size_t k_val
)
{
  if (!(len == (size_t)0U))
  {
    size_t k_plus_1 = k_val + (size_t)1U;
    KRML_CHECK_SIZE(sizeof (krml_checked_int_t), k_plus_1);
    krml_checked_int_t *c = KRML_HOST_CALLOC(k_plus_1, sizeof (krml_checked_int_t));
    size_t j = (size_t)0U;
    size_t vj0 = j;
    bool cond = vj0 < len;
    while (cond)
    {
      size_t vj = j;
      krml_checked_int_t val_j = a[vj];
      krml_checked_int_t count_old = c[FStar_SizeT_uint_to_t(val_j)];
      c[FStar_SizeT_uint_to_t(val_j)] = Prims_op_Addition(count_old, (krml_checked_int_t)1);
      j = vj + (size_t)1U;
      size_t vj0 = j;
      cond = vj0 < len;
    }
    size_t i = (size_t)1U;
    size_t vi0 = i;
    bool cond0 = vi0 <= k_val;
    while (cond0)
    {
      size_t vi = i;
      size_t vi_minus_1 = vi - (size_t)1U;
      krml_checked_int_t prev_count = c[vi_minus_1];
      krml_checked_int_t curr_count = c[vi];
      c[vi] = Prims_op_Addition(curr_count, prev_count);
      i = vi + (size_t)1U;
      size_t vi0 = i;
      cond0 = vi0 <= k_val;
    }
    size_t j_back = len - (size_t)1U;
    bool done = false;
    bool vdone = done;
    bool cond1 = !vdone;
    while (cond1)
    {
      size_t vj_back = j_back;
      krml_checked_int_t val_j = a[vj_back];
      krml_checked_int_t pos = c[FStar_SizeT_uint_to_t(val_j)];
      b[FStar_SizeT_uint_to_t(Prims_op_Subtraction(pos, (krml_checked_int_t)1))] = val_j;
      c[FStar_SizeT_uint_to_t(val_j)] = Prims_op_Subtraction(pos, (krml_checked_int_t)1);
      if (vj_back == (size_t)0U)
        done = true;
      else
        j_back = vj_back - (size_t)1U;
      bool vdone = done;
      cond1 = !vdone;
    }
    KRML_HOST_FREE(c);
  }
}

void
CLRS_Ch08_CountingSort_Impl_counting_sort_inplace(
  krml_checked_int_t *a,
  size_t len,
  size_t k_val
)
{
  if (!(len == (size_t)0U))
  {
    size_t n = len;
    krml_checked_int_t k = FStar_SizeT_v(k_val);
    KRML_MAYBE_UNUSED_VAR(k);
    size_t k1 = k_val + (size_t)1U;
    KRML_CHECK_SIZE(sizeof (krml_checked_int_t), k1);
    krml_checked_int_t *c_arr = KRML_HOST_CALLOC(k1, sizeof (krml_checked_int_t));
    size_t j = (size_t)0U;
    size_t __anf00 = j;
    bool cond = __anf00 < n;
    while (cond)
    {
      size_t vj = j;
      krml_checked_int_t val_j = a[vj];
      size_t idx = FStar_SizeT_uint_to_t(val_j);
      krml_checked_int_t old_count = c_arr[idx];
      c_arr[idx] = Prims_op_Addition(old_count, (krml_checked_int_t)1);
      j = vj + (size_t)1U;
      size_t __anf0 = j;
      cond = __anf0 < n;
    }
    size_t pos = (size_t)0U;
    size_t cur_v = (size_t)0U;
    krml_checked_int_t cur_v_nat = (krml_checked_int_t)0;
    size_t __anf01 = cur_v;
    bool cond0 = __anf01 <= k_val;
    while (cond0)
    {
      size_t vcv = cur_v;
      size_t vpos = pos;
      krml_checked_int_t vcvn = cur_v_nat;
      krml_checked_int_t cnt = c_arr[vcv];
      size_t cnt_sz = FStar_SizeT_uint_to_t(cnt);
      size_t w = (size_t)0U;
      size_t __anf0 = w;
      bool cond = __anf0 < cnt_sz;
      while (cond)
      {
        size_t vw = w;
        size_t write_pos = vpos + vw;
        a[write_pos] = vcvn;
        w = vw + (size_t)1U;
        size_t __anf0 = w;
        cond = __anf0 < cnt_sz;
      }
      pos = vpos + cnt_sz;
      cur_v = vcv + (size_t)1U;
      cur_v_nat = Prims_op_Addition(vcvn, (krml_checked_int_t)1);
      size_t __anf00 = cur_v;
      cond0 = __anf00 <= k_val;
    }
    KRML_HOST_FREE(c_arr);
  }
}

