/*****************************************************************************
 * HANDWRITTEN FILE — This is NOT generated by F* or KaRaMeL.
 *
 * This is the main test driver for the verified counting sort implementation.
 * It calls the F*+Pulse verified counting sort functions that have been
 * extracted to C via KaRaMeL.
 *****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include "fstar_sizet_shim.h"
#include "ImplTest.h"

int main(void) {
  printf("=== Counting Sort C Extraction Tests ===\n\n");

  printf("Test 1: counting_sort_inplace [3,1,2] -> [1,2,3] ...\n");
  CLRS_Ch08_CountingSort_ImplTest_test_counting_sort_inplace();
  printf("  PASSED\n\n");

  printf("Test 2: counting_sort_impl [3,1,2] -> [1,2,3] ...\n");
  CLRS_Ch08_CountingSort_ImplTest_test_counting_sort_impl();
  printf("  PASSED\n\n");

  printf("All tests passed.\n");
  return 0;
}
