/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch12.BST.TestMain=CLRS.Ch12.BST.ImplTest,CLRS.Ch12.BST.Impl -bundle CLRS.Ch12.BSTArray.TestMain=CLRS.Ch12.BSTArray.ImplTest,CLRS.Ch12.BSTArray.Impl -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch12_BST_TestMain.krml _output/CLRS_Ch12_BST_ImplTest.krml _output/CLRS_Ch12_BST_Impl.krml _output/FStar_Pervasives.krml _output/FStar_Pervasives_Native.krml _output/CLRS_Ch12_BSTArray_TestMain.krml _output/CLRS_Ch12_BSTArray_ImplTest.krml _output/CLRS_Ch12_BSTArray_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/CLRS_Ch12_BST_TestMain.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

bool
CLRS_Ch12_BST_Impl_tree_search(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  krml_checked_int_t k
)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return false;
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch12_BST_Impl_bst_node *bp = tree.v;
    CLRS_Ch12_BST_Impl_bst_node node = *bp;
    if (k == node.key)
      return true;
    else if (Prims_op_LessThan(k, node.key))
      return CLRS_Ch12_BST_Impl_tree_search(node.left, k);
    else
      return CLRS_Ch12_BST_Impl_tree_search(node.right, k);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

krml_checked_int_t
CLRS_Ch12_BST_Impl_tree_minimum(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  CLRS_Ch12_BST_Impl_bst_node *bp
)
{
  KRML_MAYBE_UNUSED_VAR(tree);
  CLRS_Ch12_BST_Impl_bst_node nd = *bp;
  if (nd.left.tag == FStar_Pervasives_Native_None)
    return nd.key;
  else if (nd.left.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch12_BST_Impl_bst_node *lbp = nd.left.v;
    return CLRS_Ch12_BST_Impl_tree_minimum(nd.left, lbp);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

krml_checked_int_t
CLRS_Ch12_BST_Impl_tree_maximum(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  CLRS_Ch12_BST_Impl_bst_node *bp
)
{
  KRML_MAYBE_UNUSED_VAR(tree);
  CLRS_Ch12_BST_Impl_bst_node nd = *bp;
  if (nd.right.tag == FStar_Pervasives_Native_None)
    return nd.key;
  else if (nd.right.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch12_BST_Impl_bst_node *rbp = nd.right.v;
    return CLRS_Ch12_BST_Impl_tree_maximum(nd.right, rbp);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
new_bst_node(
  krml_checked_int_t k,
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ parent
)
{
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
  left_nil = { .tag = FStar_Pervasives_Native_None };
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
  right_nil = { .tag = FStar_Pervasives_Native_None };
  CLRS_Ch12_BST_Impl_bst_node *bp = KRML_HOST_MALLOC(sizeof (CLRS_Ch12_BST_Impl_bst_node));
  if (bp != NULL)
    bp[0U] =
      ((CLRS_Ch12_BST_Impl_bst_node){ .key = k, .left = left_nil, .right = right_nil, .p = parent });
  return
    (
      (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
        .tag = FStar_Pervasives_Native_Some,
        .v = bp
      }
    );
}

FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
CLRS_Ch12_BST_Impl_tree_insert(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  krml_checked_int_t k,
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ parent
)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return new_bst_node(k, parent);
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch12_BST_Impl_bst_node *vl = tree.v;
    CLRS_Ch12_BST_Impl_bst_node node = *vl;
    if (Prims_op_LessThan(k, node.key))
    {
      FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
      new_left =
        CLRS_Ch12_BST_Impl_tree_insert(node.left,
          k,
          (
            (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
              .tag = FStar_Pervasives_Native_Some,
              .v = vl
            }
          ));
      *vl =
        (
          (CLRS_Ch12_BST_Impl_bst_node){
            .key = node.key,
            .left = new_left,
            .right = node.right,
            .p = node.p
          }
        );
      return
        (
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = vl
          }
        );
    }
    else if (Prims_op_GreaterThan(k, node.key))
    {
      FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
      new_right =
        CLRS_Ch12_BST_Impl_tree_insert(node.right,
          k,
          (
            (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
              .tag = FStar_Pervasives_Native_Some,
              .v = vl
            }
          ));
      *vl =
        (
          (CLRS_Ch12_BST_Impl_bst_node){
            .key = node.key,
            .left = node.left,
            .right = new_right,
            .p = node.p
          }
        );
      return
        (
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = vl
          }
        );
    }
    else
      return tree;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static void
set_parent_ptr(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ child,
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ new_parent
)
{
  if (!(child.tag == FStar_Pervasives_Native_None))
    if (child.tag == FStar_Pervasives_Native_Some)
    {
      CLRS_Ch12_BST_Impl_bst_node *bp = child.v;
      (*bp).p = new_parent;
    }
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
}

FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
CLRS_Ch12_BST_Impl_tree_delete(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  krml_checked_int_t k,
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ parent
)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return
      (
        (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
          .tag = FStar_Pervasives_Native_None
        }
      );
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch12_BST_Impl_bst_node *bp = tree.v;
    CLRS_Ch12_BST_Impl_bst_node nd = *bp;
    if (Prims_op_LessThan(k, nd.key))
    {
      FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
      new_left =
        CLRS_Ch12_BST_Impl_tree_delete(nd.left,
          k,
          (
            (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
              .tag = FStar_Pervasives_Native_Some,
              .v = bp
            }
          ));
      *bp =
        (
          (CLRS_Ch12_BST_Impl_bst_node){
            .key = nd.key,
            .left = new_left,
            .right = nd.right,
            .p = nd.p
          }
        );
      return
        (
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = bp
          }
        );
    }
    else if (Prims_op_GreaterThan(k, nd.key))
    {
      FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
      new_right =
        CLRS_Ch12_BST_Impl_tree_delete(nd.right,
          k,
          (
            (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
              .tag = FStar_Pervasives_Native_Some,
              .v = bp
            }
          ));
      *bp =
        (
          (CLRS_Ch12_BST_Impl_bst_node){
            .key = nd.key,
            .left = nd.left,
            .right = new_right,
            .p = nd.p
          }
        );
      return
        (
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = bp
          }
        );
    }
    else if (nd.left.tag == FStar_Pervasives_Native_None)
    {
      set_parent_ptr(nd.right, parent);
      KRML_HOST_FREE(bp);
      return nd.right;
    }
    else if (nd.left.tag == FStar_Pervasives_Native_Some)
      if (nd.right.tag == FStar_Pervasives_Native_None)
      {
        set_parent_ptr(nd.left, parent);
        KRML_HOST_FREE(bp);
        return nd.left;
      }
      else if (nd.right.tag == FStar_Pervasives_Native_Some)
      {
        CLRS_Ch12_BST_Impl_bst_node *rbp = nd.right.v;
        krml_checked_int_t sk = CLRS_Ch12_BST_Impl_tree_minimum(nd.right, rbp);
        FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
        new_right =
          CLRS_Ch12_BST_Impl_tree_delete(nd.right,
            sk,
            (
              (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
                .tag = FStar_Pervasives_Native_Some,
                .v = bp
              }
            ));
        *bp =
          (
            (CLRS_Ch12_BST_Impl_bst_node){
              .key = sk,
              .left = nd.left,
              .right = new_right,
              .p = nd.p
            }
          );
        return
          (
            (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
              .tag = FStar_Pervasives_Native_Some,
              .v = bp
            }
          );
      }
      else
      {
        KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
          __FILE__,
          __LINE__,
          "unreachable (pattern matches are exhaustive in F*)");
        KRML_HOST_EXIT(255U);
      }
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

void
CLRS_Ch12_BST_Impl_free_bst(FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree)
{
  if (!(tree.tag == FStar_Pervasives_Native_None))
    if (tree.tag == FStar_Pervasives_Native_Some)
    {
      CLRS_Ch12_BST_Impl_bst_node *bp = tree.v;
      CLRS_Ch12_BST_Impl_bst_node node = *bp;
      CLRS_Ch12_BST_Impl_free_bst(node.left);
      CLRS_Ch12_BST_Impl_free_bst(node.right);
      KRML_HOST_FREE(bp);
    }
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
}

static bool test_bst_ptr(void)
{
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
  empty = { .tag = FStar_Pervasives_Native_None };
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
  parent = { .tag = FStar_Pervasives_Native_None };
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
  r1 = CLRS_Ch12_BST_Impl_tree_insert(empty, (krml_checked_int_t)2, parent);
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
  r2 = CLRS_Ch12_BST_Impl_tree_insert(r1, (krml_checked_int_t)1, parent);
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
  r3 = CLRS_Ch12_BST_Impl_tree_insert(r2, (krml_checked_int_t)3, parent);
  bool f1 = CLRS_Ch12_BST_Impl_tree_search(r3, (krml_checked_int_t)1);
  bool f2 = CLRS_Ch12_BST_Impl_tree_search(r3, (krml_checked_int_t)2);
  bool f3 = CLRS_Ch12_BST_Impl_tree_search(r3, (krml_checked_int_t)3);
  bool m0 = CLRS_Ch12_BST_Impl_tree_search(r3, (krml_checked_int_t)0);
  bool m4 = CLRS_Ch12_BST_Impl_tree_search(r3, (krml_checked_int_t)4);
  bool pass_search = f1 && f2 && f3 && !m0 && !m4;
  if (r3.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch12_BST_Impl_bst_node *bp = r3.v;
    krml_checked_int_t
    min_v =
      CLRS_Ch12_BST_Impl_tree_minimum((
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = bp
          }
        ),
        bp);
    krml_checked_int_t
    max_v =
      CLRS_Ch12_BST_Impl_tree_maximum((
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = bp
          }
        ),
        bp);
    bool pass_minmax = min_v == (krml_checked_int_t)1 && max_v == (krml_checked_int_t)3;
    FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
    r4 =
      CLRS_Ch12_BST_Impl_tree_delete((
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = bp
          }
        ),
        (krml_checked_int_t)2,
        parent);
    bool g2 = CLRS_Ch12_BST_Impl_tree_search(r4, (krml_checked_int_t)2);
    bool s1 = CLRS_Ch12_BST_Impl_tree_search(r4, (krml_checked_int_t)1);
    bool s3 = CLRS_Ch12_BST_Impl_tree_search(r4, (krml_checked_int_t)3);
    bool pass_delete = !g2 && s1 && s3;
    if (r4.tag == FStar_Pervasives_Native_Some)
    {
      CLRS_Ch12_BST_Impl_bst_node *bp4 = r4.v;
      krml_checked_int_t
      min4 =
        CLRS_Ch12_BST_Impl_tree_minimum((
            (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
              .tag = FStar_Pervasives_Native_Some,
              .v = bp4
            }
          ),
          bp4);
      krml_checked_int_t
      max4 =
        CLRS_Ch12_BST_Impl_tree_maximum((
            (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
              .tag = FStar_Pervasives_Native_Some,
              .v = bp4
            }
          ),
          bp4);
      bool pass_postdel = min4 == (krml_checked_int_t)1 && max4 == (krml_checked_int_t)3;
      CLRS_Ch12_BST_Impl_free_bst((
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_Some,
            .v = bp4
          }
        ));
      return pass_search && pass_minmax && pass_delete && pass_postdel;
    }
    else if (r4.tag == FStar_Pervasives_Native_None)
    {
      CLRS_Ch12_BST_Impl_free_bst((
          (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
            .tag = FStar_Pervasives_Native_None
          }
        ));
      return pass_search && pass_minmax && pass_delete;
    }
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
  }
  else if (r3.tag == FStar_Pervasives_Native_None)
  {
    CLRS_Ch12_BST_Impl_free_bst((
        (FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_){
          .tag = FStar_Pervasives_Native_None
        }
      ));
    return pass_search;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool CLRS_Ch12_BST_TestMain_main(void)
{
  return test_bst_ptr();
}

