/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch12.BST.TestMain=CLRS.Ch12.BST.ImplTest,CLRS.Ch12.BST.Impl -bundle CLRS.Ch12.BSTArray.TestMain=CLRS.Ch12.BSTArray.ImplTest,CLRS.Ch12.BSTArray.Impl -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch12_BST_TestMain.krml _output/CLRS_Ch12_BST_ImplTest.krml _output/CLRS_Ch12_BST_Impl.krml _output/FStar_Pervasives.krml _output/FStar_Pervasives_Native.krml _output/CLRS_Ch12_BSTArray_TestMain.krml _output/CLRS_Ch12_BSTArray_ImplTest.krml _output/CLRS_Ch12_BSTArray_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/CLRS_Ch12_BSTArray_TestMain.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"
#include "internal/CLRS_Ch12_BST_TestMain.h"

typedef struct bst_s
{
  krml_checked_int_t *keys;
  bool *valid;
  size_t cap;
}
bst;

static FStar_Pervasives_Native_option__size_t tree_search(bst t, krml_checked_int_t key)
{
  size_t current = (size_t)0U;
  bool found = false;
  size_t result_idx = (size_t)0U;
  size_t vc = current;
  bool vf0 = found;
  bool cond = vc < t.cap && !vf0;
  while (cond)
  {
    size_t idx = current;
    bool is_valid = t.valid[idx];
    if (!is_valid)
      current = t.cap;
    else
    {
      krml_checked_int_t current_key = t.keys[idx];
      if (current_key == key)
      {
        result_idx = idx;
        found = true;
      }
      else if (Prims_op_LessThan(key, current_key))
      {
        size_t two_idx = (size_t)2U * idx;
        size_t left_idx = two_idx + (size_t)1U;
        if (left_idx >= t.cap)
          current = t.cap;
        else
          current = left_idx;
      }
      else
      {
        size_t two_idx = (size_t)2U * idx;
        size_t right_idx = two_idx + (size_t)2U;
        if (right_idx >= t.cap)
          current = t.cap;
        else
          current = right_idx;
      }
    }
    size_t vc = current;
    bool vf = found;
    cond = vc < t.cap && !vf;
  }
  bool vf = found;
  size_t vr = result_idx;
  if (vf)
    return
      ((FStar_Pervasives_Native_option__size_t){ .tag = FStar_Pervasives_Native_Some, .v = vr });
  else
    return ((FStar_Pervasives_Native_option__size_t){ .tag = FStar_Pervasives_Native_None });
}

static bool tree_insert(bst t, krml_checked_int_t key)
{
  size_t current = (size_t)0U;
  bool done = false;
  bool success_flag = false;
  size_t vc = current;
  bool vd0 = done;
  bool cond = vc < t.cap && !vd0;
  while (cond)
  {
    size_t idx = current;
    bool is_valid = t.valid[idx];
    if (!is_valid)
    {
      t.keys[idx] = key;
      t.valid[idx] = true;
      success_flag = true;
      done = true;
    }
    else
    {
      krml_checked_int_t current_key = t.keys[idx];
      if (current_key == key)
        done = true;
      else if (Prims_op_LessThan(key, current_key))
      {
        size_t two_idx = (size_t)2U * idx;
        size_t left_idx = two_idx + (size_t)1U;
        if (left_idx >= t.cap)
          done = true;
        else
          current = left_idx;
      }
      else
      {
        size_t two_idx = (size_t)2U * idx;
        size_t right_idx = two_idx + (size_t)2U;
        if (right_idx >= t.cap)
          done = true;
        else
          current = right_idx;
      }
    }
    size_t vc = current;
    bool vd = done;
    cond = vc < t.cap && !vd;
  }
  return success_flag;
}

static bool uu___is_Some__size_t(FStar_Pervasives_Native_option__size_t projectee)
{
  if (projectee.tag == FStar_Pervasives_Native_Some)
    return true;
  else
    return false;
}

static bool test_bstarray_search_insert(void)
{
  krml_checked_int_t *kv = KRML_HOST_CALLOC((size_t)7U, sizeof (krml_checked_int_t));
  krml_checked_int_t *k_arr = kv;
  KRML_CHECK_SIZE(sizeof (bool), (size_t)7U);
  bool *vv = KRML_HOST_MALLOC(sizeof (bool) * (size_t)7U);
  if (vv != NULL)
    for (uint32_t _i = 0U; _i < (size_t)7U; ++_i)
      vv[_i] = false;
  bool *v_arr = vv;
  bst t = { .keys = k_arr, .valid = v_arr, .cap = (size_t)7U };
  FStar_Pervasives_Native_option__size_t r_empty = tree_search(t, (krml_checked_int_t)5);
  bool pass_empty = !uu___is_Some__size_t(r_empty);
  bool success = tree_insert(t, (krml_checked_int_t)5);
  FStar_Pervasives_Native_option__size_t r_found = tree_search(t, (krml_checked_int_t)5);
  bool pass_consistency = !success || uu___is_Some__size_t(r_found);
  FStar_Pervasives_Native_option__size_t r_miss = tree_search(t, (krml_checked_int_t)99);
  KRML_MAYBE_UNUSED_VAR(r_miss);
  KRML_HOST_FREE(kv);
  KRML_HOST_FREE(vv);
  return pass_empty && pass_consistency;
}

bool CLRS_Ch12_BSTArray_TestMain_main(void)
{
  return test_bstarray_search_insert();
}

