/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch12.BST.TestMain=CLRS.Ch12.BST.ImplTest,CLRS.Ch12.BST.Impl -bundle CLRS.Ch12.BSTArray.TestMain=CLRS.Ch12.BSTArray.ImplTest,CLRS.Ch12.BSTArray.Impl -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch12_BST_TestMain.krml _output/CLRS_Ch12_BST_ImplTest.krml _output/CLRS_Ch12_BST_Impl.krml _output/FStar_Pervasives.krml _output/FStar_Pervasives_Native.krml _output/CLRS_Ch12_BSTArray_TestMain.krml _output/CLRS_Ch12_BSTArray_ImplTest.krml _output/CLRS_Ch12_BSTArray_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch12_BST_TestMain_H
#define CLRS_Ch12_BST_TestMain_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch12_BST_TestMain_main(void);


#define CLRS_Ch12_BST_TestMain_H_DEFINED
#endif /* CLRS_Ch12_BST_TestMain_H */
