/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch22.ImplTestMain=CLRS.Ch22.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/csrc _output/CLRS_Ch22_ImplTestMain.krml _output/CLRS_Ch22_BFS_ImplTest.krml _output/CLRS_Ch22_DFS_ImplTest.krml _output/CLRS_Ch22_TopologicalSort_ImplTest.krml _output/CLRS_Ch22_BFS_Impl.krml _output/CLRS_Ch22_DFS_Impl.krml _output/CLRS_Ch22_TopologicalSort_Impl.krml _output/CLRS_Ch22_TopologicalSort_Impl_Defs.krml _output/CLRS_Ch22_Graph_Common.krml _output/CLRS_Ch22_TopologicalSort_Spec.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch22_ImplTestMain.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

static size_t
scan_for_white_neighbor(
  krml_checked_int_t *adj,
  krml_checked_int_t *color,
  size_t n,
  size_t u,
  size_t scan_pos,
  bool *found_ref,
  size_t *next_v_ref
)
{
  size_t scan = scan_pos;
  size_t __anf1 = scan;
  bool __anf00 = *found_ref;
  bool cond = __anf1 < n && __anf00;
  while (cond)
  {
    size_t vscan = scan;
    size_t offset = u * n;
    size_t idx = offset + vscan;
    krml_checked_int_t has_edge_val = adj[idx];
    krml_checked_int_t cvscan = color[vscan];
    if (has_edge_val != (krml_checked_int_t)0 && cvscan == (krml_checked_int_t)0)
    {
      *found_ref = true;
      *next_v_ref = vscan;
    }
    scan = vscan + (size_t)1U;
    size_t __anf1 = scan;
    bool __anf0 = *found_ref;
    cond = __anf1 < n && __anf0;
  }
  return scan;
}

static void
dfs_visit(
  krml_checked_int_t *adj,
  size_t n,
  size_t vs,
  krml_checked_int_t *color,
  krml_checked_int_t *d,
  krml_checked_int_t *f,
  krml_checked_int_t *pred,
  size_t *stack_data,
  size_t *scan_idx,
  size_t *stack_top,
  krml_checked_int_t *time_ref
)
{
  krml_checked_int_t t = *time_ref;
  *time_ref = Prims_op_Addition(t, (krml_checked_int_t)1);
  d[vs] = Prims_op_Addition(t, (krml_checked_int_t)1);
  color[vs] = (krml_checked_int_t)1;
  pred[vs] = (krml_checked_int_t)-1;
  scan_idx[vs] = (size_t)0U;
  size_t top = *stack_top;
  stack_data[top] = vs;
  *stack_top = top + (size_t)1U;
  size_t vtop1 = *stack_top;
  bool cond = vtop1 > (size_t)0U;
  while (cond)
  {
    size_t top1 = *stack_top;
    size_t u_idx = top1 - (size_t)1U;
    size_t u = stack_data[u_idx];
    size_t scan_pos = scan_idx[u];
    bool found_white = false;
    size_t next_v = (size_t)0U;
    size_t final_scan = scan_for_white_neighbor(adj, color, n, u, scan_pos, &found_white, &next_v);
    scan_idx[u] = final_scan;
    bool found = found_white;
    if (found)
    {
      size_t vv = next_v;
      krml_checked_int_t td = *time_ref;
      *time_ref = Prims_op_Addition(td, (krml_checked_int_t)1);
      d[vv] = Prims_op_Addition(td, (krml_checked_int_t)1);
      color[vv] = (krml_checked_int_t)1;
      pred[vv] = FStar_SizeT_v(u);
      scan_idx[vv] = (size_t)0U;
      size_t topd = *stack_top;
      stack_data[topd] = vv;
      *stack_top = topd + (size_t)1U;
    }
    else
    {
      color[u] = (krml_checked_int_t)2;
      krml_checked_int_t tf = *time_ref;
      *time_ref = Prims_op_Addition(tf, (krml_checked_int_t)1);
      f[u] = Prims_op_Addition(tf, (krml_checked_int_t)1);
      size_t topf = *stack_top;
      *stack_top = topf - (size_t)1U;
    }
    size_t vtop1 = *stack_top;
    cond = vtop1 > (size_t)0U;
  }
}

static void
maybe_dfs_visit(
  krml_checked_int_t *adj,
  size_t n,
  size_t vs,
  krml_checked_int_t cv,
  krml_checked_int_t *color,
  krml_checked_int_t *d,
  krml_checked_int_t *f,
  krml_checked_int_t *pred,
  size_t *stack_data,
  size_t *scan_idx,
  size_t *stack_top,
  krml_checked_int_t *time_ref
)
{
  if (cv == (krml_checked_int_t)0)
    dfs_visit(adj, n, vs, color, d, f, pred, stack_data, scan_idx, stack_top, time_ref);
}

static void
stack_dfs(
  krml_checked_int_t *adj,
  size_t n,
  krml_checked_int_t *color,
  krml_checked_int_t *d,
  krml_checked_int_t *f,
  krml_checked_int_t *pred,
  size_t *stack_data,
  size_t *scan_idx
)
{
  size_t i = (size_t)0U;
  size_t __anf00 = i;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t vi = i;
    color[vi] = (krml_checked_int_t)0;
    d[vi] = (krml_checked_int_t)-1;
    f[vi] = (krml_checked_int_t)-1;
    pred[vi] = (krml_checked_int_t)-1;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
  i = (size_t)0U;
  size_t __anf01 = i;
  bool cond0 = __anf01 < n;
  while (cond0)
  {
    size_t vi = i;
    scan_idx[vi] = (size_t)0U;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond0 = __anf0 < n;
  }
  krml_checked_int_t time_ref = (krml_checked_int_t)0;
  size_t stack_top = (size_t)0U;
  size_t s = (size_t)0U;
  size_t __anf0 = s;
  bool cond1 = __anf0 < n;
  while (cond1)
  {
    size_t vs = s;
    krml_checked_int_t cs = color[vs];
    maybe_dfs_visit(adj,
      n,
      vs,
      cs,
      color,
      d,
      f,
      pred,
      stack_data,
      scan_idx,
      &stack_top,
      &time_ref);
    s = vs + (size_t)1U;
    size_t __anf0 = s;
    cond1 = __anf0 < n;
  }
}

static bool test_dfs_3(void)
{
  krml_checked_int_t *adj_v = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *adj = adj_v;
  adj[1U] = (krml_checked_int_t)1;
  adj[5U] = (krml_checked_int_t)1;
  krml_checked_int_t *color_v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *color = color_v;
  krml_checked_int_t *d_v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *d_arr = d_v;
  krml_checked_int_t *f_v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *f_arr = f_v;
  krml_checked_int_t *pred_v = KRML_HOST_MALLOC(sizeof (krml_checked_int_t) * (size_t)3U);
  if (pred_v != NULL)
    for (uint32_t _i = 0U; _i < (size_t)3U; ++_i)
      pred_v[_i] = (krml_checked_int_t)-1;
  krml_checked_int_t *pred_arr = pred_v;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *stack_v = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *stack_data = stack_v;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *scan_v = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *scan_idx = scan_v;
  stack_dfs(adj, (size_t)3U, color, d_arr, f_arr, pred_arr, stack_data, scan_idx);
  krml_checked_int_t c0 = color[0U];
  krml_checked_int_t c1 = color[1U];
  krml_checked_int_t c2 = color[2U];
  krml_checked_int_t rd0 = d_arr[0U];
  krml_checked_int_t rd1 = d_arr[1U];
  krml_checked_int_t rd2 = d_arr[2U];
  krml_checked_int_t rf0 = f_arr[0U];
  krml_checked_int_t rf1 = f_arr[1U];
  krml_checked_int_t rf2 = f_arr[2U];
  bool
  result =
    c0 == (krml_checked_int_t)2 && c1 == (krml_checked_int_t)2 && c2 == (krml_checked_int_t)2 &&
      Prims_op_LessThan(rd0,
        rf0)
    && Prims_op_LessThan(rd1, rf1)
    && Prims_op_LessThan(rd2, rf2);
  KRML_HOST_FREE(adj_v);
  KRML_HOST_FREE(color_v);
  KRML_HOST_FREE(d_v);
  KRML_HOST_FREE(f_v);
  KRML_HOST_FREE(pred_v);
  KRML_HOST_FREE(stack_v);
  KRML_HOST_FREE(scan_v);
  return result;
}

static void
discover_vertex(
  krml_checked_int_t *color,
  krml_checked_int_t *dist,
  krml_checked_int_t *pred,
  size_t *queue_data,
  size_t *q_tail,
  size_t u,
  size_t vv,
  krml_checked_int_t du
)
{
  color[vv] = (krml_checked_int_t)1;
  dist[vv] = Prims_op_Addition(du, (krml_checked_int_t)1);
  pred[vv] = FStar_SizeT_v(u);
  size_t t = *q_tail;
  queue_data[t] = vv;
  *q_tail = t + (size_t)1U;
}

static void
maybe_discover(
  krml_checked_int_t *color,
  krml_checked_int_t *dist,
  krml_checked_int_t *pred,
  size_t *queue_data,
  size_t *q_tail,
  size_t u,
  size_t vv,
  krml_checked_int_t du,
  krml_checked_int_t has_edge_val,
  krml_checked_int_t cv
)
{
  if (has_edge_val != (krml_checked_int_t)0 && cv == (krml_checked_int_t)0)
    discover_vertex(color, dist, pred, queue_data, q_tail, u, vv, du);
}

static void
queue_bfs(
  krml_checked_int_t *adj,
  size_t n,
  size_t source,
  krml_checked_int_t *color,
  krml_checked_int_t *dist,
  krml_checked_int_t *pred,
  size_t *queue_data
)
{
  size_t i = (size_t)0U;
  size_t __anf00 = i;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t vi = i;
    color[vi] = (krml_checked_int_t)0;
    dist[vi] = (krml_checked_int_t)-1;
    pred[vi] = (krml_checked_int_t)-1;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
  color[source] = (krml_checked_int_t)1;
  dist[source] = (krml_checked_int_t)0;
  pred[source] = (krml_checked_int_t)-1;
  size_t q_head = (size_t)0U;
  size_t q_tail = (size_t)0U;
  queue_data[0U] = source;
  q_tail = (size_t)1U;
  size_t vh = q_head;
  size_t vt0 = q_tail;
  bool cond0 = vh < vt0;
  while (cond0)
  {
    size_t vhead = q_head;
    size_t u = queue_data[vhead];
    q_head = vhead + (size_t)1U;
    krml_checked_int_t du = dist[u];
    size_t v = (size_t)0U;
    size_t __anf0 = v;
    bool cond = __anf0 < n;
    while (cond)
    {
      size_t vv = v;
      size_t offset = u * n;
      size_t idx = offset + vv;
      krml_checked_int_t has_edge_val = adj[idx];
      krml_checked_int_t cv = color[vv];
      maybe_discover(color, dist, pred, queue_data, &q_tail, u, vv, du, has_edge_val, cv);
      v = vv + (size_t)1U;
      size_t __anf0 = v;
      cond = __anf0 < n;
    }
    color[u] = (krml_checked_int_t)2;
    size_t vh = q_head;
    size_t vt = q_tail;
    cond0 = vh < vt;
  }
}

static bool test_bfs_3(void)
{
  krml_checked_int_t *adj_v = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *adj = adj_v;
  adj[1U] = (krml_checked_int_t)1;
  adj[5U] = (krml_checked_int_t)1;
  krml_checked_int_t *color_v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *color = color_v;
  krml_checked_int_t *dist_v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *dist = dist_v;
  krml_checked_int_t *pred_v = KRML_HOST_MALLOC(sizeof (krml_checked_int_t) * (size_t)3U);
  if (pred_v != NULL)
    for (uint32_t _i = 0U; _i < (size_t)3U; ++_i)
      pred_v[_i] = (krml_checked_int_t)-1;
  krml_checked_int_t *pred_arr = pred_v;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *queue_v = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *queue_data = queue_v;
  queue_bfs(adj, (size_t)3U, (size_t)0U, color, dist, pred_arr, queue_data);
  krml_checked_int_t d0 = dist[0U];
  krml_checked_int_t d1 = dist[1U];
  krml_checked_int_t d2 = dist[2U];
  bool
  result =
    d0 == (krml_checked_int_t)0 && d1 == (krml_checked_int_t)1 && d2 == (krml_checked_int_t)2;
  KRML_HOST_FREE(adj_v);
  KRML_HOST_FREE(color_v);
  KRML_HOST_FREE(dist_v);
  KRML_HOST_FREE(pred_v);
  KRML_HOST_FREE(queue_v);
  return result;
}

static void
maybe_enqueue(
  krml_checked_int_t *adj,
  krml_checked_int_t *in_degree,
  size_t *queue_data,
  size_t *queue_tail,
  size_t u,
  size_t vv,
  size_t n
)
{
  size_t idx = u * n + vv;
  krml_checked_int_t edge_val = adj[idx];
  krml_checked_int_t old_deg = in_degree[vv];
  size_t vqt = *queue_tail;
  if (edge_val != (krml_checked_int_t)0)
  {
    krml_checked_int_t new_deg = Prims_op_Subtraction(old_deg, (krml_checked_int_t)1);
    in_degree[vv] = new_deg;
    if (new_deg == (krml_checked_int_t)0 && vqt < n)
    {
      queue_data[vqt] = vv;
      *queue_tail = vqt + (size_t)1U;
    }
  }
}

static void
pn_loop_step(
  krml_checked_int_t *adj,
  krml_checked_int_t *in_degree,
  size_t *queue_data,
  size_t *queue_tail,
  size_t u,
  size_t vv,
  size_t n
)
{
  maybe_enqueue(adj, in_degree, queue_data, queue_tail, u, vv, n);
}

static void
process_neighbors(
  krml_checked_int_t *adj,
  krml_checked_int_t *in_degree,
  size_t *queue_data,
  size_t *queue_tail,
  size_t u,
  size_t n
)
{
  size_t v = (size_t)0U;
  size_t __anf0 = v;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t vv = v;
    pn_loop_step(adj, in_degree, queue_data, queue_tail, u, vv, n);
    v = vv + (size_t)1U;
    size_t __anf0 = v;
    cond = __anf0 < n;
  }
}

static krml_checked_int_t *topological_sort(krml_checked_int_t *adj, size_t n)
{
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), n);
  krml_checked_int_t *in_degree_v = KRML_HOST_CALLOC(n, sizeof (krml_checked_int_t));
  krml_checked_int_t *in_degree = in_degree_v;
  size_t i = (size_t)0U;
  size_t __anf00 = i;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t vi = i;
    size_t j = (size_t)0U;
    size_t __anf0 = j;
    bool cond0 = __anf0 < n;
    while (cond0)
    {
      size_t vj = j;
      size_t idx = vi * n + vj;
      krml_checked_int_t edge_val = adj[idx];
      krml_checked_int_t old_deg = in_degree[vj];
      krml_checked_int_t new_deg;
      if (edge_val != (krml_checked_int_t)0)
        new_deg = Prims_op_Addition(old_deg, (krml_checked_int_t)1);
      else
        new_deg = old_deg;
      in_degree[vj] = new_deg;
      j = vj + (size_t)1U;
      size_t __anf0 = j;
      cond0 = __anf0 < n;
    }
    i = vi + (size_t)1U;
    size_t __anf00 = i;
    cond = __anf00 < n;
  }
  KRML_CHECK_SIZE(sizeof (size_t), n);
  size_t *queue_v = KRML_HOST_CALLOC(n, sizeof (size_t));
  size_t *queue = queue_v;
  size_t queue_tail = (size_t)0U;
  size_t i1 = (size_t)0U;
  size_t __anf01 = i1;
  bool cond0 = __anf01 < n;
  while (cond0)
  {
    size_t vi = i1;
    size_t vqt = queue_tail;
    krml_checked_int_t deg = in_degree[vi];
    queue[vqt] = vi;
    size_t new_vqt;
    if (deg == (krml_checked_int_t)0)
      new_vqt = vqt + (size_t)1U;
    else
      new_vqt = vqt;
    queue_tail = new_vqt;
    i1 = vi + (size_t)1U;
    size_t __anf0 = i1;
    cond0 = __anf0 < n;
  }
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), n);
  krml_checked_int_t *output_v = KRML_HOST_CALLOC(n, sizeof (krml_checked_int_t));
  krml_checked_int_t *output = output_v;
  size_t queue_head = (size_t)0U;
  size_t out_idx = (size_t)0U;
  size_t __anf1 = queue_head;
  size_t __anf02 = queue_tail;
  bool cond1 = __anf1 < __anf02;
  while (cond1)
  {
    size_t vqh = queue_head;
    size_t vout = out_idx;
    size_t u = queue[vqh];
    krml_checked_int_t u_int = FStar_SizeT_v(u);
    output[vout] = u_int;
    size_t new_vout = vout + (size_t)1U;
    out_idx = new_vout;
    queue_head = vqh + (size_t)1U;
    process_neighbors(adj, in_degree, queue, &queue_tail, u, n);
    size_t __anf1 = queue_head;
    size_t __anf0 = queue_tail;
    cond1 = __anf1 < __anf0;
  }
  KRML_HOST_FREE(in_degree_v);
  KRML_HOST_FREE(queue_v);
  return output_v;
}

static bool test_topo_sort_3(void)
{
  krml_checked_int_t *adj_v = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *adj = adj_v;
  adj[1U] = (krml_checked_int_t)1;
  adj[5U] = (krml_checked_int_t)1;
  krml_checked_int_t *output = topological_sort(adj, (size_t)3U);
  krml_checked_int_t *out_arr = output;
  krml_checked_int_t v0 = out_arr[0U];
  krml_checked_int_t v1 = out_arr[1U];
  krml_checked_int_t v2 = out_arr[2U];
  bool
  result =
    Prims_op_GreaterThanOrEqual(v0, (krml_checked_int_t)0) &&
      Prims_op_LessThan(v0,
        (krml_checked_int_t)3)
    && Prims_op_GreaterThanOrEqual(v1, (krml_checked_int_t)0)
    && Prims_op_LessThan(v1, (krml_checked_int_t)3)
    && Prims_op_GreaterThanOrEqual(v2, (krml_checked_int_t)0)
    && Prims_op_LessThan(v2, (krml_checked_int_t)3)
    && v0 != v1
    && v0 != v2
    && v1 != v2;
  KRML_HOST_FREE(output);
  KRML_HOST_FREE(adj_v);
  return result;
}

bool CLRS_Ch22_ImplTestMain_run_all_tests(void)
{
  bool r1 = test_bfs_3();
  bool r2 = test_dfs_3();
  bool r3 = test_topo_sort_3();
  return r1 && r2 && r3;
}

