/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch22.ImplTestMain=CLRS.Ch22.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/csrc _output/CLRS_Ch22_ImplTestMain.krml _output/CLRS_Ch22_BFS_ImplTest.krml _output/CLRS_Ch22_DFS_ImplTest.krml _output/CLRS_Ch22_TopologicalSort_ImplTest.krml _output/CLRS_Ch22_BFS_Impl.krml _output/CLRS_Ch22_DFS_Impl.krml _output/CLRS_Ch22_TopologicalSort_Impl.krml _output/CLRS_Ch22_TopologicalSort_Impl_Defs.krml _output/CLRS_Ch22_Graph_Common.krml _output/CLRS_Ch22_TopologicalSort_Spec.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch22_ImplTestMain_H
#define CLRS_Ch22_ImplTestMain_H

#include "krmllib.h"

#include "krml/internal/compat.h"
#include "fstar_support.h"

bool CLRS_Ch22_ImplTestMain_run_all_tests(void);


#define CLRS_Ch22_ImplTestMain_H_DEFINED
#endif /* CLRS_Ch22_ImplTestMain_H */
