/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch32.NaiveStringMatch.ImplTest+CLRS.Ch32.KMP.ImplTest+CLRS.Ch32.RabinKarp.ImplTest+CLRS.Ch32.NaiveStringMatch+CLRS.Ch32.KMP+CLRS.Ch32.RabinKarp=[rename=Ch32_StringMatch] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -no-prefix CLRS.Ch32.NaiveStringMatch.ImplTest -no-prefix CLRS.Ch32.KMP.ImplTest -no-prefix CLRS.Ch32.RabinKarp.ImplTest -no-prefix CLRS.Ch32.NaiveStringMatch -no-prefix CLRS.Ch32.KMP -no-prefix CLRS.Ch32.RabinKarp -tmpdir _extract _output/CLRS_Ch32_NaiveStringMatch_ImplTest.krml _output/CLRS_Ch32_NaiveStringMatch.krml _output/CLRS_Ch32_KMP_ImplTest.krml _output/CLRS_Ch32_KMP.krml _output/CLRS_Ch32_RabinKarp_ImplTest.krml _output/CLRS_Ch32_RabinKarp.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_PulseCore_Prims_H
#define internal_FStar_Pulse_PulseCore_Prims_H

#include "krmllib.h"

#include "krml/internal/compat.h"

extern krml_checked_int_t Prims_op_Multiply(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Modulus(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_FStar_Pulse_PulseCore_Prims_H_DEFINED
#endif /* internal_FStar_Pulse_PulseCore_Prims_H */
