/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch07_Quicksort_ImplTest.krml _output/CLRS_Ch07_Quicksort_Impl.krml _output/CLRS_Ch07_Partition_Impl.krml _output/CLRS_Ch07_Partition_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_PulseCore_Prims_H
#define internal_FStar_Pulse_PulseCore_Prims_H

#include "krmllib.h"

#include "krml/internal/compat.h"

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_LessThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_FStar_Pulse_PulseCore_Prims_H_DEFINED
#endif /* internal_FStar_Pulse_PulseCore_Prims_H */
