/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch26.MaxFlow.ImplTest=CLRS.Ch26.MaxFlow.* -tmpdir _output _output/CLRS_Ch26_MaxFlow_ImplTest.krml _output/CLRS_Ch26_MaxFlow_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_Prims_H
#define internal_Prims_H

#include "krmllib.h"

#include "krml/internal/compat.h"

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_Prims_H_DEFINED
#endif /* internal_Prims_H */
