/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch32.NaiveStringMatch.ImplTest+CLRS.Ch32.KMP.ImplTest+CLRS.Ch32.RabinKarp.ImplTest+CLRS.Ch32.NaiveStringMatch+CLRS.Ch32.KMP+CLRS.Ch32.RabinKarp=[rename=Ch32_StringMatch] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -no-prefix CLRS.Ch32.NaiveStringMatch.ImplTest -no-prefix CLRS.Ch32.KMP.ImplTest -no-prefix CLRS.Ch32.RabinKarp.ImplTest -no-prefix CLRS.Ch32.NaiveStringMatch -no-prefix CLRS.Ch32.KMP -no-prefix CLRS.Ch32.RabinKarp -tmpdir _extract _output/CLRS_Ch32_NaiveStringMatch_ImplTest.krml _output/CLRS_Ch32_NaiveStringMatch.krml _output/CLRS_Ch32_KMP_ImplTest.krml _output/CLRS_Ch32_KMP.krml _output/CLRS_Ch32_RabinKarp_ImplTest.krml _output/CLRS_Ch32_RabinKarp.krml
  F* version: <unknown>
  KaRaMeL version: 7bdb6cb2fd7661f4a0dade9ccae810451cb51746
 */

#include "Ch32_StringMatch.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

bool sz_eq(size_t a, size_t b)
{
  return !(a < b || b < a);
}

size_t
naive_string_match__krml_checked_int_t(
  krml_checked_int_t *text,
  krml_checked_int_t *pattern,
  size_t n,
  size_t m
)
{
  size_t count = (size_t)0U;
  size_t s = (size_t)0U;
  size_t __anf00 = s;
  bool cond = __anf00 <= n - m;
  while (cond)
  {
    size_t vs = s;
    size_t j = (size_t)0U;
    bool all_match = true;
    size_t __anf1 = j;
    bool __anf00 = all_match;
    bool cond0 = __anf1 < m && __anf00;
    while (cond0)
    {
      size_t vj = j;
      krml_checked_int_t text_char = text[vs + vj];
      krml_checked_int_t pat_char = pattern[vj];
      if (text_char != pat_char)
        all_match = false;
      j = vj + (size_t)1U;
      size_t __anf1 = j;
      bool __anf0 = all_match;
      cond0 = __anf1 < m && __anf0;
    }
    size_t final_j = j;
    bool final_all_match = all_match;
    size_t vcount_before = count;
    if (final_j == m && final_all_match)
      count = vcount_before + (size_t)1U;
    s = vs + (size_t)1U;
    size_t __anf0 = s;
    cond = __anf0 <= n - m;
  }
  return count;
}

bool test_naive_string_match(void)
{
  krml_checked_int_t *tv = KRML_HOST_CALLOC((size_t)5U, sizeof (krml_checked_int_t));
  krml_checked_int_t *text = tv;
  text[0U] = (krml_checked_int_t)1;
  text[1U] = (krml_checked_int_t)2;
  text[2U] = (krml_checked_int_t)1;
  text[3U] = (krml_checked_int_t)2;
  text[4U] = (krml_checked_int_t)1;
  krml_checked_int_t *pv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *pat = pv;
  pat[0U] = (krml_checked_int_t)1;
  pat[1U] = (krml_checked_int_t)2;
  pat[2U] = (krml_checked_int_t)1;
  size_t count = naive_string_match__krml_checked_int_t(text, pat, (size_t)5U, (size_t)3U);
  bool pass = !(count < (size_t)2U || (size_t)2U < count);
  KRML_HOST_FREE(tv);
  KRML_HOST_FREE(pv);
  return pass;
}

bool sz_eq0(size_t a, size_t b)
{
  return !(a < b || b < a);
}

bool test_kmp_string_match(void)
{
  krml_checked_int_t *tv = KRML_HOST_CALLOC((size_t)5U, sizeof (krml_checked_int_t));
  krml_checked_int_t *text = tv;
  text[0U] = (krml_checked_int_t)0;
  text[1U] = (krml_checked_int_t)1;
  text[2U] = (krml_checked_int_t)0;
  text[3U] = (krml_checked_int_t)1;
  text[4U] = (krml_checked_int_t)0;
  krml_checked_int_t *pv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *pat = pv;
  pat[0U] = (krml_checked_int_t)0;
  pat[1U] = (krml_checked_int_t)1;
  pat[2U] = (krml_checked_int_t)0;
  size_t count = kmp_string_match(text, pat, (size_t)5U, (size_t)3U);
  bool pass = !(count < (size_t)2U || (size_t)2U < count);
  KRML_HOST_FREE(tv);
  KRML_HOST_FREE(pv);
  return pass;
}

bool int_eq(krml_checked_int_t a, krml_checked_int_t b)
{
  return !(Prims_op_LessThan(a, b) || Prims_op_LessThan(b, a));
}

bool test_rabin_karp(void)
{
  krml_checked_int_t *tv = KRML_HOST_CALLOC((size_t)5U, sizeof (krml_checked_int_t));
  krml_checked_int_t *text = tv;
  text[0U] = (krml_checked_int_t)1;
  text[1U] = (krml_checked_int_t)2;
  text[2U] = (krml_checked_int_t)1;
  text[3U] = (krml_checked_int_t)2;
  text[4U] = (krml_checked_int_t)1;
  krml_checked_int_t *pv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *pat = pv;
  pat[0U] = (krml_checked_int_t)1;
  pat[1U] = (krml_checked_int_t)2;
  pat[2U] = (krml_checked_int_t)1;
  krml_checked_int_t
  count =
    rabin_karp(text,
      pat,
      (size_t)5U,
      (size_t)3U,
      (krml_checked_int_t)10,
      (krml_checked_int_t)13);
  bool
  pass =
    !(Prims_op_LessThan(count, (krml_checked_int_t)2) ||
      Prims_op_LessThan((krml_checked_int_t)2,
        count));
  KRML_HOST_FREE(tv);
  KRML_HOST_FREE(pv);
  return pass;
}

size_t
kmp_matcher(
  krml_checked_int_t *text,
  krml_checked_int_t *pattern,
  size_t *pi,
  size_t n,
  size_t m
)
{
  size_t q = (size_t)0U;
  size_t count_matches = (size_t)0U;
  size_t i = (size_t)0U;
  size_t __anf00 = i;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t vi = i;
    bool done_follow = false;
    bool __anf0 = done_follow;
    bool cond0 = !__anf0;
    while (cond0)
    {
      size_t vq = q;
      krml_checked_int_t text_char = text[vi];
      krml_checked_int_t pat_char = pattern[vq];
      bool should_follow = vq > (size_t)0U && pat_char != text_char;
      if (should_follow)
      {
        size_t safe_idx = vq - (size_t)1U;
        size_t pi_val = pi[safe_idx];
        q = pi_val;
      }
      else
        done_follow = true;
      bool __anf0 = done_follow;
      cond0 = !__anf0;
    }
    size_t vq_after = q;
    krml_checked_int_t text_char_final = text[vi];
    krml_checked_int_t pat_char_final = pattern[vq_after];
    bool chars_match = pat_char_final == text_char_final;
    size_t new_q_val;
    if (chars_match)
      new_q_val = vq_after + (size_t)1U;
    else
      new_q_val = vq_after;
    q = new_q_val;
    size_t vq_final = q;
    bool have_match = vq_final == m;
    size_t old_count = count_matches;
    size_t new_count_val;
    if (have_match)
      new_count_val = old_count + (size_t)1U;
    else
      new_count_val = old_count;
    size_t pi_idx_for_reset = m - (size_t)1U;
    size_t pi_val_for_reset = pi[pi_idx_for_reset];
    size_t new_q_after_match;
    if (have_match)
      new_q_after_match = pi_val_for_reset;
    else
      new_q_after_match = vq_final;
    size_t vi_next = vi + (size_t)1U;
    count_matches = new_count_val;
    q = new_q_after_match;
    i = vi_next;
    size_t __anf00 = i;
    cond = __anf00 < n;
  }
  return count_matches;
}

void
compute_prefix_function__krml_checked_int_t(krml_checked_int_t *pattern, size_t *pi, size_t m)
{
  size_t k = (size_t)0U;
  size_t q = (size_t)1U;
  size_t __anf00 = q;
  bool cond = __anf00 < m;
  while (cond)
  {
    size_t vq = q;
    bool done_inner = false;
    bool __anf0 = done_inner;
    bool cond0 = !__anf0;
    while (cond0)
    {
      size_t vk = k;
      bool vk_pos = vk > (size_t)0U;
      size_t safe_pi_idx;
      if (vk_pos)
        safe_pi_idx = vk - (size_t)1U;
      else
        safe_pi_idx = (size_t)0U;
      size_t pi_prev = pi[safe_pi_idx];
      krml_checked_int_t pk = pattern[vk];
      krml_checked_int_t pq = pattern[vq];
      bool should_update = vk_pos && pk != pq;
      if (should_update)
        k = pi_prev;
      else
        done_inner = true;
      bool __anf0 = done_inner;
      cond0 = !__anf0;
    }
    size_t vk_after_inner = k;
    krml_checked_int_t pk_final = pattern[vk_after_inner];
    krml_checked_int_t pq_final = pattern[vq];
    bool chars_match = pk_final == pq_final;
    size_t new_k_final;
    if (chars_match)
      new_k_final = vk_after_inner + (size_t)1U;
    else
      new_k_final = vk_after_inner;
    k = new_k_final;
    size_t final_k = k;
    pi[vq] = final_k;
    q = vq + (size_t)1U;
    size_t __anf00 = q;
    cond = __anf00 < m;
  }
}

size_t
kmp_string_match(krml_checked_int_t *text, krml_checked_int_t *pattern, size_t n, size_t m)
{
  KRML_CHECK_SIZE(sizeof (size_t), m);
  size_t *pi = KRML_HOST_CALLOC(m, sizeof (size_t));
  compute_prefix_function__krml_checked_int_t(pattern, pi, m);
  size_t result = kmp_matcher(text, pattern, pi, n, m);
  KRML_HOST_FREE(pi);
  return result;
}

krml_checked_int_t
compute_hash(
  krml_checked_int_t *arr,
  krml_checked_int_t d,
  krml_checked_int_t q,
  size_t start,
  size_t len
)
{
  krml_checked_int_t acc = (krml_checked_int_t)0;
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < len;
  while (cond)
  {
    size_t vi = i;
    krml_checked_int_t vacc = acc;
    krml_checked_int_t c = arr[start + vi];
    krml_checked_int_t
    new_acc = Prims_op_Modulus(Prims_op_Addition(Prims_op_Multiply(d, vacc), c), q);
    acc = new_acc;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < len;
  }
  return acc;
}

krml_checked_int_t compute_pow_mod(krml_checked_int_t d, size_t exp, krml_checked_int_t q)
{
  krml_checked_int_t acc = Prims_op_Modulus((krml_checked_int_t)1, q);
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < exp;
  while (cond)
  {
    size_t vi = i;
    krml_checked_int_t vacc = acc;
    krml_checked_int_t new_acc = Prims_op_Modulus(Prims_op_Multiply(d, vacc), q);
    acc = new_acc;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < exp;
  }
  return acc;
}

krml_checked_int_t
rabin_karp(
  krml_checked_int_t *text,
  krml_checked_int_t *pattern,
  size_t n,
  size_t m,
  krml_checked_int_t d,
  krml_checked_int_t q
)
{
  krml_checked_int_t p_hash = compute_hash(pattern, d, q, (size_t)0U, m);
  krml_checked_int_t t_hash_init = compute_hash(text, d, q, (size_t)0U, m);
  size_t ite0;
  if (m == (size_t)1U)
    ite0 = (size_t)0U;
  else
    ite0 = m - (size_t)1U;
  krml_checked_int_t h = compute_pow_mod(d, ite0, q);
  krml_checked_int_t t_hash = t_hash_init;
  krml_checked_int_t count = (krml_checked_int_t)0;
  size_t s = (size_t)0U;
  size_t max_s = n - m;
  size_t __anf00 = s;
  bool cond = __anf00 <= max_s;
  while (cond)
  {
    size_t vs = s;
    krml_checked_int_t vcount_outer = count;
    krml_checked_int_t vt_hash_outer = t_hash;
    bool hash_match = vt_hash_outer == p_hash;
    krml_checked_int_t ite;
    if (hash_match)
      ite = (krml_checked_int_t)1;
    else
      ite = (krml_checked_int_t)0;
    krml_checked_int_t verified = ite;
    size_t j = (size_t)0U;
    size_t __anf1 = j;
    krml_checked_int_t __anf00 = verified;
    bool cond0 = __anf1 < m && __anf00 == (krml_checked_int_t)1;
    while (cond0)
    {
      size_t vj = j;
      krml_checked_int_t text_char = text[vs + vj];
      krml_checked_int_t pat_char = pattern[vj];
      krml_checked_int_t current_verified = verified;
      bool chars_match = text_char == pat_char;
      krml_checked_int_t new_verified;
      if (chars_match)
        new_verified = current_verified;
      else
        new_verified = (krml_checked_int_t)0;
      verified = new_verified;
      j = vj + (size_t)1U;
      size_t __anf1 = j;
      krml_checked_int_t __anf0 = verified;
      cond0 = __anf1 < m && __anf0 == (krml_checked_int_t)1;
    }
    krml_checked_int_t final_verified = verified;
    size_t final_j = j;
    krml_checked_int_t should_count;
    if (final_verified == (krml_checked_int_t)1 && final_j == m)
      should_count = (krml_checked_int_t)1;
    else
      should_count = (krml_checked_int_t)0;
    count = Prims_op_Addition(vcount_outer, should_count);
    bool is_last = vs == max_s;
    if (is_last)
    {
      t_hash = vt_hash_outer;
      s = vs + (size_t)1U;
    }
    else
    {
      krml_checked_int_t old_char = text[vs];
      krml_checked_int_t new_char = text[vs + m];
      krml_checked_int_t
      new_hash =
        Prims_op_Modulus(Prims_op_Addition(Prims_op_Multiply(d,
              Prims_op_Modulus(Prims_op_Subtraction(Prims_op_Addition(vt_hash_outer, q),
                  Prims_op_Modulus(Prims_op_Multiply(old_char, h), q)),
                q)),
            new_char),
          q);
      t_hash = new_hash;
      s = vs + (size_t)1U;
    }
    size_t __anf0 = s;
    cond = __anf0 <= max_s;
  }
  return count;
}

