/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch32.NaiveStringMatch.ImplTest+CLRS.Ch32.KMP.ImplTest+CLRS.Ch32.RabinKarp.ImplTest+CLRS.Ch32.NaiveStringMatch+CLRS.Ch32.KMP+CLRS.Ch32.RabinKarp=[rename=Ch32_StringMatch] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -no-prefix CLRS.Ch32.NaiveStringMatch.ImplTest -no-prefix CLRS.Ch32.KMP.ImplTest -no-prefix CLRS.Ch32.RabinKarp.ImplTest -no-prefix CLRS.Ch32.NaiveStringMatch -no-prefix CLRS.Ch32.KMP -no-prefix CLRS.Ch32.RabinKarp -tmpdir _extract _output/CLRS_Ch32_NaiveStringMatch_ImplTest.krml _output/CLRS_Ch32_NaiveStringMatch.krml _output/CLRS_Ch32_KMP_ImplTest.krml _output/CLRS_Ch32_KMP.krml _output/CLRS_Ch32_RabinKarp_ImplTest.krml _output/CLRS_Ch32_RabinKarp.krml
  F* version: <unknown>
  KaRaMeL version: 7bdb6cb2fd7661f4a0dade9ccae810451cb51746
 */

#ifndef Ch32_StringMatch_H
#define Ch32_StringMatch_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool sz_eq(size_t a, size_t b);

size_t
naive_string_match__krml_checked_int_t(
  krml_checked_int_t *text,
  krml_checked_int_t *pattern,
  size_t n,
  size_t m
);

bool test_naive_string_match(void);

bool sz_eq0(size_t a, size_t b);

bool test_kmp_string_match(void);

bool int_eq(krml_checked_int_t a, krml_checked_int_t b);

bool test_rabin_karp(void);

size_t
kmp_matcher(
  krml_checked_int_t *text,
  krml_checked_int_t *pattern,
  size_t *pi,
  size_t n,
  size_t m
);

void
compute_prefix_function__krml_checked_int_t(krml_checked_int_t *pattern, size_t *pi, size_t m);

size_t
kmp_string_match(krml_checked_int_t *text, krml_checked_int_t *pattern, size_t n, size_t m);

krml_checked_int_t
compute_hash(
  krml_checked_int_t *arr,
  krml_checked_int_t d,
  krml_checked_int_t q,
  size_t start,
  size_t len
);

krml_checked_int_t compute_pow_mod(krml_checked_int_t d, size_t exp, krml_checked_int_t q);

krml_checked_int_t
rabin_karp(
  krml_checked_int_t *text,
  krml_checked_int_t *pattern,
  size_t n,
  size_t m,
  krml_checked_int_t d,
  krml_checked_int_t q
);


#define Ch32_StringMatch_H_DEFINED
#endif /* Ch32_StringMatch_H */
