/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch24.BellmanFord.ImplTest+CLRS.Ch24.Dijkstra.ImplTest=CLRS.Ch24.*[rename=Ch24_SSSP] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch24_BellmanFord_ImplTest.krml _output/CLRS_Ch24_BellmanFord_Impl.krml _output/CLRS_Ch24_Dijkstra_ImplTest.krml _output/CLRS_Ch24_Dijkstra_Impl.krml _output/CLRS_Ch24_Dijkstra.krml _output/CLRS_Ch24_ShortestPath_Inf.krml _output/CLRS_Ch24_ShortestPath_Spec.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef Ch24_SSSP_H
#define Ch24_SSSP_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch24_BellmanFord_ImplTest_test_bellman_ford_3(void);

bool CLRS_Ch24_Dijkstra_ImplTest_test_dijkstra_3(void);


#define Ch24_SSSP_H_DEFINED
#endif /* Ch24_SSSP_H */
