/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch24.BellmanFord.ImplTest+CLRS.Ch24.Dijkstra.ImplTest=CLRS.Ch24.*[rename=Ch24_SSSP] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch24_BellmanFord_ImplTest.krml _output/CLRS_Ch24_BellmanFord_Impl.krml _output/CLRS_Ch24_Dijkstra_ImplTest.krml _output/CLRS_Ch24_Dijkstra_Impl.krml _output/CLRS_Ch24_Dijkstra.krml _output/CLRS_Ch24_ShortestPath_Inf.krml _output/CLRS_Ch24_ShortestPath_Spec.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/Ch24_SSSP.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

krml_checked_int_t CLRS_Ch24_ShortestPath_Inf_inf = (krml_checked_int_t)1000000;

krml_checked_int_t CLRS_Ch24_ShortestPath_Spec_inf;

static void
bellman_ford(
  krml_checked_int_t *weights,
  size_t n,
  size_t source,
  krml_checked_int_t *dist,
  bool *result
)
{
  size_t init_i = (size_t)0U;
  size_t vi0 = init_i;
  bool cond = vi0 < n;
  while (cond)
  {
    size_t vi = init_i;
    krml_checked_int_t new_val;
    if (vi == source)
      new_val = (krml_checked_int_t)0;
    else
      new_val = CLRS_Ch24_ShortestPath_Spec_inf;
    dist[vi] = new_val;
    init_i = vi + (size_t)1U;
    size_t vi0 = init_i;
    cond = vi0 < n;
  }
  size_t round = (size_t)1U;
  size_t vround0 = round;
  bool cond0 = vround0 < n;
  while (cond0)
  {
    size_t vround = round;
    size_t u = (size_t)0U;
    size_t vu0 = u;
    bool cond = vu0 < n;
    while (cond)
    {
      size_t vu = u;
      krml_checked_int_t dist_u = dist[vu];
      size_t v = (size_t)0U;
      size_t vv0 = v;
      bool cond0 = vv0 < n;
      while (cond0)
      {
        size_t vv = v;
        size_t w_idx = vu * n + vv;
        krml_checked_int_t w_uv = weights[w_idx];
        krml_checked_int_t old_dist_v = dist[vv];
        bool
        can_relax =
          Prims_op_LessThan(w_uv, CLRS_Ch24_ShortestPath_Spec_inf) &&
            Prims_op_LessThan(dist_u,
              CLRS_Ch24_ShortestPath_Spec_inf);
        krml_checked_int_t sum = Prims_op_Addition(dist_u, w_uv);
        bool should_update = can_relax && Prims_op_LessThan(sum, old_dist_v) && vv != source;
        krml_checked_int_t new_dist_v;
        if (should_update)
          new_dist_v = sum;
        else
          new_dist_v = old_dist_v;
        dist[vv] = new_dist_v;
        v = vv + (size_t)1U;
        size_t vv0 = v;
        cond0 = vv0 < n;
      }
      u = vu + (size_t)1U;
      size_t vu0 = u;
      cond = vu0 < n;
    }
    round = vround + (size_t)1U;
    size_t vround0 = round;
    cond0 = vround0 < n;
  }
  bool no_neg = true;
  size_t cu = (size_t)0U;
  size_t vcu0 = cu;
  bool cond1 = vcu0 < n;
  while (cond1)
  {
    size_t vcu = cu;
    krml_checked_int_t dist_cu = dist[vcu];
    size_t cv = (size_t)0U;
    size_t vcv0 = cv;
    bool cond = vcv0 < n;
    while (cond)
    {
      size_t vcv = cv;
      size_t w_idx = vcu * n + vcv;
      krml_checked_int_t w = weights[w_idx];
      krml_checked_int_t d_u = dist_cu;
      krml_checked_int_t d_v = dist[vcv];
      bool
      edge_ok =
        Prims_op_GreaterThanOrEqual(w, CLRS_Ch24_ShortestPath_Spec_inf) ||
          Prims_op_GreaterThanOrEqual(d_u,
            CLRS_Ch24_ShortestPath_Spec_inf)
        || Prims_op_LessThanOrEqual(d_v, Prims_op_Addition(d_u, w));
      if (!edge_ok)
        no_neg = false;
      cv = vcv + (size_t)1U;
      size_t vcv0 = cv;
      cond = vcv0 < n;
    }
    cu = vcu + (size_t)1U;
    size_t vcu0 = cu;
    cond1 = vcu0 < n;
  }
  bool final_no_neg = no_neg;
  *result = final_no_neg;
}

static size_t
find_min_unvisited(krml_checked_int_t *dist, krml_checked_int_t *visited, size_t n)
{
  size_t min_idx = (size_t)0U;
  krml_checked_int_t
  min_val = Prims_op_Addition(CLRS_Ch24_ShortestPath_Spec_inf, (krml_checked_int_t)1);
  size_t i = (size_t)0U;
  size_t vi0 = i;
  bool cond = vi0 < n;
  while (cond)
  {
    size_t vi = i;
    krml_checked_int_t visited_i = visited[vi];
    if (visited_i == (krml_checked_int_t)0)
    {
      krml_checked_int_t dist_i = dist[vi];
      krml_checked_int_t curr_min = min_val;
      if (Prims_op_LessThan(dist_i, curr_min))
      {
        min_idx = vi;
        min_val = dist_i;
      }
    }
    i = vi + (size_t)1U;
    size_t vi0 = i;
    cond = vi0 < n;
  }
  return min_idx;
}

static void
dijkstra_relax_round(
  krml_checked_int_t *weights,
  size_t n,
  krml_checked_int_t *dist,
  size_t *pred,
  krml_checked_int_t *visited,
  size_t u,
  krml_checked_int_t dist_u
)
{
  size_t v = (size_t)0U;
  size_t vv0 = v;
  bool cond = vv0 < n;
  while (cond)
  {
    size_t vv = v;
    size_t w_idx = u * n + vv;
    krml_checked_int_t w = weights[w_idx];
    krml_checked_int_t visited_v = visited[vv];
    krml_checked_int_t old_dist = dist[vv];
    size_t old_pred = pred[vv];
    bool
    can_relax =
      visited_v == (krml_checked_int_t)0 && Prims_op_LessThan(w, CLRS_Ch24_ShortestPath_Spec_inf) &&
        Prims_op_LessThan(dist_u,
          CLRS_Ch24_ShortestPath_Spec_inf);
    krml_checked_int_t sum = Prims_op_Addition(dist_u, w);
    bool should_update = can_relax && Prims_op_LessThan(sum, old_dist);
    krml_checked_int_t new_dist;
    if (should_update)
      new_dist = sum;
    else
      new_dist = old_dist;
    size_t new_pred;
    if (should_update)
      new_pred = u;
    else
      new_pred = old_pred;
    dist[vv] = new_dist;
    pred[vv] = new_pred;
    v = vv + (size_t)1U;
    size_t vv0 = v;
    cond = vv0 < n;
  }
}

static void
dijkstra(
  krml_checked_int_t *weights,
  size_t n,
  size_t source,
  krml_checked_int_t *dist,
  size_t *pred
)
{
  size_t init_i = (size_t)0U;
  size_t vi0 = init_i;
  bool cond = vi0 < n;
  while (cond)
  {
    size_t vi = init_i;
    krml_checked_int_t new_val;
    if (vi == source)
      new_val = (krml_checked_int_t)0;
    else
      new_val = CLRS_Ch24_ShortestPath_Spec_inf;
    dist[vi] = new_val;
    pred[vi] = vi;
    init_i = vi + (size_t)1U;
    size_t vi0 = init_i;
    cond = vi0 < n;
  }
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), n);
  krml_checked_int_t *visited = KRML_HOST_CALLOC(n, sizeof (krml_checked_int_t));
  size_t round = (size_t)0U;
  size_t vround0 = round;
  bool cond0 = vround0 < n;
  while (cond0)
  {
    size_t vround = round;
    size_t u = find_min_unvisited(dist, visited, n);
    visited[u] = (krml_checked_int_t)1;
    krml_checked_int_t dist_u = dist[u];
    dijkstra_relax_round(weights, n, dist, pred, visited, u, dist_u);
    round = vround + (size_t)1U;
    size_t vround0 = round;
    cond0 = vround0 < n;
  }
  KRML_HOST_FREE(visited);
}

static void
dijkstra0(
  krml_checked_int_t *weights,
  size_t n,
  size_t source,
  krml_checked_int_t *dist,
  size_t *pred
)
{
  dijkstra(weights, n, source, dist, pred);
}

bool CLRS_Ch24_BellmanFord_ImplTest_test_bellman_ford_3(void)
{
  krml_checked_int_t *wv = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *weights = wv;
  weights[0U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[1U] = (krml_checked_int_t)4;
  weights[2U] = (krml_checked_int_t)5;
  weights[3U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[4U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[5U] = (krml_checked_int_t)-2;
  weights[6U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[7U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[8U] = CLRS_Ch24_ShortestPath_Spec_inf;
  krml_checked_int_t *dv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *dist = dv;
  bool result = false;
  bellman_ford(weights, (size_t)3U, (size_t)0U, dist, &result);
  krml_checked_int_t d0 = dist[0U];
  krml_checked_int_t d1 = dist[1U];
  krml_checked_int_t d2 = dist[2U];
  bool nc = result;
  bool
  pass =
    d0 == (krml_checked_int_t)0 && d1 == (krml_checked_int_t)4 && d2 == (krml_checked_int_t)2 && nc;
  KRML_HOST_FREE(wv);
  KRML_HOST_FREE(dv);
  return pass;
}

bool CLRS_Ch24_Dijkstra_ImplTest_test_dijkstra_3(void)
{
  krml_checked_int_t *wv = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *weights = wv;
  weights[0U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[1U] = (krml_checked_int_t)3;
  weights[2U] = (krml_checked_int_t)7;
  weights[3U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[4U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[5U] = (krml_checked_int_t)2;
  weights[6U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[7U] = CLRS_Ch24_ShortestPath_Spec_inf;
  weights[8U] = CLRS_Ch24_ShortestPath_Spec_inf;
  krml_checked_int_t *dv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *dist = dv;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *pv = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *pred = pv;
  dijkstra0(weights, (size_t)3U, (size_t)0U, dist, pred);
  krml_checked_int_t d0 = dist[0U];
  krml_checked_int_t d1 = dist[1U];
  krml_checked_int_t d2 = dist[2U];
  bool
  pass =
    d0 == (krml_checked_int_t)0 && d1 == (krml_checked_int_t)3 && d2 == (krml_checked_int_t)5;
  KRML_HOST_FREE(wv);
  KRML_HOST_FREE(dv);
  KRML_HOST_FREE(pv);
  return pass;
}

