/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch24.BellmanFord.ImplTest+CLRS.Ch24.Dijkstra.ImplTest=CLRS.Ch24.*[rename=Ch24_SSSP] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch24_BellmanFord_ImplTest.krml _output/CLRS_Ch24_BellmanFord_Impl.krml _output/CLRS_Ch24_Dijkstra_ImplTest.krml _output/CLRS_Ch24_Dijkstra_Impl.krml _output/CLRS_Ch24_Dijkstra.krml _output/CLRS_Ch24_ShortestPath_Inf.krml _output/CLRS_Ch24_ShortestPath_Spec.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef krmlinit_H
#define krmlinit_H

#include "krmllib.h"

#include "krml/internal/compat.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void);


#define krmlinit_H_DEFINED
#endif /* krmlinit_H */
