/* !!  HANDWRITTEN  -- not generated by F* or KaRaMeL  !! */
/* Test driver for verified SSSP algorithms (Ch24).        */

/*
  Test driver for verified SSSP algorithms (Ch24).
  Calls extracted, proof-carrying test functions from ImplTest modules.
  All test logic is verified Pulse code; this file only dispatches.
*/

#include <stdio.h>
#include "Ch24_SSSP.h"
#include "krmlinit.h"

int main(void) {
    krmlinit_globals();

    printf("=== CLRS Ch24 SSSP — Extracted tests ===\n\n");

    printf("--- Bellman-Ford test (3-vertex graph) ---\n");
    if (!CLRS_Ch24_BellmanFord_ImplTest_test_bellman_ford_3()) {
        fprintf(stderr, "FAIL: Bellman-Ford output mismatch\n");
        return 1;
    }
    printf("  PASS\n\n");

    printf("--- Dijkstra test (3-vertex graph) ---\n");
    if (!CLRS_Ch24_Dijkstra_ImplTest_test_dijkstra_3()) {
        fprintf(stderr, "FAIL: Dijkstra output mismatch\n");
        return 1;
    }
    printf("  PASS\n\n");

    printf("=== All ch24 tests passed ===\n");
    return 0;
}
