/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17-18 -add-include "krml/internal/compat.h" -bundle CLRS.Ch16.ActivitySelection.ImplTest=CLRS.Ch16.ActivitySelection.* -bundle CLRS.Ch16.Huffman.ImplTest=CLRS.Ch16.Huffman.*,Pulse.Lib.PriorityQueue,Pulse.Lib.ResizableVec,Pulse.Lib.TotalOrder,Pulse.Lib.Vec,Pulse.Lib.Box -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/c_extract _output/CLRS_Ch16_ActivitySelection_ImplTest.krml _output/CLRS_Ch16_ActivitySelection_Impl.krml _output/CLRS_Ch16_Huffman_ImplTest.krml _output/CLRS_Ch16_Huffman_Impl.krml _output/CLRS_Ch16_Huffman_Defs.krml _output/CLRS_Ch16_Huffman_PQForest.krml _output/Pulse_Lib_PriorityQueue.krml _output/Pulse_Lib_ResizableVec.krml _output/Pulse_Lib_TotalOrder.krml _output/Pulse_Lib_Vec.krml _output/Pulse_Lib_Box.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/CLRS_Ch16_Huffman_ImplTest.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

static FStar_Order_order
pq_entry_compare(CLRS_Ch16_Huffman_Defs_pq_entry x, CLRS_Ch16_Huffman_Defs_pq_entry y)
{
  krml_checked_int_t fx = x.fst;
  size_t ix = x.snd;
  krml_checked_int_t fy = y.fst;
  size_t iy = y.snd;
  if (Prims_op_LessThan(fx, fy))
    return FStar_Order_Lt;
  else if (Prims_op_GreaterThan(fx, fy))
    return FStar_Order_Gt;
  else if (Prims_op_LessThan(FStar_SizeT_v(ix), FStar_SizeT_v(iy)))
    return FStar_Order_Lt;
  else if (Prims_op_GreaterThan(FStar_SizeT_v(ix), FStar_SizeT_v(iy)))
    return FStar_Order_Gt;
  else
    return FStar_Order_Eq;
}

static FStar_Order_order
(*pq_entry_total_order)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1) =
  pq_entry_compare;

static CLRS_Ch16_Huffman_Defs_hnode *alloc_hnode(CLRS_Ch16_Huffman_Defs_hnode h)
{
  CLRS_Ch16_Huffman_Defs_hnode *buf = KRML_HOST_MALLOC(sizeof (CLRS_Ch16_Huffman_Defs_hnode));
  if (buf != NULL)
    buf[0U] = h;
  return buf;
}

static Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_
create___krml_checked_int_t___size_t_(size_t capacity)
{
  KRML_CHECK_SIZE(sizeof (FStar_Pervasives_Native_option___krml_checked_int_t___size_t_),
    capacity);
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_
  *vec =
    KRML_HOST_MALLOC(sizeof (FStar_Pervasives_Native_option___krml_checked_int_t___size_t_) *
        capacity);
  if (vec != NULL)
    for (uint32_t _i = 0U; _i < capacity; ++_i)
      vec[_i] =
        (
          (FStar_Pervasives_Native_option___krml_checked_int_t___size_t_){
            .tag = FStar_Pervasives_Native_None
          }
        );
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_
  **vec_box =
    KRML_HOST_MALLOC(sizeof (FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ *));
  if (vec_box != NULL)
    vec_box[0U] = vec;
  size_t *size_box = KRML_HOST_CALLOC(1U, sizeof (size_t));
  size_t cap = capacity;
  size_t *cap_box = KRML_HOST_MALLOC(sizeof (size_t));
  if (cap_box != NULL)
    cap_box[0U] = cap;
  return
    (
      (Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_){
        .vec_box = vec_box,
        .size_box = size_box,
        .cap_box = cap_box
      }
    );
}

static Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_
create___krml_checked_int_t___size_t_0(size_t capacity)
{
  return create___krml_checked_int_t___size_t_(capacity);
}

static void
push___krml_checked_int_t___size_t_(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ v,
  CLRS_Ch16_Huffman_Defs_pq_entry x
)
{
  size_t current_sz = *v.size_box;
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ *current_vec = *v.vec_box;
  current_vec[current_sz] =
    (
      (FStar_Pervasives_Native_option___krml_checked_int_t___size_t_){
        .tag = FStar_Pervasives_Native_Some,
        .v = x
      }
    );
  *v.size_box = current_sz + (size_t)1U;
}

static size_t
len___krml_checked_int_t___size_t_(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ v
)
{
  return *v.size_box;
}

static CLRS_Ch16_Huffman_Defs_pq_entry
get___krml_checked_int_t___size_t_(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ v,
  size_t i
)
{
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ *current_vec = *v.vec_box;
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ opt_x = current_vec[i];
  if (opt_x.tag == FStar_Pervasives_Native_Some)
    return opt_x.v;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static bool
op_Less_Question___krml_checked_int_t___size_t_(
  FStar_Order_order (*o)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  CLRS_Ch16_Huffman_Defs_pq_entry x,
  CLRS_Ch16_Huffman_Defs_pq_entry y
)
{
  return FStar_Order_lt(o(x, y));
}

static void
set___krml_checked_int_t___size_t_(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ v,
  size_t i,
  CLRS_Ch16_Huffman_Defs_pq_entry x
)
{
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ *current_vec = *v.vec_box;
  current_vec[i] =
    (
      (FStar_Pervasives_Native_option___krml_checked_int_t___size_t_){
        .tag = FStar_Pervasives_Native_Some,
        .v = x
      }
    );
}

static void
swap___krml_checked_int_t___size_t_(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq,
  size_t i,
  size_t j
)
{
  CLRS_Ch16_Huffman_Defs_pq_entry vi = get___krml_checked_int_t___size_t_(pq, i);
  CLRS_Ch16_Huffman_Defs_pq_entry vj = get___krml_checked_int_t___size_t_(pq, j);
  set___krml_checked_int_t___size_t_(pq, i, vj);
  set___krml_checked_int_t___size_t_(pq, j, vi);
}

void
Pulse_Lib_PriorityQueue_sift_up___krml_checked_int_t___size_t_(
  FStar_Order_order
  (*uu___)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq,
  size_t idx
)
{
  if (!(idx == (size_t)0U))
  {
    size_t parent = (idx - (size_t)1U) / (size_t)2U;
    CLRS_Ch16_Huffman_Defs_pq_entry current_val = get___krml_checked_int_t___size_t_(pq, idx);
    CLRS_Ch16_Huffman_Defs_pq_entry parent_val = get___krml_checked_int_t___size_t_(pq, parent);
    if (op_Less_Question___krml_checked_int_t___size_t_(uu___, current_val, parent_val))
    {
      swap___krml_checked_int_t___size_t_(pq, idx, parent);
      Pulse_Lib_PriorityQueue_sift_up___krml_checked_int_t___size_t_(uu___, pq, parent);
    }
  }
}

static void
insert___krml_checked_int_t___size_t_(
  FStar_Order_order
  (*uu___)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq,
  CLRS_Ch16_Huffman_Defs_pq_entry x
)
{
  push___krml_checked_int_t___size_t_(pq, x);
  size_t new_len = len___krml_checked_int_t___size_t_(pq);
  size_t last_idx = new_len - (size_t)1U;
  Pulse_Lib_PriorityQueue_sift_up___krml_checked_int_t___size_t_(uu___, pq, last_idx);
}

static CLRS_Ch16_Huffman_Defs_pq_entry
pop___krml_checked_int_t___size_t_(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ v
)
{
  size_t current_sz = *v.size_box;
  size_t last_idx = current_sz - (size_t)1U;
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ *current_vec = *v.vec_box;
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ opt_x = current_vec[last_idx];
  CLRS_Ch16_Huffman_Defs_pq_entry x;
  if (opt_x.tag == FStar_Pervasives_Native_Some)
    x = opt_x.v;
  else
    x =
      KRML_EABORT(CLRS_Ch16_Huffman_Defs_pq_entry,
        "unreachable (pattern matches are exhaustive in F*)");
  *v.size_box = last_idx;
  return x;
}

static bool
op_Less_Equals_Question___krml_checked_int_t___size_t_(
  FStar_Order_order (*o)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  CLRS_Ch16_Huffman_Defs_pq_entry x,
  CLRS_Ch16_Huffman_Defs_pq_entry y
)
{
  return FStar_Order_le(o(x, y));
}

void
Pulse_Lib_PriorityQueue_sift_down___krml_checked_int_t___size_t_(
  FStar_Order_order
  (*uu___)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq,
  size_t idx,
  size_t len
)
{
  size_t left = (size_t)2U * idx + (size_t)1U;
  if (!(left >= len))
  {
    size_t right = (size_t)2U * idx + (size_t)2U;
    CLRS_Ch16_Huffman_Defs_pq_entry current_val = get___krml_checked_int_t___size_t_(pq, idx);
    CLRS_Ch16_Huffman_Defs_pq_entry left_val = get___krml_checked_int_t___size_t_(pq, left);
    if (right < len)
    {
      CLRS_Ch16_Huffman_Defs_pq_entry right_val = get___krml_checked_int_t___size_t_(pq, right);
      if (op_Less_Equals_Question___krml_checked_int_t___size_t_(uu___, left_val, right_val))
      {
        if (op_Less_Question___krml_checked_int_t___size_t_(uu___, left_val, current_val))
        {
          swap___krml_checked_int_t___size_t_(pq, idx, left);
          Pulse_Lib_PriorityQueue_sift_down___krml_checked_int_t___size_t_(uu___, pq, left, len);
        }
      }
      else if (op_Less_Question___krml_checked_int_t___size_t_(uu___, right_val, current_val))
      {
        swap___krml_checked_int_t___size_t_(pq, idx, right);
        Pulse_Lib_PriorityQueue_sift_down___krml_checked_int_t___size_t_(uu___, pq, right, len);
      }
    }
    else if (op_Less_Question___krml_checked_int_t___size_t_(uu___, left_val, current_val))
    {
      swap___krml_checked_int_t___size_t_(pq, idx, left);
      Pulse_Lib_PriorityQueue_sift_down___krml_checked_int_t___size_t_(uu___, pq, left, len);
    }
  }
}

static CLRS_Ch16_Huffman_Defs_pq_entry
extract_min___krml_checked_int_t___size_t_(
  FStar_Order_order
  (*uu___)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq
)
{
  CLRS_Ch16_Huffman_Defs_pq_entry min_val = get___krml_checked_int_t___size_t_(pq, (size_t)0U);
  size_t len = len___krml_checked_int_t___size_t_(pq);
  if (len == (size_t)1U)
  {
    pop___krml_checked_int_t___size_t_(pq);
    return min_val;
  }
  else
  {
    size_t last_idx = len - (size_t)1U;
    CLRS_Ch16_Huffman_Defs_pq_entry last_val = get___krml_checked_int_t___size_t_(pq, last_idx);
    set___krml_checked_int_t___size_t_(pq, (size_t)0U, last_val);
    pop___krml_checked_int_t___size_t_(pq);
    size_t new_len = len___krml_checked_int_t___size_t_(pq);
    Pulse_Lib_PriorityQueue_sift_down___krml_checked_int_t___size_t_(uu___,
      pq,
      (size_t)0U,
      new_len);
    return min_val;
  }
}

static void
free___krml_checked_int_t___size_t_(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ v
)
{
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ *current_vec = *v.vec_box;
  KRML_HOST_FREE(current_vec);
  KRML_HOST_FREE(v.vec_box);
  KRML_HOST_FREE(v.size_box);
  KRML_HOST_FREE(v.cap_box);
}

static void
free___krml_checked_int_t___size_t_0(
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq
)
{
  free___krml_checked_int_t___size_t_(pq);
}

static CLRS_Ch16_Huffman_Defs_hnode *huffman_tree(krml_checked_int_t *freqs, size_t n)
{
  CLRS_Ch16_Huffman_Defs_hnode
  *dummy =
    alloc_hnode((
        (CLRS_Ch16_Huffman_Defs_hnode){
          .sym = (krml_checked_int_t)0,
          .freq = (krml_checked_int_t)0,
          .left = { .tag = FStar_Pervasives_Native_None },
          .right = { .tag = FStar_Pervasives_Native_None }
        }
      ));
  KRML_CHECK_SIZE(sizeof (CLRS_Ch16_Huffman_Defs_hnode *), n);
  CLRS_Ch16_Huffman_Defs_hnode
  **nodes = KRML_HOST_MALLOC(sizeof (CLRS_Ch16_Huffman_Defs_hnode *) * n);
  if (nodes != NULL)
    for (uint32_t _i = 0U; _i < n; ++_i)
      nodes[_i] = dummy;
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_
  pq = create___krml_checked_int_t___size_t_0(n);
  size_t i = (size_t)0U;
  size_t __anf00 = i;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t vi = i;
    krml_checked_int_t freq_val = freqs[vi];
    CLRS_Ch16_Huffman_Defs_hnode
    *leaf =
      alloc_hnode((
          (CLRS_Ch16_Huffman_Defs_hnode){
            .sym = FStar_SizeT_v(vi),
            .freq = freq_val,
            .left = { .tag = FStar_Pervasives_Native_None },
            .right = { .tag = FStar_Pervasives_Native_None }
          }
        ));
    nodes[vi] = leaf;
    insert___krml_checked_int_t___size_t_(pq_entry_total_order,
      pq,
      ((CLRS_Ch16_Huffman_Defs_pq_entry){ .fst = freq_val, .snd = vi }));
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
  size_t iter = (size_t)0U;
  size_t n_minus_1 = n - (size_t)1U;
  size_t __anf0 = iter;
  bool cond0 = __anf0 < n_minus_1;
  while (cond0)
  {
    CLRS_Ch16_Huffman_Defs_pq_entry
    _letpattern = extract_min___krml_checked_int_t___size_t_(pq_entry_total_order, pq);
    krml_checked_int_t freq1 = _letpattern.fst;
    size_t idx1 = _letpattern.snd;
    CLRS_Ch16_Huffman_Defs_pq_entry
    _letpattern1 = extract_min___krml_checked_int_t___size_t_(pq_entry_total_order, pq);
    krml_checked_int_t freq2 = _letpattern1.fst;
    size_t idx2 = _letpattern1.snd;
    krml_checked_int_t sum_freq = Prims_op_Addition(freq1, freq2);
    CLRS_Ch16_Huffman_Defs_hnode *left_ptr = nodes[idx1];
    CLRS_Ch16_Huffman_Defs_hnode *right_ptr = nodes[idx2];
    CLRS_Ch16_Huffman_Defs_hnode
    *merged =
      alloc_hnode((
          (CLRS_Ch16_Huffman_Defs_hnode){
            .sym = (krml_checked_int_t)0,
            .freq = sum_freq,
            .left = { .tag = FStar_Pervasives_Native_Some, .v = left_ptr },
            .right = { .tag = FStar_Pervasives_Native_Some, .v = right_ptr }
          }
        ));
    nodes[idx1] = merged;
    insert___krml_checked_int_t___size_t_(pq_entry_total_order,
      pq,
      ((CLRS_Ch16_Huffman_Defs_pq_entry){ .fst = sum_freq, .snd = idx1 }));
    size_t viter = iter;
    iter = viter + (size_t)1U;
    size_t __anf0 = iter;
    cond0 = __anf0 < n_minus_1;
  }
  CLRS_Ch16_Huffman_Defs_pq_entry
  _letpattern = extract_min___krml_checked_int_t___size_t_(pq_entry_total_order, pq);
  size_t result_idx = _letpattern.snd;
  CLRS_Ch16_Huffman_Defs_hnode *result = nodes[result_idx];
  free___krml_checked_int_t___size_t_0(pq);
  KRML_HOST_FREE(dummy);
  KRML_HOST_FREE(nodes);
  return result;
}

bool CLRS_Ch16_Huffman_ImplTest_test_huffman_2(void)
{
  krml_checked_int_t *fv = KRML_HOST_CALLOC((size_t)2U, sizeof (krml_checked_int_t));
  krml_checked_int_t *freqs = fv;
  freqs[0U] = (krml_checked_int_t)3;
  freqs[1U] = (krml_checked_int_t)5;
  CLRS_Ch16_Huffman_Defs_hnode *tree_ptr = huffman_tree(freqs, (size_t)2U);
  KRML_MAYBE_UNUSED_VAR(tree_ptr);
  krml_checked_int_t f0 = freqs[0U];
  krml_checked_int_t f1 = freqs[1U];
  bool pass = f0 == (krml_checked_int_t)3 && f1 == (krml_checked_int_t)5;
  KRML_HOST_FREE(fv);
  return pass;
}

