/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17-18 -add-include "krml/internal/compat.h" -bundle CLRS.Ch16.ActivitySelection.ImplTest=CLRS.Ch16.ActivitySelection.* -bundle CLRS.Ch16.Huffman.ImplTest=CLRS.Ch16.Huffman.*,Pulse.Lib.PriorityQueue,Pulse.Lib.ResizableVec,Pulse.Lib.TotalOrder,Pulse.Lib.Vec,Pulse.Lib.Box -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/c_extract _output/CLRS_Ch16_ActivitySelection_ImplTest.krml _output/CLRS_Ch16_ActivitySelection_Impl.krml _output/CLRS_Ch16_Huffman_ImplTest.krml _output/CLRS_Ch16_Huffman_Impl.krml _output/CLRS_Ch16_Huffman_Defs.krml _output/CLRS_Ch16_Huffman_PQForest.krml _output/Pulse_Lib_PriorityQueue.krml _output/Pulse_Lib_ResizableVec.krml _output/Pulse_Lib_TotalOrder.krml _output/Pulse_Lib_Vec.krml _output/Pulse_Lib_Box.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch16_Huffman_ImplTest_H
#define CLRS_Ch16_Huffman_ImplTest_H

#include "krmllib.h"

#include "krml/internal/compat.h"
#include "fstar_support.h"

bool CLRS_Ch16_Huffman_ImplTest_test_huffman_2(void);


#define CLRS_Ch16_Huffman_ImplTest_H_DEFINED
#endif /* CLRS_Ch16_Huffman_ImplTest_H */
