/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17-18 -add-include "krml/internal/compat.h" -bundle CLRS.Ch16.ActivitySelection.ImplTest=CLRS.Ch16.ActivitySelection.* -bundle CLRS.Ch16.Huffman.ImplTest=CLRS.Ch16.Huffman.*,Pulse.Lib.PriorityQueue,Pulse.Lib.ResizableVec,Pulse.Lib.TotalOrder,Pulse.Lib.Vec,Pulse.Lib.Box -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/c_extract _output/CLRS_Ch16_ActivitySelection_ImplTest.krml _output/CLRS_Ch16_ActivitySelection_Impl.krml _output/CLRS_Ch16_Huffman_ImplTest.krml _output/CLRS_Ch16_Huffman_Impl.krml _output/CLRS_Ch16_Huffman_Defs.krml _output/CLRS_Ch16_Huffman_PQForest.krml _output/Pulse_Lib_PriorityQueue.krml _output/Pulse_Lib_ResizableVec.krml _output/Pulse_Lib_TotalOrder.krml _output/Pulse_Lib_Vec.krml _output/Pulse_Lib_Box.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch16_ActivitySelection_ImplTest.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

static size_t
activity_selection(
  krml_checked_int_t *start_times,
  krml_checked_int_t *finish_times,
  size_t *out,
  size_t n
)
{
  if ((size_t)0U < n)
  {
    out[0U] = (size_t)0U;
    size_t count = (size_t)1U;
    krml_checked_int_t first_finish = finish_times[0U];
    krml_checked_int_t last_finish = first_finish;
    size_t i = (size_t)1U;
    size_t __anf0 = i;
    bool cond = __anf0 < n;
    while (cond)
    {
      size_t vi = i;
      krml_checked_int_t curr_start = start_times[vi];
      krml_checked_int_t curr_finish = finish_times[vi];
      krml_checked_int_t vlast_finish = last_finish;
      size_t vcount = count;
      bool selected = Prims_op_GreaterThanOrEqual(curr_start, vlast_finish);
      if (selected)
      {
        out[vcount] = vi;
        count = vcount + (size_t)1U;
        last_finish = curr_finish;
        i = vi + (size_t)1U;
      }
      else
        i = vi + (size_t)1U;
      size_t __anf0 = i;
      cond = __anf0 < n;
    }
    return count;
  }
  else
    return (size_t)0U;
}

bool CLRS_Ch16_ActivitySelection_ImplTest_sz_eq(size_t a, size_t b)
{
  return !(a < b || b < a);
}

bool CLRS_Ch16_ActivitySelection_ImplTest_test_activity_selection_3(void)
{
  krml_checked_int_t *sv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *start_arr = sv;
  start_arr[0U] = (krml_checked_int_t)1;
  start_arr[1U] = (krml_checked_int_t)3;
  start_arr[2U] = (krml_checked_int_t)5;
  krml_checked_int_t *fv = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *finish_arr = fv;
  finish_arr[0U] = (krml_checked_int_t)4;
  finish_arr[1U] = (krml_checked_int_t)5;
  finish_arr[2U] = (krml_checked_int_t)7;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *ov = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *out_arr = ov;
  size_t count = activity_selection(start_arr, finish_arr, out_arr, (size_t)3U);
  size_t v0 = out_arr[0U];
  size_t v1 = out_arr[1U];
  bool
  pass =
    !(v0 < (size_t)0U || (size_t)0U < v0) && !(v1 < (size_t)2U || (size_t)2U < v1) &&
      !(count < (size_t)2U || (size_t)2U < count);
  KRML_HOST_FREE(ov);
  KRML_HOST_FREE(fv);
  KRML_HOST_FREE(sv);
  return pass;
}

