# Standalone Makefile for Ch16 Greedy Algorithms — C snapshot
#
# This directory contains a self-contained C snapshot of the verified
# CLRS Ch16 implementations (Activity Selection + Huffman coding).
#
# All *.c and *.h files (except main.c, fstar_support.c, fstar_support.h)
# were generated by F* + KaRaMeL from machine-checked Pulse proofs.
# The handwritten files are marked with a HANDWRITTEN banner.
#
# Usage:
#   make          # build and run the tests
#   make build    # build only
#   make run      # run the test executable
#   make clean    # remove build artifacts

CC       ?= cc
CFLAGS    = -std=c11 -Wall -g -fwrapv \
            -D_BSD_SOURCE -D_DEFAULT_SOURCE \
            -Wno-unused-variable -Wno-unused-parameter \
            -Wno-parentheses -Wno-unused-but-set-variable
INCLUDES  = -I .

EXE = ch16_test

# All C source files in this snapshot
SRCS = main.c \
       fstar_support.c \
       prims.c \
       CLRS_Ch16_ActivitySelection_ImplTest.c \
       CLRS_Ch16_Huffman_ImplTest.c \
       FStar_Pulse_PulseCore_Prims.c

.PHONY: all build run clean

all: run

build: $(EXE)

$(EXE): $(SRCS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $(SRCS)

run: $(EXE)
	./$(EXE)

clean:
	rm -f $(EXE)
