/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch06.Heap.ImplTest=CLRS.Ch06.Heap.*,Pulse.Lib.BoundedIntegers -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch06_Heap_Impl.krml _output/CLRS_Ch06_Heap_ImplTest.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch06_Heap_ImplTest_H
#define CLRS_Ch06_Heap_ImplTest_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch06_Heap_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b);

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_3(void);

bool CLRS_Ch06_Heap_ImplTest_test_build_max_heap_3(void);

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_0(void);

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_prefix(void);

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_duplicates(void);


#define CLRS_Ch06_Heap_ImplTest_H_DEFINED
#endif /* CLRS_Ch06_Heap_ImplTest_H */
