/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch06.Heap.ImplTest=CLRS.Ch06.Heap.*,Pulse.Lib.BoundedIntegers -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch06_Heap_Impl.krml _output/CLRS_Ch06_Heap_ImplTest.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/CLRS_Ch06_Heap_ImplTest.h"

Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_int;

void CLRS_Ch06_Heap_Impl_max_heapify(krml_checked_int_t *a, size_t idx, size_t heap_size)
{
  size_t left = (size_t)2U * idx + (size_t)1U;
  if (!(left >= heap_size))
  {
    size_t right = (size_t)2U * idx + (size_t)2U;
    krml_checked_int_t cur = a[idx];
    krml_checked_int_t lv = a[left];
    if (right < heap_size)
    {
      krml_checked_int_t rv = a[right];
      bool
      (*op_Greater_Equals)(krml_checked_int_t x0, krml_checked_int_t x1) =
        Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater_Equals;
      if (op_Greater_Equals(lv, rv))
      {
        bool
        (*op_Greater)(krml_checked_int_t x0, krml_checked_int_t x1) =
          Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater;
        if (op_Greater(lv, cur))
        {
          krml_checked_int_t vi = a[idx];
          krml_checked_int_t vl = a[left];
          a[idx] = vl;
          a[left] = vi;
          CLRS_Ch06_Heap_Impl_max_heapify(a, left, heap_size);
        }
      }
      else
      {
        bool
        (*op_Greater)(krml_checked_int_t x0, krml_checked_int_t x1) =
          Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater;
        if (op_Greater(rv, cur))
        {
          krml_checked_int_t vi = a[idx];
          krml_checked_int_t vr = a[right];
          a[idx] = vr;
          a[right] = vi;
          CLRS_Ch06_Heap_Impl_max_heapify(a, right, heap_size);
        }
      }
    }
    else
    {
      bool
      (*op_Greater)(krml_checked_int_t x0, krml_checked_int_t x1) =
        Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater;
      if (op_Greater(lv, cur))
      {
        krml_checked_int_t vi = a[idx];
        krml_checked_int_t vl = a[left];
        a[idx] = vl;
        a[left] = vi;
        CLRS_Ch06_Heap_Impl_max_heapify(a, left, heap_size);
      }
    }
  }
}

static void build_max_heap(krml_checked_int_t *a, size_t n)
{
  size_t half = n / (size_t)2U;
  size_t i = half;
  size_t __anf0 = i;
  bool cond = __anf0 > (size_t)0U;
  while (cond)
  {
    size_t vi = i;
    size_t idx = vi - (size_t)1U;
    i = idx;
    CLRS_Ch06_Heap_Impl_max_heapify(a, idx, n);
    size_t __anf0 = i;
    cond = __anf0 > (size_t)0U;
  }
}

static void heapsort(krml_checked_int_t *a, size_t n)
{
  if (!(n == (size_t)0U))
  {
    build_max_heap(a, n);
    size_t heap_sz = n;
    size_t __anf0 = heap_sz;
    bool cond = __anf0 > (size_t)1U;
    while (cond)
    {
      size_t vsz = heap_sz;
      size_t last = vsz - (size_t)1U;
      krml_checked_int_t v0 = a[0U];
      krml_checked_int_t vl = a[last];
      a[0U] = vl;
      a[last] = v0;
      size_t new_sz = vsz - (size_t)1U;
      CLRS_Ch06_Heap_Impl_max_heapify(a, (size_t)0U, new_sz);
      heap_sz = new_sz;
      size_t __anf0 = heap_sz;
      cond = __anf0 > (size_t)1U;
    }
  }
}

bool CLRS_Ch06_Heap_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b)
{
  return a == b;
}

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_3(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  heapsort(arr, (size_t)3U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  KRML_HOST_FREE(v);
  return
    v0 == (krml_checked_int_t)1 && v1 == (krml_checked_int_t)2 && v2 == (krml_checked_int_t)3;
}

bool CLRS_Ch06_Heap_ImplTest_test_build_max_heap_3(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  build_max_heap(arr, (size_t)3U);
  krml_checked_int_t v0 = arr[0U];
  KRML_HOST_FREE(v);
  return v0 == (krml_checked_int_t)3;
}

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_0(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)5;
  arr[1U] = (krml_checked_int_t)3;
  arr[2U] = (krml_checked_int_t)7;
  heapsort(arr, (size_t)0U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  KRML_HOST_FREE(v);
  return
    v0 == (krml_checked_int_t)5 && v1 == (krml_checked_int_t)3 && v2 == (krml_checked_int_t)7;
}

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_prefix(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)7;
  arr[1U] = (krml_checked_int_t)5;
  arr[2U] = (krml_checked_int_t)3;
  heapsort(arr, (size_t)2U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  KRML_HOST_FREE(v);
  return
    v0 == (krml_checked_int_t)5 && v1 == (krml_checked_int_t)7 && v2 == (krml_checked_int_t)3;
}

bool CLRS_Ch06_Heap_ImplTest_test_heapsort_duplicates(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)2;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  heapsort(arr, (size_t)3U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  KRML_HOST_FREE(v);
  return
    v0 == (krml_checked_int_t)1 && v1 == (krml_checked_int_t)2 && v2 == (krml_checked_int_t)2;
}

