/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch06.Heap.ImplTest=CLRS.Ch06.Heap.*,Pulse.Lib.BoundedIntegers -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch06_Heap_Impl.krml _output/CLRS_Ch06_Heap_ImplTest.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "krmlinit.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"
#include "internal/CLRS_Ch06_Heap_ImplTest.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void)
{
  Pulse_Lib_BoundedIntegers_bounded_int_int =
    (
      (Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t){
        .op_Plus = (void *)0U,
        .op_Subtraction = (void *)0U,
        .op_Less = (void *)0U,
        .op_Less_Equals = (void *)0U,
        .op_Greater = (void *)0U,
        .op_Greater_Equals = (void *)0U,
        .op_Percent = (void *)0U,
        .op_Slash = (void *)0U
      }
    );
}

