/*
 * !! HANDWRITTEN — NOT GENERATED !!
 *
 * This file is handwritten (not generated by F* / KaRaMeL).
 * All other .c/.h files in this directory are machine-generated.
 */
/*
 * main.c — Test driver for CLRS Ch06 Heapsort extracted from Pulse/F*
 *
 * Provides:
 *   - krmlinit_globals to wire up the BoundedIntegers typeclass dict
 *     (using Prims_op_* from krmllib's prims.c)
 *   - main() entry point calling all 5 test functions and checking results
 *
 * Prims integer operations are provided by $(KRML_HOME)/krmllib/dist/generic/prims.c
 * via EXTRA_C_SOURCES in the Makefile (no hand-written implementations needed).
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include "krml/internal/compat.h"
#include "CLRS_Ch06_Heap_ImplTest.h"
#include "internal/CLRS_Ch06_Heap_ImplTest.h"

/* Prims_op_* declarations — implementations from krmllib/dist/generic/prims.c */
extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);
extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);
extern krml_checked_int_t Prims_op_Modulus(krml_checked_int_t x, krml_checked_int_t y);
extern krml_checked_int_t Prims_op_Division(krml_checked_int_t x, krml_checked_int_t y);
extern bool Prims_op_LessThan(krml_checked_int_t x, krml_checked_int_t y);
extern bool Prims_op_LessThanOrEqual(krml_checked_int_t x, krml_checked_int_t y);
extern bool Prims_op_GreaterThan(krml_checked_int_t x, krml_checked_int_t y);
extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x, krml_checked_int_t y);

/* Initialize the BoundedIntegers typeclass dict with Prims_op_* from krmllib */
void krmlinit_globals(void) {
  Pulse_Lib_BoundedIntegers_bounded_int_int =
    (Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t){
      .op_Plus             = Prims_op_Addition,
      .op_Subtraction      = Prims_op_Subtraction,
      .op_Less             = Prims_op_LessThan,
      .op_Less_Equals      = Prims_op_LessThanOrEqual,
      .op_Greater          = Prims_op_GreaterThan,
      .op_Greater_Equals   = Prims_op_GreaterThanOrEqual,
      .op_Percent          = Prims_op_Modulus,
      .op_Slash            = Prims_op_Division
    };
}

int main(void) {
  krmlinit_globals();

  int failures = 0;

  printf("CLRS Ch06 Heapsort — Concrete Execution Tests\n");
  printf("==============================================\n");

  printf("Test 1: heapsort [3,1,2] -> [1,2,3] ... ");
  if (CLRS_Ch06_Heap_ImplTest_test_heapsort_3()) {
    printf("PASS\n");
  } else {
    printf("FAIL\n");
    failures++;
  }

  printf("Test 2: build_max_heap [3,1,2] root=3 ... ");
  if (CLRS_Ch06_Heap_ImplTest_test_build_max_heap_3()) {
    printf("PASS\n");
  } else {
    printf("FAIL\n");
    failures++;
  }

  printf("Test 3: heapsort n=0 [5,3,7] unchanged ... ");
  if (CLRS_Ch06_Heap_ImplTest_test_heapsort_0()) {
    printf("PASS\n");
  } else {
    printf("FAIL\n");
    failures++;
  }

  printf("Test 4: heapsort prefix n=2 [7,5,3] -> [5,7,3] ... ");
  if (CLRS_Ch06_Heap_ImplTest_test_heapsort_prefix()) {
    printf("PASS\n");
  } else {
    printf("FAIL\n");
    failures++;
  }

  printf("Test 5: heapsort duplicates [2,1,2] -> [1,2,2] ... ");
  if (CLRS_Ch06_Heap_ImplTest_test_heapsort_duplicates()) {
    printf("PASS\n");
  } else {
    printf("FAIL\n");
    failures++;
  }

  printf("==============================================\n");
  if (failures == 0) {
    printf("All 5 tests passed.\n");
    return 0;
  } else {
    printf("%d test(s) FAILED.\n", failures);
    return 1;
  }
}
