/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15 -add-include "krml/internal/compat.h" -bundle CLRS.Ch11.HashTable.ImplTest=CLRS.Ch11.HashTable.Impl[rename=CLRS_Ch11_HashTable_ImplTest] -bundle FStar.*,Pulse.*,Prims,PulseCore.*,LowStar.* -add-include "fstar_support.h" -tmpdir _output _output/CLRS_Ch11_HashTable_Impl.krml _output/CLRS_Ch11_HashTable_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch11_HashTable_ImplTest_H
#define CLRS_Ch11_HashTable_ImplTest_H

#include "krmllib.h"

#include "krml/internal/compat.h"
#include "fstar_support.h"

bool CLRS_Ch11_HashTable_ImplTest_test_search_empty(void);

bool CLRS_Ch11_HashTable_ImplTest_test_insert_then_search(void);

bool CLRS_Ch11_HashTable_ImplTest_test_insert_search_absent(void);

bool CLRS_Ch11_HashTable_ImplTest_test_delete_then_search(void);

bool CLRS_Ch11_HashTable_ImplTest_test_insert_no_dup_existing(void);

bool CLRS_Ch11_HashTable_ImplTest_test_insert_no_dup_fresh(void);

bool CLRS_Ch11_HashTable_ImplTest_test_create_free(void);


#define CLRS_Ch11_HashTable_ImplTest_H_DEFINED
#endif /* CLRS_Ch11_HashTable_ImplTest_H */
