/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15 -add-include "krml/internal/compat.h" -bundle CLRS.Ch11.HashTable.ImplTest=CLRS.Ch11.HashTable.Impl[rename=CLRS_Ch11_HashTable_ImplTest] -bundle FStar.*,Pulse.*,Prims,PulseCore.*,LowStar.* -add-include "fstar_support.h" -tmpdir _output _output/CLRS_Ch11_HashTable_Impl.krml _output/CLRS_Ch11_HashTable_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch11_HashTable_ImplTest.h"

#include "internal/FStar_Pulse_Prims_PulseCore_LowStar.h"

static size_t hash(krml_checked_int_t k, size_t size)
{
  return FStar_SizeT_uint_to_t(k) % size;
}

static size_t hash_probe(krml_checked_int_t k, size_t i, size_t size)
{
  size_t h = hash(k, size);
  krml_checked_int_t sum = Prims_op_Addition(FStar_SizeT_v(h), FStar_SizeT_v(i));
  return FStar_SizeT_uint_to_t(Prims_op_Modulus(sum, FStar_SizeT_v(size)));
}

static krml_checked_int_t *hash_table_create(size_t size)
{
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), size);
  krml_checked_int_t *buf = KRML_HOST_MALLOC(sizeof (krml_checked_int_t) * size);
  if (buf != NULL)
    for (uint32_t _i = 0U; _i < size; ++_i)
      buf[_i] = (krml_checked_int_t)-1;
  return buf;
}

static void hash_table_free(krml_checked_int_t *tv)
{
  KRML_HOST_FREE(tv);
}

static bool hash_insert(krml_checked_int_t *table, size_t size, krml_checked_int_t key)
{
  size_t i = (size_t)0U;
  bool inserted = false;
  bool vinserted = inserted;
  size_t vi0 = i;
  bool cond = !vinserted && vi0 < size;
  while (cond)
  {
    size_t vi0 = i;
    size_t idx = hash_probe(key, vi0, size);
    krml_checked_int_t slot = table[idx];
    bool can_insert = slot == (krml_checked_int_t)-1 || slot == (krml_checked_int_t)-2;
    krml_checked_int_t new_val;
    if (can_insert)
      new_val = key;
    else
      new_val = slot;
    table[idx] = new_val;
    bool vinserted = inserted;
    bool new_inserted;
    if (can_insert)
      new_inserted = true;
    else
      new_inserted = vinserted;
    inserted = new_inserted;
    i = vi0 + (size_t)1U;
    bool vinserted0 = inserted;
    size_t vi = i;
    cond = !vinserted0 && vi < size;
  }
  return inserted;
}

static size_t hash_search(krml_checked_int_t *table, size_t size, krml_checked_int_t key)
{
  size_t i = (size_t)0U;
  size_t found_idx = size;
  bool done = false;
  bool vdone = done;
  size_t vi0 = i;
  bool cond = !vdone && vi0 < size;
  while (cond)
  {
    size_t vi0 = i;
    size_t idx = hash_probe(key, vi0, size);
    krml_checked_int_t slot = table[idx];
    bool is_found = slot == key;
    bool is_empty = slot == (krml_checked_int_t)-1;
    size_t vfound_idx_inner = found_idx;
    size_t new_found_idx;
    if (is_found)
      new_found_idx = idx;
    else
      new_found_idx = vfound_idx_inner;
    found_idx = new_found_idx;
    bool vdone_inner = done;
    bool new_done;
    if (is_found || is_empty)
      new_done = true;
    else
      new_done = vdone_inner;
    done = new_done;
    i = vi0 + (size_t)1U;
    bool vdone = done;
    size_t vi = i;
    cond = !vdone && vi < size;
  }
  return found_idx;
}

static bool hash_delete(krml_checked_int_t *table, size_t size, krml_checked_int_t key)
{
  size_t search_result = hash_search(table, size, key);
  if (search_result < size)
  {
    table[search_result] = (krml_checked_int_t)-2;
    return true;
  }
  else
    return false;
}

static bool hash_insert_no_dup(krml_checked_int_t *table, size_t size, krml_checked_int_t key)
{
  size_t search_result = hash_search(table, size, key);
  if (search_result < size)
    return true;
  else
    return hash_insert(table, size, key);
}

bool CLRS_Ch11_HashTable_ImplTest_test_search_empty(void)
{
  krml_checked_int_t *tv = hash_table_create((size_t)3U);
  krml_checked_int_t *table = tv;
  size_t r = hash_search(table, (size_t)3U, (krml_checked_int_t)5);
  bool ok = r == (size_t)3U;
  hash_table_free(tv);
  return ok;
}

bool CLRS_Ch11_HashTable_ImplTest_test_insert_then_search(void)
{
  krml_checked_int_t *tv = hash_table_create((size_t)3U);
  krml_checked_int_t *table = tv;
  bool b = hash_insert(table, (size_t)3U, (krml_checked_int_t)0);
  size_t r = hash_search(table, (size_t)3U, (krml_checked_int_t)0);
  bool ok = b && r < (size_t)3U;
  hash_table_free(tv);
  return ok;
}

bool CLRS_Ch11_HashTable_ImplTest_test_insert_search_absent(void)
{
  krml_checked_int_t *tv = hash_table_create((size_t)3U);
  krml_checked_int_t *table = tv;
  bool b = hash_insert(table, (size_t)3U, (krml_checked_int_t)0);
  size_t r = hash_search(table, (size_t)3U, (krml_checked_int_t)1);
  bool ok = b && r == (size_t)3U;
  hash_table_free(tv);
  return ok;
}

bool CLRS_Ch11_HashTable_ImplTest_test_delete_then_search(void)
{
  krml_checked_int_t *tv = hash_table_create((size_t)3U);
  krml_checked_int_t *table = tv;
  bool b1 = hash_insert(table, (size_t)3U, (krml_checked_int_t)0);
  bool b2 = hash_delete(table, (size_t)3U, (krml_checked_int_t)0);
  size_t r = hash_search(table, (size_t)3U, (krml_checked_int_t)0);
  bool ok = b1 && b2 && r == (size_t)3U;
  hash_table_free(tv);
  return ok;
}

bool CLRS_Ch11_HashTable_ImplTest_test_insert_no_dup_existing(void)
{
  krml_checked_int_t *tv = hash_table_create((size_t)3U);
  krml_checked_int_t *table = tv;
  bool b1 = hash_insert(table, (size_t)3U, (krml_checked_int_t)0);
  bool b2 = hash_insert_no_dup(table, (size_t)3U, (krml_checked_int_t)0);
  size_t r = hash_search(table, (size_t)3U, (krml_checked_int_t)0);
  bool ok = b1 && b2 && r < (size_t)3U;
  hash_table_free(tv);
  return ok;
}

bool CLRS_Ch11_HashTable_ImplTest_test_insert_no_dup_fresh(void)
{
  krml_checked_int_t *tv = hash_table_create((size_t)3U);
  krml_checked_int_t *table = tv;
  bool b = hash_insert_no_dup(table, (size_t)3U, (krml_checked_int_t)0);
  size_t r = hash_search(table, (size_t)3U, (krml_checked_int_t)0);
  bool ok = b && r < (size_t)3U;
  hash_table_free(tv);
  return ok;
}

bool CLRS_Ch11_HashTable_ImplTest_test_create_free(void)
{
  krml_checked_int_t *tv = hash_table_create((size_t)5U);
  hash_table_free(tv);
  return true;
}

