/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch23.Prim.ImplTest+CLRS.Ch23.Prim.Impl+CLRS.Ch23.Kruskal.ImplTest+CLRS.Ch23.Kruskal.Impl=CLRS.*[rename=Ch23_MST] -tmpdir _output/c _output/CLRS_Ch23_Prim_ImplTest.krml _output/CLRS_Ch23_Prim_Impl.krml _output/CLRS_Ch23_Kruskal_ImplTest.krml _output/CLRS_Ch23_Kruskal_Impl.krml _output/CLRS_Ch23_MST_Spec.krml _output/CLRS_Ch23_Prim_Spec.krml _output/CLRS_Ch23_Prim_Greedy.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_Ch23_MST_H
#define internal_Ch23_MST_H

#include "krmllib.h"

#include "../Ch23_MST.h"
#include "krml/internal/compat.h"

typedef struct Prims_list__size_t_s Prims_list__size_t;

typedef struct Prims_list__size_t_s
{
  Prims_list__CLRS_Ch23_MST_Spec_edge_tags tag;
  size_t hd;
  Prims_list__size_t *tl;
}
Prims_list__size_t;


#define internal_Ch23_MST_H_DEFINED
#endif /* internal_Ch23_MST_H */
