/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch23.Prim.ImplTest+CLRS.Ch23.Prim.Impl+CLRS.Ch23.Kruskal.ImplTest+CLRS.Ch23.Kruskal.Impl=CLRS.*[rename=Ch23_MST] -tmpdir _output/c _output/CLRS_Ch23_Prim_ImplTest.krml _output/CLRS_Ch23_Prim_Impl.krml _output/CLRS_Ch23_Kruskal_ImplTest.krml _output/CLRS_Ch23_Kruskal_Impl.krml _output/CLRS_Ch23_MST_Spec.krml _output/CLRS_Ch23_Prim_Spec.krml _output/CLRS_Ch23_Prim_Greedy.krml
  F* version: <unknown>
  KaRaMeL version: 7bdb6cb2fd7661f4a0dade9ccae810451cb51746
 */

#ifndef internal_Prims_H
#define internal_Prims_H

#include "krmllib.h"

#include "krml/internal/compat.h"

extern krml_checked_int_t Prims_op_Multiply(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_Prims_H_DEFINED
#endif /* internal_Prims_H */
