/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch31.GCD.ImplTest+CLRS.Ch31.ExtendedGCD.ImplTest+CLRS.Ch31.ModExp.ImplTest+CLRS.Ch31.ModExpLR.ImplTest=CLRS.*[rename=Ch31_NumberTheory] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch31_GCD_ImplTest.krml _output/CLRS_Ch31_GCD_Impl.krml _output/CLRS_Ch31_GCD_Spec.krml _output/CLRS_Ch31_GCD_Complexity.krml _output/CLRS_Ch31_GCD_Lemmas.krml _output/CLRS_Ch31_ExtendedGCD_ImplTest.krml _output/CLRS_Ch31_ExtendedGCD_Impl.krml _output/CLRS_Ch31_ExtendedGCD_Spec.krml _output/CLRS_Ch31_ExtendedGCD_Complexity.krml _output/CLRS_Ch31_ExtendedGCD_Lemmas.krml _output/CLRS_Ch31_ModExp_ImplTest.krml _output/CLRS_Ch31_ModExp_Impl.krml _output/CLRS_Ch31_ModExp_Spec.krml _output/CLRS_Ch31_ModExp_Complexity.krml _output/CLRS_Ch31_ModExp_Lemmas.krml _output/CLRS_Ch31_ModExpLR_ImplTest.krml _output/CLRS_Ch31_ModExpLR_Impl.krml _output/CLRS_Ch31_ModExpLR_Complexity.krml _output/CLRS_Ch31_ModExpLR_Lemmas.krml _output/CLRS_Common_Complexity.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "Ch31_NumberTheory.h"

static size_t gcd_impl(size_t a_init, size_t b_init)
{
  size_t a = a_init;
  size_t b = b_init;
  size_t __anf0 = b;
  bool cond = __anf0 > (size_t)0U;
  while (cond)
  {
    size_t va = a;
    size_t vb = b;
    size_t temp = va % vb;
    a = vb;
    b = temp;
    size_t __anf0 = b;
    cond = __anf0 > (size_t)0U;
  }
  return a;
}

static size_t extended_gcd_impl(size_t a_init, size_t b_init)
{
  size_t a = a_init;
  size_t b = b_init;
  size_t __anf0 = b;
  bool cond = __anf0 > (size_t)0U;
  while (cond)
  {
    size_t va = a;
    size_t vb = b;
    size_t temp = va % vb;
    a = vb;
    b = temp;
    size_t __anf0 = b;
    cond = __anf0 > (size_t)0U;
  }
  return a;
}

static size_t mod_exp_impl(size_t b_init, size_t e_init, size_t m_init)
{
  size_t result = (size_t)1U % m_init;
  size_t base = b_init % m_init;
  size_t exp = e_init;
  size_t ve0 = exp;
  bool cond = ve0 > (size_t)0U;
  while (cond)
  {
    size_t ve = exp;
    size_t vr = result;
    size_t vb = base;
    if (ve % (size_t)2U == (size_t)1U)
      result = vr * vb % m_init;
    else
      result = vr;
    size_t vb2 = base;
    base = vb2 * vb2 % m_init;
    size_t ve2 = exp;
    exp = ve2 / (size_t)2U;
    size_t ve0 = exp;
    cond = ve0 > (size_t)0U;
  }
  return result;
}

static size_t mod_exp_lr_impl(size_t b_init, size_t e_init, size_t m_init)
{
  if (e_init == (size_t)0U)
    return (size_t)1U % m_init;
  else
  {
    size_t b_mod = b_init % m_init;
    size_t mask = (size_t)1U;
    size_t vm0 = mask;
    bool cond = vm0 <= e_init / (size_t)2U;
    while (cond)
    {
      size_t vm = mask;
      mask = vm * (size_t)2U;
      size_t vm0 = mask;
      cond = vm0 <= e_init / (size_t)2U;
    }
    size_t d = (size_t)1U % m_init;
    size_t vm = mask;
    bool cond0 = vm > (size_t)0U;
    while (cond0)
    {
      size_t vmask = mask;
      size_t vd = d;
      size_t bit = e_init / vmask % (size_t)2U;
      size_t sq = vd * vd % m_init;
      if (bit == (size_t)1U)
        d = sq * b_mod % m_init;
      else
        d = sq;
      mask = vmask / (size_t)2U;
      size_t vm = mask;
      cond0 = vm > (size_t)0U;
    }
    return d;
  }
}

bool CLRS_Ch31_GCD_ImplTest_test_gcd(void)
{
  size_t result = gcd_impl((size_t)12U, (size_t)8U);
  return !(result < (size_t)4U || (size_t)4U < result);
}

bool CLRS_Ch31_ExtendedGCD_ImplTest_test_extended_gcd(void)
{
  size_t result = extended_gcd_impl((size_t)35U, (size_t)15U);
  return !(result < (size_t)5U || (size_t)5U < result);
}

bool CLRS_Ch31_ModExp_ImplTest_test_mod_exp(void)
{
  size_t result = mod_exp_impl((size_t)2U, (size_t)10U, (size_t)100U);
  return !(result < (size_t)24U || (size_t)24U < result);
}

bool CLRS_Ch31_ModExpLR_ImplTest_test_mod_exp_lr(void)
{
  size_t result = mod_exp_lr_impl((size_t)3U, (size_t)5U, (size_t)7U);
  return !(result < (size_t)5U || (size_t)5U < result);
}

