/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch31.GCD.ImplTest+CLRS.Ch31.ExtendedGCD.ImplTest+CLRS.Ch31.ModExp.ImplTest+CLRS.Ch31.ModExpLR.ImplTest=CLRS.*[rename=Ch31_NumberTheory] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch31_GCD_ImplTest.krml _output/CLRS_Ch31_GCD_Impl.krml _output/CLRS_Ch31_GCD_Spec.krml _output/CLRS_Ch31_GCD_Complexity.krml _output/CLRS_Ch31_GCD_Lemmas.krml _output/CLRS_Ch31_ExtendedGCD_ImplTest.krml _output/CLRS_Ch31_ExtendedGCD_Impl.krml _output/CLRS_Ch31_ExtendedGCD_Spec.krml _output/CLRS_Ch31_ExtendedGCD_Complexity.krml _output/CLRS_Ch31_ExtendedGCD_Lemmas.krml _output/CLRS_Ch31_ModExp_ImplTest.krml _output/CLRS_Ch31_ModExp_Impl.krml _output/CLRS_Ch31_ModExp_Spec.krml _output/CLRS_Ch31_ModExp_Complexity.krml _output/CLRS_Ch31_ModExp_Lemmas.krml _output/CLRS_Ch31_ModExpLR_ImplTest.krml _output/CLRS_Ch31_ModExpLR_Impl.krml _output/CLRS_Ch31_ModExpLR_Complexity.krml _output/CLRS_Ch31_ModExpLR_Lemmas.krml _output/CLRS_Common_Complexity.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef Ch31_NumberTheory_H
#define Ch31_NumberTheory_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch31_GCD_ImplTest_test_gcd(void);

bool CLRS_Ch31_ExtendedGCD_ImplTest_test_extended_gcd(void);

bool CLRS_Ch31_ModExp_ImplTest_test_mod_exp(void);

bool CLRS_Ch31_ModExpLR_ImplTest_test_mod_exp_lr(void);


#define Ch31_NumberTheory_H_DEFINED
#endif /* Ch31_NumberTheory_H */
