/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch23.Prim.ImplTest+CLRS.Ch23.Prim.Impl+CLRS.Ch23.Kruskal.ImplTest+CLRS.Ch23.Kruskal.Impl=CLRS.*[rename=Ch23_MST] -tmpdir _output/c _output/CLRS_Ch23_Prim_ImplTest.krml _output/CLRS_Ch23_Prim_Impl.krml _output/CLRS_Ch23_Kruskal_ImplTest.krml _output/CLRS_Ch23_Kruskal_Impl.krml _output/CLRS_Ch23_MST_Spec.krml _output/CLRS_Ch23_Prim_Spec.krml _output/CLRS_Ch23_Prim_Greedy.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/Ch23_MST.h"

#include "internal/Prims.h"

bool CLRS_Ch23_Prim_ImplTest_sz_eq(size_t a, size_t b)
{
  return !(a < b || b < a);
}

bool CLRS_Ch23_Prim_ImplTest_test_prim_3(void)
{
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)9U);
  size_t *wv = KRML_HOST_CALLOC((size_t)9U, sizeof (size_t));
  size_t *weights = wv;
  weights[0U] = (size_t)0U;
  weights[1U] = (size_t)1U;
  weights[2U] = (size_t)3U;
  weights[3U] = (size_t)1U;
  weights[4U] = (size_t)0U;
  weights[5U] = (size_t)2U;
  weights[6U] = (size_t)3U;
  weights[7U] = (size_t)2U;
  weights[8U] = (size_t)0U;
  K____size_t___size_t_ _letpattern = CLRS_Ch23_Prim_Impl_prim(weights, (size_t)3U, (size_t)0U);
  size_t *key_vec = _letpattern.fst;
  size_t *parent_vec = _letpattern.snd;
  size_t *key_arr = key_vec;
  size_t k0 = key_arr[0U];
  size_t k1 = key_arr[1U];
  size_t k2 = key_arr[2U];
  size_t *parent_arr = parent_vec;
  size_t p0 = parent_arr[0U];
  size_t p1 = parent_arr[1U];
  size_t p2 = parent_arr[2U];
  bool
  pass =
    !(k0 < (size_t)0U || (size_t)0U < k0) && !(k1 < (size_t)1U || (size_t)1U < k1) &&
      !(k2 < (size_t)2U || (size_t)2U < k2)
    && !(p0 < (size_t)0U || (size_t)0U < p0)
    && !(p1 < (size_t)0U || (size_t)0U < p1)
    && !(p2 < (size_t)1U || (size_t)1U < p2);
  KRML_HOST_FREE(wv);
  return pass;
}

size_t CLRS_Ch23_Prim_Impl_infinity = (size_t)65535U;

typedef struct __size_t_size_t_s
{
  size_t fst;
  size_t snd;
}
__size_t_size_t;

static __size_t_size_t find_min_vertex(size_t *key_a, size_t *in_mst, size_t n)
{
  size_t min_idx = (size_t)0U;
  size_t min_key = CLRS_Ch23_Prim_Impl_infinity;
  size_t find_i = (size_t)0U;
  size_t v_find_i0 = find_i;
  bool cond = v_find_i0 < n;
  while (cond)
  {
    size_t v_find_i = find_i;
    size_t ki = key_a[v_find_i];
    size_t in_mst_i = in_mst[v_find_i];
    size_t v_min_key = min_key;
    size_t v_min_idx = min_idx;
    bool cond1 = in_mst_i == (size_t)0U;
    bool cond2 = ki < v_min_key;
    bool should_update = cond1 && cond2;
    size_t new_min_key;
    if (should_update)
      new_min_key = ki;
    else
      new_min_key = v_min_key;
    size_t new_min_idx;
    if (should_update)
      new_min_idx = v_find_i;
    else
      new_min_idx = v_min_idx;
    min_key = new_min_key;
    min_idx = new_min_idx;
    find_i = v_find_i + (size_t)1U;
    size_t v_find_i0 = find_i;
    cond = v_find_i0 < n;
  }
  size_t result = min_idx;
  size_t final_key = min_key;
  return ((__size_t_size_t){ .fst = result, .snd = final_key });
}

static void
update_keys(
  size_t *key_a,
  size_t *in_mst,
  size_t *parent_a,
  size_t *weights,
  size_t n,
  size_t u
)
{
  size_t update_i = (size_t)0U;
  size_t vi = update_i;
  bool cond = vi < n;
  while (cond)
  {
    size_t v = update_i;
    size_t key_v = key_a[v];
    size_t in_mst_v = in_mst[v];
    uint64_t u64_u = (uint64_t)u;
    uint64_t u64_n = (uint64_t)n;
    uint64_t u64_v = (uint64_t)v;
    uint64_t prod_mod = u64_u * u64_n;
    uint64_t idx_mod = prod_mod + u64_v;
    size_t weight_idx = (size_t)idx_mod;
    size_t weight_uv = weights[weight_idx];
    size_t old_parent_v = parent_a[v];
    bool cond_not_in_mst = in_mst_v == (size_t)0U;
    bool cond_weight_better = weight_uv < key_v;
    bool cond_weight_valid = weight_uv < CLRS_Ch23_Prim_Impl_infinity;
    bool should_update_key = cond_not_in_mst && cond_weight_better && cond_weight_valid;
    size_t new_key_v;
    if (should_update_key)
      new_key_v = weight_uv;
    else
      new_key_v = key_v;
    size_t new_parent_v;
    if (should_update_key)
      new_parent_v = u;
    else
      new_parent_v = old_parent_v;
    key_a[v] = new_key_v;
    parent_a[v] = new_parent_v;
    update_i = v + (size_t)1U;
    size_t vi = update_i;
    cond = vi < n;
  }
}

static void
prim_step(size_t *key_a, size_t *in_mst, size_t *parent_a, size_t *weights, size_t n)
{
  __size_t_size_t _letpattern = find_min_vertex(key_a, in_mst, n);
  size_t u = _letpattern.fst;
  in_mst[u] = (size_t)1U;
  update_keys(key_a, in_mst, parent_a, weights, n, u);
}

K____size_t___size_t_ CLRS_Ch23_Prim_Impl_prim(size_t *weights, size_t n, size_t source)
{
  KRML_CHECK_SIZE(sizeof (size_t), n);
  size_t *key = KRML_HOST_MALLOC(sizeof (size_t) * n);
  if (key != NULL)
    for (uint32_t _i = 0U; _i < n; ++_i)
      key[_i] = CLRS_Ch23_Prim_Impl_infinity;
  size_t *key_a = key;
  KRML_CHECK_SIZE(sizeof (size_t), n);
  size_t *parent_v = KRML_HOST_MALLOC(sizeof (size_t) * n);
  if (parent_v != NULL)
    for (uint32_t _i = 0U; _i < n; ++_i)
      parent_v[_i] = source;
  size_t *parent_a = parent_v;
  key_a[source] = (size_t)0U;
  KRML_CHECK_SIZE(sizeof (size_t), n);
  size_t *in_mst_v = KRML_HOST_CALLOC(n, sizeof (size_t));
  size_t *in_mst = in_mst_v;
  size_t iter = (size_t)0U;
  size_t v_iter0 = iter;
  bool cond = v_iter0 < n;
  while (cond)
  {
    prim_step(key_a, in_mst, parent_a, weights, n);
    size_t v_iter = iter;
    size_t new_iter = v_iter + (size_t)1U;
    iter = new_iter;
    size_t v_iter0 = iter;
    cond = v_iter0 < n;
  }
  parent_a[source] = source;
  KRML_HOST_FREE(in_mst_v);
  return ((K____size_t___size_t_){ .fst = key, .snd = parent_v });
}

bool CLRS_Ch23_Kruskal_ImplTest_sz_eq(size_t a, size_t b)
{
  return !(a < b || b < a);
}

bool CLRS_Ch23_Kruskal_ImplTest_test_kruskal_satisfiability(void)
{
  krml_checked_int_t *adj_v = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *adj = adj_v;
  adj[0U] = (krml_checked_int_t)0;
  adj[1U] = (krml_checked_int_t)1;
  adj[2U] = (krml_checked_int_t)3;
  adj[3U] = (krml_checked_int_t)1;
  adj[4U] = (krml_checked_int_t)0;
  adj[5U] = (krml_checked_int_t)2;
  adj[6U] = (krml_checked_int_t)3;
  adj[7U] = (krml_checked_int_t)2;
  adj[8U] = (krml_checked_int_t)0;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *eu_v = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *edge_u = eu_v;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *ev_v = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *edge_v = ev_v;
  size_t ec_ref = (size_t)0U;
  CLRS_Ch23_Kruskal_Impl_kruskal(adj, edge_u, edge_v, &ec_ref, (size_t)3U);
  size_t ec_val = ec_ref;
  size_t eu0 = edge_u[0U];
  size_t ev0 = edge_v[0U];
  size_t eu1 = edge_u[1U];
  size_t ev1 = edge_v[1U];
  bool
  e0_is_01 =
    !(eu0 < (size_t)0U || (size_t)0U < eu0) && !(ev0 < (size_t)1U || (size_t)1U < ev0) ||
      !(eu0 < (size_t)1U || (size_t)1U < eu0) && !(ev0 < (size_t)0U || (size_t)0U < ev0);
  bool
  e0_is_12 =
    !(eu0 < (size_t)1U || (size_t)1U < eu0) && !(ev0 < (size_t)2U || (size_t)2U < ev0) ||
      !(eu0 < (size_t)2U || (size_t)2U < eu0) && !(ev0 < (size_t)1U || (size_t)1U < ev0);
  bool
  e1_is_01 =
    !(eu1 < (size_t)0U || (size_t)0U < eu1) && !(ev1 < (size_t)1U || (size_t)1U < ev1) ||
      !(eu1 < (size_t)1U || (size_t)1U < eu1) && !(ev1 < (size_t)0U || (size_t)0U < ev1);
  bool
  e1_is_12 =
    !(eu1 < (size_t)1U || (size_t)1U < eu1) && !(ev1 < (size_t)2U || (size_t)2U < ev1) ||
      !(eu1 < (size_t)2U || (size_t)2U < eu1) && !(ev1 < (size_t)1U || (size_t)1U < ev1);
  bool
  pass =
    !(ec_val < (size_t)2U || (size_t)2U < ec_val) && (e0_is_01 && e1_is_12 || e0_is_12 && e1_is_01);
  KRML_HOST_FREE(adj_v);
  KRML_HOST_FREE(eu_v);
  KRML_HOST_FREE(ev_v);
  return pass;
}

static size_t find(size_t *parent, size_t v, size_t n)
{
  size_t curr = v;
  size_t steps = (size_t)0U;
  size_t __anf0 = steps;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t vcurr = curr;
    size_t p1 = parent[vcurr];
    curr = p1;
    size_t vsteps = steps;
    steps = vsteps + (size_t)1U;
    size_t __anf0 = steps;
    cond = __anf0 < n;
  }
  return curr;
}

static void do_union(size_t *parent, size_t root_u, size_t root_v)
{
  parent[root_u] = root_v;
}

void
CLRS_Ch23_Kruskal_Impl_kruskal(
  krml_checked_int_t *adj,
  size_t *edge_u,
  size_t *edge_v,
  size_t *edge_count,
  size_t n
)
{
  KRML_CHECK_SIZE(sizeof (size_t), n);
  size_t *parent_v = KRML_HOST_CALLOC(n, sizeof (size_t));
  size_t *parent = parent_v;
  size_t i = (size_t)0U;
  size_t __anf00 = i;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t vi = i;
    parent[vi] = vi;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
  size_t round = (size_t)0U;
  size_t max_rounds = n - (size_t)1U;
  size_t __anf01 = round;
  bool cond0 = __anf01 < max_rounds;
  while (cond0)
  {
    size_t vround = round;
    size_t best_u = (size_t)0U;
    size_t best_v = (size_t)0U;
    krml_checked_int_t best_w = (krml_checked_int_t)0;
    size_t ui = (size_t)0U;
    size_t __anf00 = ui;
    bool cond = __anf00 < n;
    while (cond)
    {
      size_t vui = ui;
      size_t vi = (size_t)0U;
      size_t __anf0 = vi;
      bool cond0 = __anf0 < n;
      while (cond0)
      {
        size_t vvi = vi;
        size_t offset = vui * n;
        size_t idx = offset + vvi;
        krml_checked_int_t w = adj[idx];
        krml_checked_int_t vbw = best_w;
        size_t vbu_old = best_u;
        size_t vbv_old = best_v;
        size_t root_ui = find(parent, vui, n);
        size_t root_vi = find(parent, vvi, n);
        bool diff_comp = root_ui != root_vi;
        bool
        take_it =
          Prims_op_GreaterThan(w, (krml_checked_int_t)0) && diff_comp &&
            (vbw == (krml_checked_int_t)0 || Prims_op_LessThan(w, vbw));
        size_t ite;
        if (take_it)
          ite = vui;
        else
          ite = vbu_old;
        best_u = ite;
        size_t ite0;
        if (take_it)
          ite0 = vvi;
        else
          ite0 = vbv_old;
        best_v = ite0;
        krml_checked_int_t ite1;
        if (take_it)
          ite1 = w;
        else
          ite1 = vbw;
        best_w = ite1;
        vi = vvi + (size_t)1U;
        size_t __anf0 = vi;
        cond0 = __anf0 < n;
      }
      ui = vui + (size_t)1U;
      size_t __anf00 = ui;
      cond = __anf00 < n;
    }
    size_t vbu = best_u;
    size_t vbv = best_v;
    krml_checked_int_t vbw = best_w;
    size_t vec = *edge_count;
    size_t root_u = find(parent, vbu, n);
    size_t root_v = find(parent, vbv, n);
    bool
    should_add = Prims_op_GreaterThan(vbw, (krml_checked_int_t)0) && root_u != root_v && vec < n;
    size_t old_eu0 = edge_u[0U];
    size_t old_ev0 = edge_v[0U];
    size_t write_pos;
    if (should_add)
      write_pos = vec;
    else
      write_pos = (size_t)0U;
    size_t ite;
    if (should_add)
      ite = vbu;
    else
      ite = old_eu0;
    edge_u[write_pos] = ite;
    size_t ite0;
    if (should_add)
      ite0 = vbv;
    else
      ite0 = old_ev0;
    edge_v[write_pos] = ite0;
    size_t ite1;
    if (should_add)
      ite1 = vec + (size_t)1U;
    else
      ite1 = vec;
    *edge_count = ite1;
    do_union(parent, root_u, root_v);
    round = vround + (size_t)1U;
    size_t __anf0 = round;
    cond0 = __anf0 < max_rounds;
  }
  KRML_HOST_FREE(parent_v);
}

