/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch23.Prim.ImplTest+CLRS.Ch23.Prim.Impl+CLRS.Ch23.Kruskal.ImplTest+CLRS.Ch23.Kruskal.Impl=CLRS.*[rename=Ch23_MST] -tmpdir _output/c _output/CLRS_Ch23_Prim_ImplTest.krml _output/CLRS_Ch23_Prim_Impl.krml _output/CLRS_Ch23_Kruskal_ImplTest.krml _output/CLRS_Ch23_Kruskal_Impl.krml _output/CLRS_Ch23_MST_Spec.krml _output/CLRS_Ch23_Prim_Spec.krml _output/CLRS_Ch23_Prim_Greedy.krml
  F* version: <unknown>
  KaRaMeL version: 7bdb6cb2fd7661f4a0dade9ccae810451cb51746
 */

#ifndef Ch23_MST_H
#define Ch23_MST_H

#include "krmllib.h"

#include "krml/internal/compat.h"

typedef struct CLRS_Ch23_MST_Spec_edge_s
{
  krml_checked_int_t u;
  krml_checked_int_t v;
  krml_checked_int_t w;
}
CLRS_Ch23_MST_Spec_edge;

typedef struct Prims_list__CLRS_Ch23_MST_Spec_edge_s Prims_list__CLRS_Ch23_MST_Spec_edge;

#define Prims_Nil 0
#define Prims_Cons 1

typedef uint8_t Prims_list__CLRS_Ch23_MST_Spec_edge_tags;

typedef struct Prims_list__CLRS_Ch23_MST_Spec_edge_s
{
  Prims_list__CLRS_Ch23_MST_Spec_edge_tags tag;
  CLRS_Ch23_MST_Spec_edge hd;
  Prims_list__CLRS_Ch23_MST_Spec_edge *tl;
}
Prims_list__CLRS_Ch23_MST_Spec_edge;

typedef struct CLRS_Ch23_MST_Spec_graph_s
{
  krml_checked_int_t n;
  Prims_list__CLRS_Ch23_MST_Spec_edge *edges;
}
CLRS_Ch23_MST_Spec_graph;

bool CLRS_Ch23_Prim_ImplTest_sz_eq(size_t a, size_t b);

typedef struct K____size_t___size_t__s
{
  size_t *fst;
  size_t *snd;
}
K____size_t___size_t_;

bool CLRS_Ch23_Prim_ImplTest_test_prim_3(void);

extern size_t CLRS_Ch23_Prim_Impl_infinity;

typedef void *CLRS_Ch23_Prim_Impl_valid_weights;

typedef void *CLRS_Ch23_Prim_Impl_all_keys_bounded;

typedef void *CLRS_Ch23_Prim_Impl_parent_valid;

typedef void *CLRS_Ch23_Prim_Impl_key_parent_consistent;

typedef void *CLRS_Ch23_Prim_Impl_prim_correct;

typedef void *CLRS_Ch23_Prim_Impl_symmetric_weights;

typedef void *CLRS_Ch23_Prim_Impl_prim_mst_result;

K____size_t___size_t_ CLRS_Ch23_Prim_Impl_prim(size_t *weights, size_t n, size_t source);

bool CLRS_Ch23_Kruskal_ImplTest_sz_eq(size_t a, size_t b);

bool CLRS_Ch23_Kruskal_ImplTest_test_kruskal_satisfiability(void);

typedef void *CLRS_Ch23_Kruskal_Impl_symmetric_adj;

typedef void *CLRS_Ch23_Kruskal_Impl_no_self_loops_adj;

typedef void *CLRS_Ch23_Kruskal_Impl_edges_safe;

typedef void *CLRS_Ch23_Kruskal_Impl_kruskal_mst_result;

void
CLRS_Ch23_Kruskal_Impl_kruskal(
  krml_checked_int_t *adj,
  size_t *edge_u,
  size_t *edge_v,
  size_t *edge_count,
  size_t n
);


#define Ch23_MST_H_DEFINED
#endif /* Ch23_MST_H */
