/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch08.CountingSort.ImplTest+CLRS.Ch08.CountingSort.Impl=CLRS.Ch08.CountingSort.ImplTest,CLRS.Ch08.CountingSort.Impl[rename=ImplTest] -bundle FStar.*,Pulse.*,PulseCore.*,Prims,CLRS.Ch08.CountingSort.Spec,CLRS.Ch08.CountingSort.Lemmas,CLRS.Ch08.CountingSort.StableLemmas,CLRS.Ch08.CountingSort.DigitSortLemmas,CLRS.Ch08.RadixSort.* -add-early-include "fstar_sizet_shim.h" -tmpdir _output _output/CLRS_Ch08_CountingSort_ImplTest.krml _output/CLRS_Ch08_CountingSort_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_PulseCore_Prims_CLRS_Ch08_CountingSort_Spec_CLRS_Ch08_CountingSort_Lemmas_CLRS_Ch08_CountingSort_StableLemmas_CLRS_Ch08_CountingSort_DigitSortLemmas_CLRS_Ch08_RadixSort_H
#define internal_FStar_Pulse_PulseCore_Prims_CLRS_Ch08_CountingSort_Spec_CLRS_Ch08_CountingSort_Lemmas_CLRS_Ch08_CountingSort_StableLemmas_CLRS_Ch08_CountingSort_DigitSortLemmas_CLRS_Ch08_RadixSort_H

#include "fstar_sizet_shim.h"

#include "krmllib.h"

#include "krml/internal/compat.h"

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);


#define internal_FStar_Pulse_PulseCore_Prims_CLRS_Ch08_CountingSort_Spec_CLRS_Ch08_CountingSort_Lemmas_CLRS_Ch08_CountingSort_StableLemmas_CLRS_Ch08_CountingSort_DigitSortLemmas_CLRS_Ch08_RadixSort_H_DEFINED
#endif /* internal_FStar_Pulse_PulseCore_Prims_CLRS_Ch08_CountingSort_Spec_CLRS_Ch08_CountingSort_Lemmas_CLRS_Ch08_CountingSort_StableLemmas_CLRS_Ch08_CountingSort_DigitSortLemmas_CLRS_Ch08_RadixSort_H */
