/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch33.Segments.ImplTest+CLRS.Ch33.GrahamScan.ImplTest+CLRS.Ch33.JarvisMarch.ImplTest=CLRS.Ch33.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch33_Segments_Impl.krml _output/CLRS_Ch33_Segments_ImplTest.krml _output/CLRS_Ch33_GrahamScan_Impl.krml _output/CLRS_Ch33_GrahamScan_ImplTest.krml _output/CLRS_Ch33_JarvisMarch_Impl.krml _output/CLRS_Ch33_JarvisMarch_ImplTest.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch33_Segments_ImplTest_CLRS_Ch33_GrahamScan_ImplTest_CLRS_Ch33_JarvisMarch_ImplTest_H
#define CLRS_Ch33_Segments_ImplTest_CLRS_Ch33_GrahamScan_ImplTest_CLRS_Ch33_JarvisMarch_ImplTest_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch33_Segments_ImplTest_test_cross_product(void);

bool CLRS_Ch33_Segments_ImplTest_test_direction(void);

bool CLRS_Ch33_Segments_ImplTest_test_on_segment(void);

bool CLRS_Ch33_Segments_ImplTest_test_segments_intersect(void);

bool CLRS_Ch33_GrahamScan_ImplTest_test_find_bottom(void);

bool CLRS_Ch33_GrahamScan_ImplTest_test_polar_cmp(void);

bool CLRS_Ch33_GrahamScan_ImplTest_test_pop_while(void);

bool CLRS_Ch33_GrahamScan_ImplTest_test_graham_scan_step(void);

bool CLRS_Ch33_JarvisMarch_ImplTest_test_find_leftmost(void);

bool CLRS_Ch33_JarvisMarch_ImplTest_test_find_next(void);

bool CLRS_Ch33_JarvisMarch_ImplTest_test_jarvis_march(void);

bool CLRS_Ch33_JarvisMarch_ImplTest_test_jarvis_march_with_hull(void);


#define CLRS_Ch33_Segments_ImplTest_CLRS_Ch33_GrahamScan_ImplTest_CLRS_Ch33_JarvisMarch_ImplTest_H_DEFINED
#endif /* CLRS_Ch33_Segments_ImplTest_CLRS_Ch33_GrahamScan_ImplTest_CLRS_Ch33_JarvisMarch_ImplTest_H */
