/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch33.Segments.ImplTest+CLRS.Ch33.GrahamScan.ImplTest+CLRS.Ch33.JarvisMarch.ImplTest=CLRS.Ch33.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch33_Segments_Impl.krml _output/CLRS_Ch33_Segments_ImplTest.krml _output/CLRS_Ch33_GrahamScan_Impl.krml _output/CLRS_Ch33_GrahamScan_ImplTest.krml _output/CLRS_Ch33_JarvisMarch_Impl.krml _output/CLRS_Ch33_JarvisMarch_ImplTest.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch33_Segments_ImplTest_CLRS_Ch33_GrahamScan_ImplTest_CLRS_Ch33_JarvisMarch_ImplTest.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

static krml_checked_int_t
cross_product(
  krml_checked_int_t x1,
  krml_checked_int_t y1,
  krml_checked_int_t x2,
  krml_checked_int_t y2,
  krml_checked_int_t x3,
  krml_checked_int_t y3
)
{
  krml_checked_int_t dx21 = Prims_op_Subtraction(x2, x1);
  krml_checked_int_t dy31 = Prims_op_Subtraction(y3, y1);
  krml_checked_int_t dx31 = Prims_op_Subtraction(x3, x1);
  krml_checked_int_t dy21 = Prims_op_Subtraction(y2, y1);
  krml_checked_int_t term1 = Prims_op_Multiply(dx21, dy31);
  krml_checked_int_t term2 = Prims_op_Multiply(dx31, dy21);
  return Prims_op_Subtraction(term1, term2);
}

static krml_checked_int_t
direction(
  krml_checked_int_t x1,
  krml_checked_int_t y1,
  krml_checked_int_t x2,
  krml_checked_int_t y2,
  krml_checked_int_t x3,
  krml_checked_int_t y3
)
{
  return cross_product(x1, y1, x2, y2, x3, y3);
}

static bool
on_segment(
  krml_checked_int_t x1,
  krml_checked_int_t y1,
  krml_checked_int_t x2,
  krml_checked_int_t y2,
  krml_checked_int_t x,
  krml_checked_int_t y
)
{
  krml_checked_int_t max_x;
  if (Prims_op_GreaterThanOrEqual(x1, x2))
    max_x = x1;
  else
    max_x = x2;
  krml_checked_int_t min_x;
  if (Prims_op_LessThanOrEqual(x1, x2))
    min_x = x1;
  else
    min_x = x2;
  krml_checked_int_t max_y;
  if (Prims_op_GreaterThanOrEqual(y1, y2))
    max_y = y1;
  else
    max_y = y2;
  krml_checked_int_t min_y;
  if (Prims_op_LessThanOrEqual(y1, y2))
    min_y = y1;
  else
    min_y = y2;
  bool check_x = Prims_op_LessThanOrEqual(x, max_x) && Prims_op_GreaterThanOrEqual(x, min_x);
  bool check_y = Prims_op_LessThanOrEqual(y, max_y) && Prims_op_GreaterThanOrEqual(y, min_y);
  return check_x && check_y;
}

static bool
segments_intersect(
  krml_checked_int_t x1,
  krml_checked_int_t y1,
  krml_checked_int_t x2,
  krml_checked_int_t y2,
  krml_checked_int_t x3,
  krml_checked_int_t y3,
  krml_checked_int_t x4,
  krml_checked_int_t y4
)
{
  krml_checked_int_t d1 = direction(x3, y3, x4, y4, x1, y1);
  krml_checked_int_t d2 = direction(x3, y3, x4, y4, x2, y2);
  krml_checked_int_t d3 = direction(x1, y1, x2, y2, x3, y3);
  krml_checked_int_t d4 = direction(x1, y1, x2, y2, x4, y4);
  bool
  general_case =
    (Prims_op_GreaterThan(d1, (krml_checked_int_t)0) &&
      Prims_op_LessThan(d2,
        (krml_checked_int_t)0)
    ||
      Prims_op_LessThan(d1, (krml_checked_int_t)0) &&
        Prims_op_GreaterThan(d2,
          (krml_checked_int_t)0))
    &&
      (Prims_op_GreaterThan(d3, (krml_checked_int_t)0) &&
        Prims_op_LessThan(d4,
          (krml_checked_int_t)0)
      ||
        Prims_op_LessThan(d3, (krml_checked_int_t)0) &&
          Prims_op_GreaterThan(d4,
            (krml_checked_int_t)0));
  if (general_case)
    return true;
  else
  {
    bool __anf0 = on_segment(x3, y3, x4, y4, x1, y1);
    bool case1 = d1 == (krml_checked_int_t)0 && __anf0;
    if (case1)
      return true;
    else
    {
      bool __anf01 = on_segment(x3, y3, x4, y4, x2, y2);
      bool case2 = d2 == (krml_checked_int_t)0 && __anf01;
      if (case2)
        return true;
      else
      {
        bool __anf02 = on_segment(x1, y1, x2, y2, x3, y3);
        bool case3 = d3 == (krml_checked_int_t)0 && __anf02;
        if (case3)
          return true;
        else
        {
          bool __anf03 = on_segment(x1, y1, x2, y2, x4, y4);
          return d4 == (krml_checked_int_t)0 && __anf03;
        }
      }
    }
  }
}

static size_t find_bottom(krml_checked_int_t *xs, krml_checked_int_t *ys, size_t len)
{
  size_t best = (size_t)0U;
  size_t i = (size_t)1U;
  size_t __anf0 = i;
  bool cond = __anf0 < len;
  while (cond)
  {
    size_t vi = i;
    size_t vbest = best;
    krml_checked_int_t yi = ys[vi];
    krml_checked_int_t yb = ys[vbest];
    krml_checked_int_t xi = xs[vi];
    krml_checked_int_t xb = xs[vbest];
    if (Prims_op_LessThan(yi, yb) || yi == yb && Prims_op_LessThan(xi, xb))
      best = vi;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < len;
  }
  return best;
}

static krml_checked_int_t
polar_cmp(krml_checked_int_t *xs, krml_checked_int_t *ys, size_t p0, size_t a, size_t b)
{
  krml_checked_int_t px = xs[p0];
  krml_checked_int_t py = ys[p0];
  krml_checked_int_t ax = xs[a];
  krml_checked_int_t ay = ys[a];
  krml_checked_int_t bx = xs[b];
  krml_checked_int_t b_y = ys[b];
  return
    Prims_op_Subtraction(Prims_op_Multiply(Prims_op_Subtraction(ax, px),
        Prims_op_Subtraction(b_y, py)),
      Prims_op_Multiply(Prims_op_Subtraction(bx, px), Prims_op_Subtraction(ay, py)));
}

static size_t
pop_while(
  krml_checked_int_t *xs,
  krml_checked_int_t *ys,
  size_t *hull,
  size_t top_in,
  size_t p_idx
)
{
  size_t t = top_in;
  bool keep_going = true;
  while (keep_going)
  {
    size_t vt = t;
    if (vt < (size_t)2U)
      keep_going = false;
    else
    {
      size_t t1_idx = hull[vt - (size_t)1U];
      size_t t2_idx = hull[vt - (size_t)2U];
      krml_checked_int_t t1x = xs[t1_idx];
      krml_checked_int_t t1y = ys[t1_idx];
      krml_checked_int_t t2x = xs[t2_idx];
      krml_checked_int_t t2y = ys[t2_idx];
      krml_checked_int_t px = xs[p_idx];
      krml_checked_int_t py = ys[p_idx];
      krml_checked_int_t
      cp =
        Prims_op_Subtraction(Prims_op_Multiply(Prims_op_Subtraction(t1x, t2x),
            Prims_op_Subtraction(py, t2y)),
          Prims_op_Multiply(Prims_op_Subtraction(px, t2x), Prims_op_Subtraction(t1y, t2y)));
      if (Prims_op_LessThanOrEqual(cp, (krml_checked_int_t)0))
        t = vt - (size_t)1U;
      else
        keep_going = false;
    }
  }
  return t;
}

static size_t
graham_scan_step(
  krml_checked_int_t *xs,
  krml_checked_int_t *ys,
  size_t *hull,
  size_t top_in,
  size_t p_idx
)
{
  size_t top_ = pop_while(xs, ys, hull, top_in, p_idx);
  hull[top_] = p_idx;
  return top_ + (size_t)1U;
}

static size_t find_leftmost(krml_checked_int_t *xs, krml_checked_int_t *ys, size_t len)
{
  size_t best = (size_t)0U;
  size_t i = (size_t)1U;
  size_t __anf0 = i;
  bool cond = __anf0 < len;
  while (cond)
  {
    size_t vi = i;
    size_t vbest = best;
    krml_checked_int_t xi = xs[vi];
    krml_checked_int_t xb = xs[vbest];
    krml_checked_int_t yi = ys[vi];
    krml_checked_int_t yb = ys[vbest];
    if (Prims_op_LessThan(xi, xb) || xi == xb && Prims_op_LessThan(yi, yb))
      best = vi;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < len;
  }
  return best;
}

static size_t
find_next(krml_checked_int_t *xs, krml_checked_int_t *ys, size_t len, size_t current)
{
  size_t next = current;
  size_t j = (size_t)0U;
  size_t __anf0 = j;
  bool cond = __anf0 < len;
  while (cond)
  {
    size_t vj = j;
    size_t vnext = next;
    krml_checked_int_t cx = xs[current];
    krml_checked_int_t cy = ys[current];
    krml_checked_int_t nx = xs[vnext];
    krml_checked_int_t ny = ys[vnext];
    krml_checked_int_t jx = xs[vj];
    krml_checked_int_t jy = ys[vj];
    krml_checked_int_t
    cp =
      Prims_op_Subtraction(Prims_op_Multiply(Prims_op_Subtraction(nx, cx),
          Prims_op_Subtraction(jy, cy)),
        Prims_op_Multiply(Prims_op_Subtraction(jx, cx), Prims_op_Subtraction(ny, cy)));
    bool
    do_update =
      !(vj == current) && (vnext == current || Prims_op_LessThan(cp, (krml_checked_int_t)0));
    if (do_update)
      next = vj;
    j = vj + (size_t)1U;
    size_t __anf0 = j;
    cond = __anf0 < len;
  }
  return next;
}

static size_t jarvis_march(krml_checked_int_t *xs, krml_checked_int_t *ys, size_t len)
{
  size_t p0 = find_leftmost(xs, ys, len);
  size_t first_next = find_next(xs, ys, len, p0);
  if (first_next == p0)
    return (size_t)1U;
  else
  {
    size_t h = (size_t)2U;
    size_t current = first_next;
    bool running = true;
    while (running)
    {
      size_t vc = current;
      size_t next = find_next(xs, ys, len, vc);
      size_t vh = h;
      bool go = !(next == p0) && vh < len;
      if (go)
      {
        h = vh + (size_t)1U;
        current = next;
      }
      else
        running = false;
    }
    return h;
  }
}

static void hull_write_step(size_t *hull_out, size_t vh, size_t next)
{
  hull_out[vh] = next;
}

static size_t
jarvis_march_with_hull(
  krml_checked_int_t *xs,
  krml_checked_int_t *ys,
  size_t len,
  size_t *hull_out
)
{
  size_t p0 = find_leftmost(xs, ys, len);
  hull_out[0U] = p0;
  size_t first_next = find_next(xs, ys, len, p0);
  if (first_next == p0)
    return (size_t)1U;
  else
  {
    hull_out[1U] = first_next;
    size_t h = (size_t)2U;
    size_t current = first_next;
    bool running = true;
    while (running)
    {
      size_t vc = current;
      size_t next = find_next(xs, ys, len, vc);
      size_t vh = h;
      bool go = !(next == p0) && vh < len;
      if (go)
      {
        hull_write_step(hull_out, vh, next);
        h = vh + (size_t)1U;
        current = next;
      }
      else
        running = false;
    }
    return h;
  }
}

bool CLRS_Ch33_Segments_ImplTest_test_cross_product(void)
{
  krml_checked_int_t
  r_ccw =
    cross_product((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)1,
      (krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)1);
  krml_checked_int_t
  r_cw =
    cross_product((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)1,
      (krml_checked_int_t)1,
      (krml_checked_int_t)0);
  krml_checked_int_t
  r_col =
    cross_product((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)1,
      (krml_checked_int_t)1,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2);
  return
    r_ccw == (krml_checked_int_t)1 && r_cw == (krml_checked_int_t)-1 &&
      r_col == (krml_checked_int_t)0;
}

bool CLRS_Ch33_Segments_ImplTest_test_direction(void)
{
  krml_checked_int_t
  r =
    direction((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)1,
      (krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)1);
  return r == (krml_checked_int_t)1;
}

bool CLRS_Ch33_Segments_ImplTest_test_on_segment(void)
{
  bool
  r1 =
    on_segment((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)1,
      (krml_checked_int_t)1);
  bool
  r2 =
    on_segment((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)3,
      (krml_checked_int_t)3);
  bool
  r3 =
    on_segment((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)0,
      (krml_checked_int_t)0);
  bool
  r4 =
    on_segment((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2);
  return r1 && !r2 && r3 && r4;
}

bool CLRS_Ch33_Segments_ImplTest_test_segments_intersect(void)
{
  bool
  r1 =
    segments_intersect((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)0,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)0);
  bool
  r2 =
    segments_intersect((krml_checked_int_t)0,
      (krml_checked_int_t)0,
      (krml_checked_int_t)1,
      (krml_checked_int_t)1,
      (krml_checked_int_t)2,
      (krml_checked_int_t)2,
      (krml_checked_int_t)3,
      (krml_checked_int_t)3);
  return r1 && !r2;
}

bool CLRS_Ch33_GrahamScan_ImplTest_test_find_bottom(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)2;
  size_t r = find_bottom(xs, ys, (size_t)3U);
  bool ok = r == (size_t)0U;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  return ok;
}

bool CLRS_Ch33_GrahamScan_ImplTest_test_polar_cmp(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)2;
  krml_checked_int_t r = polar_cmp(xs, ys, (size_t)0U, (size_t)1U, (size_t)2U);
  bool ok = r == (krml_checked_int_t)4;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  return ok;
}

bool CLRS_Ch33_GrahamScan_ImplTest_test_pop_while(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)4U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  xs[3U] = (krml_checked_int_t)0;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)4U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)1;
  ys[3U] = (krml_checked_int_t)2;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)4U);
  size_t *vh = KRML_HOST_CALLOC((size_t)4U, sizeof (size_t));
  size_t *hull = vh;
  hull[0U] = (size_t)0U;
  hull[1U] = (size_t)1U;
  hull[2U] = (size_t)2U;
  size_t r = pop_while(xs, ys, hull, (size_t)3U, (size_t)3U);
  bool ok = r == (size_t)2U;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  KRML_HOST_FREE(vh);
  return ok;
}

bool CLRS_Ch33_GrahamScan_ImplTest_test_graham_scan_step(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)4U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  xs[3U] = (krml_checked_int_t)0;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)4U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)1;
  ys[3U] = (krml_checked_int_t)2;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)4U);
  size_t *vh = KRML_HOST_CALLOC((size_t)4U, sizeof (size_t));
  size_t *hull = vh;
  hull[0U] = (size_t)0U;
  hull[1U] = (size_t)1U;
  hull[2U] = (size_t)2U;
  size_t r = graham_scan_step(xs, ys, hull, (size_t)3U, (size_t)3U);
  size_t h0 = hull[0U];
  size_t h1 = hull[1U];
  size_t h2 = hull[2U];
  bool ok = r == (size_t)3U && h0 == (size_t)0U && h1 == (size_t)1U && h2 == (size_t)3U;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  KRML_HOST_FREE(vh);
  return ok;
}

bool CLRS_Ch33_JarvisMarch_ImplTest_test_find_leftmost(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)2;
  size_t r = find_leftmost(xs, ys, (size_t)3U);
  bool ok = r == (size_t)0U;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  return ok;
}

bool CLRS_Ch33_JarvisMarch_ImplTest_test_find_next(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)2;
  size_t r0 = find_next(xs, ys, (size_t)3U, (size_t)0U);
  size_t r1 = find_next(xs, ys, (size_t)3U, (size_t)1U);
  size_t r2 = find_next(xs, ys, (size_t)3U, (size_t)2U);
  bool ok = r0 == (size_t)1U && r1 == (size_t)2U && r2 == (size_t)0U;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  return ok;
}

bool CLRS_Ch33_JarvisMarch_ImplTest_test_jarvis_march(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)2;
  size_t h = jarvis_march(xs, ys, (size_t)3U);
  bool ok = h == (size_t)3U;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  return ok;
}

bool CLRS_Ch33_JarvisMarch_ImplTest_test_jarvis_march_with_hull(void)
{
  krml_checked_int_t *vx = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *xs = vx;
  xs[0U] = (krml_checked_int_t)0;
  xs[1U] = (krml_checked_int_t)2;
  xs[2U] = (krml_checked_int_t)1;
  krml_checked_int_t *vy = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *ys = vy;
  ys[0U] = (krml_checked_int_t)0;
  ys[1U] = (krml_checked_int_t)0;
  ys[2U] = (krml_checked_int_t)2;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *vhull = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *hull = vhull;
  size_t h = jarvis_march_with_hull(xs, ys, (size_t)3U, hull);
  size_t h0 = hull[0U];
  size_t h1 = hull[1U];
  size_t h2 = hull[2U];
  bool ok = h == (size_t)3U && h0 == (size_t)0U && h1 == (size_t)1U && h2 == (size_t)2U;
  KRML_HOST_FREE(vx);
  KRML_HOST_FREE(vy);
  KRML_HOST_FREE(vhull);
  return ok;
}

