/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/ws2/FunFM/tools/krml/karamel/krml -skip-compilation -djson _output/ISMM_UnionFind_Impl.krml
  F* version: <unknown>
  KaRaMeL version: 03c78946
 */

#ifndef ISMM_UnionFind_Impl_H
#define ISMM_UnionFind_Impl_H

#include "krmllib.h"

typedef void *ISMM_UnionFind_Impl_well_formed;

typedef void *ISMM_UnionFind_Impl_is_root_at;

typedef void *ISMM_UnionFind_Impl_is_forest;


#define ISMM_UnionFind_Impl_H_DEFINED
#endif /* ISMM_UnionFind_Impl_H */
