/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-15 -add-include "krml/internal/compat.h" -bundle CLRS.Ch13.RBTree.Main=CLRS.Ch13.RBTree.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch13_RBTree_Main.krml _output/CLRS_Ch13_RBTree_ImplTest.krml _output/CLRS_Ch13_RBTree_Impl.krml _output/CLRS_Ch13_RBTree_Spec.krml _output/FStar_Pervasives_Native.krml _output/FStar_Pervasives.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/CLRS_Ch13_RBTree_Main.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

static bool uu___is_Red(CLRS_Ch13_RBTree_Spec_color projectee)
{
  switch (projectee)
  {
    case CLRS_Ch13_RBTree_Spec_Red:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

static bool uu___is_Black(CLRS_Ch13_RBTree_Spec_color projectee)
{
  switch (projectee)
  {
    case CLRS_Ch13_RBTree_Spec_Black:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

#define BC_LL 0
#define BC_LR 1
#define BC_RL 2
#define BC_RR 3
#define BC_None 4

typedef uint8_t balance_case;

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
new_node(
  krml_checked_int_t k,
  CLRS_Ch13_RBTree_Spec_color c,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  CLRS_Ch13_RBTree_Impl_rb_node *p = KRML_HOST_MALLOC(sizeof (CLRS_Ch13_RBTree_Impl_rb_node));
  if (p != NULL)
    p[0U] = ((CLRS_Ch13_RBTree_Impl_rb_node){ .key = k, .color = c, .left = l, .right = r });
  return
    (
      (FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_){
        .tag = FStar_Pervasives_Native_Some,
        .v = p
      }
    );
}

static balance_case
check_right_balance(FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r)
{
  if (r.tag == FStar_Pervasives_Native_None)
    return BC_None;
  else if (r.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *rp = r.v;
    CLRS_Ch13_RBTree_Impl_rb_node rn = *rp;
    if (uu___is_Red(rn.color))
      if (rn.left.tag == FStar_Pervasives_Native_None)
        if (rn.right.tag == FStar_Pervasives_Native_None)
          return BC_None;
        else if (rn.right.tag == FStar_Pervasives_Native_Some)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *rrp = rn.right.v;
          CLRS_Ch13_RBTree_Impl_rb_node rrn = *rrp;
          if (uu___is_Red(rrn.color))
            return BC_RR;
          else
            return BC_None;
        }
        else
        {
          KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
            __FILE__,
            __LINE__,
            "unreachable (pattern matches are exhaustive in F*)");
          KRML_HOST_EXIT(255U);
        }
      else if (rn.left.tag == FStar_Pervasives_Native_Some)
      {
        CLRS_Ch13_RBTree_Impl_rb_node *rlp = rn.left.v;
        CLRS_Ch13_RBTree_Impl_rb_node rln = *rlp;
        if (uu___is_Red(rln.color))
          return BC_RL;
        else if (rn.right.tag == FStar_Pervasives_Native_None)
          return BC_None;
        else if (rn.right.tag == FStar_Pervasives_Native_Some)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *rrp = rn.right.v;
          CLRS_Ch13_RBTree_Impl_rb_node rrn = *rrp;
          if (uu___is_Red(rrn.color))
            return BC_RR;
          else
            return BC_None;
        }
        else
        {
          KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
            __FILE__,
            __LINE__,
            "unreachable (pattern matches are exhaustive in F*)");
          KRML_HOST_EXIT(255U);
        }
      }
      else
      {
        KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
          __FILE__,
          __LINE__,
          "unreachable (pattern matches are exhaustive in F*)");
        KRML_HOST_EXIT(255U);
      }
    else
      return BC_None;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static balance_case
classify_runtime(
  CLRS_Ch13_RBTree_Spec_color c,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  if (uu___is_Red(c))
    return BC_None;
  else if (l.tag == FStar_Pervasives_Native_None)
    return check_right_balance(r);
  else if (l.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *lp = l.v;
    CLRS_Ch13_RBTree_Impl_rb_node ln = *lp;
    if (uu___is_Red(ln.color))
      if (ln.left.tag == FStar_Pervasives_Native_None)
        if (ln.right.tag == FStar_Pervasives_Native_None)
          return check_right_balance(r);
        else if (ln.right.tag == FStar_Pervasives_Native_Some)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *lrp = ln.right.v;
          CLRS_Ch13_RBTree_Impl_rb_node lrn = *lrp;
          if (uu___is_Red(lrn.color))
            return BC_LR;
          else
            return check_right_balance(r);
        }
        else
        {
          KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
            __FILE__,
            __LINE__,
            "unreachable (pattern matches are exhaustive in F*)");
          KRML_HOST_EXIT(255U);
        }
      else if (ln.left.tag == FStar_Pervasives_Native_Some)
      {
        CLRS_Ch13_RBTree_Impl_rb_node *llp = ln.left.v;
        CLRS_Ch13_RBTree_Impl_rb_node lln = *llp;
        if (uu___is_Red(lln.color))
          return BC_LL;
        else if (ln.right.tag == FStar_Pervasives_Native_None)
          return check_right_balance(r);
        else if (ln.right.tag == FStar_Pervasives_Native_Some)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *lrp = ln.right.v;
          CLRS_Ch13_RBTree_Impl_rb_node lrn = *lrp;
          if (uu___is_Red(lrn.color))
            return BC_LR;
          else
            return check_right_balance(r);
        }
        else
        {
          KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
            __FILE__,
            __LINE__,
            "unreachable (pattern matches are exhaustive in F*)");
          KRML_HOST_EXIT(255U);
        }
      }
      else
      {
        KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
          __FILE__,
          __LINE__,
          "unreachable (pattern matches are exhaustive in F*)");
        KRML_HOST_EXIT(255U);
      }
    else
      return check_right_balance(r);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
balance_ll(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  krml_checked_int_t v,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  CLRS_Ch13_RBTree_Impl_rb_node *lp;
  if (l.tag == FStar_Pervasives_Native_Some)
    lp = l.v;
  else
    lp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  CLRS_Ch13_RBTree_Impl_rb_node ln = *lp;
  CLRS_Ch13_RBTree_Impl_rb_node *llp;
  if (ln.left.tag == FStar_Pervasives_Native_Some)
    llp = ln.left.v;
  else
    llp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  (*llp).color = CLRS_Ch13_RBTree_Spec_Black;
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  right_black = new_node(v, CLRS_Ch13_RBTree_Spec_Black, ln.right, r);
  *lp =
    (
      (CLRS_Ch13_RBTree_Impl_rb_node){
        .key = ln.key,
        .color = CLRS_Ch13_RBTree_Spec_Red,
        .left = ln.left,
        .right = right_black
      }
    );
  return l;
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
balance_lr(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  krml_checked_int_t v,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  CLRS_Ch13_RBTree_Impl_rb_node *lp;
  if (l.tag == FStar_Pervasives_Native_Some)
    lp = l.v;
  else
    lp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  CLRS_Ch13_RBTree_Impl_rb_node ln = *lp;
  CLRS_Ch13_RBTree_Impl_rb_node *lrp;
  if (ln.right.tag == FStar_Pervasives_Native_Some)
    lrp = ln.right.v;
  else
    lrp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  CLRS_Ch13_RBTree_Impl_rb_node lrn = *lrp;
  *lp =
    (
      (CLRS_Ch13_RBTree_Impl_rb_node){
        .key = ln.key,
        .color = CLRS_Ch13_RBTree_Spec_Black,
        .left = ln.left,
        .right = lrn.left
      }
    );
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  right_black = new_node(v, CLRS_Ch13_RBTree_Spec_Black, lrn.right, r);
  *lrp =
    (
      (CLRS_Ch13_RBTree_Impl_rb_node){
        .key = lrn.key,
        .color = CLRS_Ch13_RBTree_Spec_Red,
        .left = l,
        .right = right_black
      }
    );
  return
    (
      (FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_){
        .tag = FStar_Pervasives_Native_Some,
        .v = lrp
      }
    );
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
balance_rl(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  krml_checked_int_t v,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  CLRS_Ch13_RBTree_Impl_rb_node *rp;
  if (r.tag == FStar_Pervasives_Native_Some)
    rp = r.v;
  else
    rp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  CLRS_Ch13_RBTree_Impl_rb_node rn = *rp;
  CLRS_Ch13_RBTree_Impl_rb_node *rlp;
  if (rn.left.tag == FStar_Pervasives_Native_Some)
    rlp = rn.left.v;
  else
    rlp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  CLRS_Ch13_RBTree_Impl_rb_node rln = *rlp;
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  left_black = new_node(v, CLRS_Ch13_RBTree_Spec_Black, l, rln.left);
  *rp =
    (
      (CLRS_Ch13_RBTree_Impl_rb_node){
        .key = rn.key,
        .color = CLRS_Ch13_RBTree_Spec_Black,
        .left = rln.right,
        .right = rn.right
      }
    );
  *rlp =
    (
      (CLRS_Ch13_RBTree_Impl_rb_node){
        .key = rln.key,
        .color = CLRS_Ch13_RBTree_Spec_Red,
        .left = left_black,
        .right = r
      }
    );
  return
    (
      (FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_){
        .tag = FStar_Pervasives_Native_Some,
        .v = rlp
      }
    );
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
balance_rr(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  krml_checked_int_t v,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  CLRS_Ch13_RBTree_Impl_rb_node *rp;
  if (r.tag == FStar_Pervasives_Native_Some)
    rp = r.v;
  else
    rp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  CLRS_Ch13_RBTree_Impl_rb_node rn = *rp;
  CLRS_Ch13_RBTree_Impl_rb_node *rrp;
  if (rn.right.tag == FStar_Pervasives_Native_Some)
    rrp = rn.right.v;
  else
    rrp =
      KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
        "unreachable (pattern matches are exhaustive in F*)");
  CLRS_Ch13_RBTree_Impl_rb_node rrn = *rrp;
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  left_black = new_node(v, CLRS_Ch13_RBTree_Spec_Black, l, rn.left);
  *rrp =
    (
      (CLRS_Ch13_RBTree_Impl_rb_node){
        .key = rrn.key,
        .color = CLRS_Ch13_RBTree_Spec_Black,
        .left = rrn.left,
        .right = rrn.right
      }
    );
  *rp =
    (
      (CLRS_Ch13_RBTree_Impl_rb_node){
        .key = rn.key,
        .color = CLRS_Ch13_RBTree_Spec_Red,
        .left = left_black,
        .right = rn.right
      }
    );
  return r;
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_balance(
  CLRS_Ch13_RBTree_Spec_color c,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  krml_checked_int_t v,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  balance_case bc = classify_runtime(c, l, r);
  switch (bc)
  {
    case BC_LL:
      {
        return balance_ll(l, v, r);
      }
    case BC_LR:
      {
        return balance_lr(l, v, r);
      }
    case BC_RL:
      {
        return balance_rl(l, v, r);
      }
    case BC_RR:
      {
        return balance_rr(l, v, r);
      }
    case BC_None:
      {
        return new_node(v, c, l, r);
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
}

FStar_Pervasives_Native_option__krml_checked_int_t
CLRS_Ch13_RBTree_Impl_rb_search(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return
      ((FStar_Pervasives_Native_option__krml_checked_int_t){ .tag = FStar_Pervasives_Native_None });
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *vl = tree.v;
    CLRS_Ch13_RBTree_Impl_rb_node node = *vl;
    if (Prims_op_LessThan(k, node.key))
      return CLRS_Ch13_RBTree_Impl_rb_search(node.left, k);
    else if (Prims_op_GreaterThan(k, node.key))
      return CLRS_Ch13_RBTree_Impl_rb_search(node.right, k);
    else
      return
        (
          (FStar_Pervasives_Native_option__krml_checked_int_t){
            .tag = FStar_Pervasives_Native_Some,
            .v = node.key
          }
        );
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
CLRS_Ch13_RBTree_Impl_rb_ins(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  if (tree.tag == FStar_Pervasives_Native_None)
  {
    FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
    left_leaf = { .tag = FStar_Pervasives_Native_None };
    FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
    right_leaf = { .tag = FStar_Pervasives_Native_None };
    return new_node(k, CLRS_Ch13_RBTree_Spec_Red, left_leaf, right_leaf);
  }
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *vl = tree.v;
    CLRS_Ch13_RBTree_Impl_rb_node node = *vl;
    if (Prims_op_LessThan(k, node.key))
    {
      FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
      new_left = CLRS_Ch13_RBTree_Impl_rb_ins(node.left, k);
      KRML_HOST_FREE(vl);
      return rb_balance(node.color, new_left, node.key, node.right);
    }
    else if (Prims_op_GreaterThan(k, node.key))
    {
      FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
      new_right = CLRS_Ch13_RBTree_Impl_rb_ins(node.right, k);
      KRML_HOST_FREE(vl);
      return rb_balance(node.color, node.left, node.key, new_right);
    }
    else
    {
      *vl = node;
      return tree;
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_make_black(FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return tree;
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *vl = tree.v;
    (*vl).color = CLRS_Ch13_RBTree_Spec_Black;
    return tree;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_insert(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  t = CLRS_Ch13_RBTree_Impl_rb_ins(tree, k);
  return rb_make_black(t);
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_redden(FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return tree;
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *p = tree.v;
    CLRS_Ch13_RBTree_Impl_rb_node node = *p;
    if (uu___is_Black(node.color))
    {
      *p =
        (
          (CLRS_Ch13_RBTree_Impl_rb_node){
            .key = node.key,
            .color = CLRS_Ch13_RBTree_Spec_Red,
            .left = node.left,
            .right = node.right
          }
        );
      return tree;
    }
    else
    {
      *p = node;
      return tree;
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static bool
is_color(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  CLRS_Ch13_RBTree_Spec_color c
)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return false;
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *p = tree.v;
    CLRS_Ch13_RBTree_Impl_rb_node node = *p;
    bool res = node.color == c;
    *p = node;
    return res;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_balL(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  krml_checked_int_t v,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  bool l_red = is_color(l, CLRS_Ch13_RBTree_Spec_Red);
  if (l_red)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *lp;
    if (l.tag == FStar_Pervasives_Native_Some)
      lp = l.v;
    else
      lp =
        KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
          "unreachable (pattern matches are exhaustive in F*)");
    (*lp).color = CLRS_Ch13_RBTree_Spec_Black;
    return new_node(v, CLRS_Ch13_RBTree_Spec_Red, l, r);
  }
  else
  {
    bool r_black = is_color(r, CLRS_Ch13_RBTree_Spec_Black);
    if (r_black)
    {
      CLRS_Ch13_RBTree_Impl_rb_node *rp;
      if (r.tag == FStar_Pervasives_Native_Some)
        rp = r.v;
      else
        rp =
          KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
            "unreachable (pattern matches are exhaustive in F*)");
      (*rp).color = CLRS_Ch13_RBTree_Spec_Red;
      return rb_balance(CLRS_Ch13_RBTree_Spec_Black, l, v, r);
    }
    else
    {
      bool r_red = is_color(r, CLRS_Ch13_RBTree_Spec_Red);
      if (r_red)
      {
        CLRS_Ch13_RBTree_Impl_rb_node *rp;
        if (r.tag == FStar_Pervasives_Native_Some)
          rp = r.v;
        else
          rp =
            KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
              "unreachable (pattern matches are exhaustive in F*)");
        CLRS_Ch13_RBTree_Impl_rb_node rn = *rp;
        bool rl_black = is_color(rn.left, CLRS_Ch13_RBTree_Spec_Black);
        if (rl_black)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *rlp;
          if (rn.left.tag == FStar_Pervasives_Native_Some)
            rlp = rn.left.v;
          else
            rlp =
              KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
                "unreachable (pattern matches are exhaustive in F*)");
          CLRS_Ch13_RBTree_Impl_rb_node rln = *rlp;
          FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ rd = rb_redden(rn.right);
          FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
          right_balanced = rb_balance(CLRS_Ch13_RBTree_Spec_Black, rln.right, rn.key, rd);
          FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
          left_black = new_node(v, CLRS_Ch13_RBTree_Spec_Black, l, rln.left);
          KRML_HOST_FREE(rp);
          *rlp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = rln.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = left_black,
                .right = right_balanced
              }
            );
          return
            (
              (FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_){
                .tag = FStar_Pervasives_Native_Some,
                .v = rlp
              }
            );
        }
        else
        {
          *rp = rn;
          return new_node(v, CLRS_Ch13_RBTree_Spec_Black, l, r);
        }
      }
      else
        return new_node(v, CLRS_Ch13_RBTree_Spec_Black, l, r);
    }
  }
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_balR(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  krml_checked_int_t v,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  bool r_red = is_color(r, CLRS_Ch13_RBTree_Spec_Red);
  if (r_red)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *rp;
    if (r.tag == FStar_Pervasives_Native_Some)
      rp = r.v;
    else
      rp =
        KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
          "unreachable (pattern matches are exhaustive in F*)");
    (*rp).color = CLRS_Ch13_RBTree_Spec_Black;
    return new_node(v, CLRS_Ch13_RBTree_Spec_Red, l, r);
  }
  else
  {
    bool l_black = is_color(l, CLRS_Ch13_RBTree_Spec_Black);
    if (l_black)
    {
      CLRS_Ch13_RBTree_Impl_rb_node *lp;
      if (l.tag == FStar_Pervasives_Native_Some)
        lp = l.v;
      else
        lp =
          KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
            "unreachable (pattern matches are exhaustive in F*)");
      (*lp).color = CLRS_Ch13_RBTree_Spec_Red;
      return rb_balance(CLRS_Ch13_RBTree_Spec_Black, l, v, r);
    }
    else
    {
      bool l_red = is_color(l, CLRS_Ch13_RBTree_Spec_Red);
      if (l_red)
      {
        CLRS_Ch13_RBTree_Impl_rb_node *lp;
        if (l.tag == FStar_Pervasives_Native_Some)
          lp = l.v;
        else
          lp =
            KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
              "unreachable (pattern matches are exhaustive in F*)");
        CLRS_Ch13_RBTree_Impl_rb_node ln = *lp;
        bool lr_black = is_color(ln.right, CLRS_Ch13_RBTree_Spec_Black);
        if (lr_black)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *lrp;
          if (ln.right.tag == FStar_Pervasives_Native_Some)
            lrp = ln.right.v;
          else
            lrp =
              KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
                "unreachable (pattern matches are exhaustive in F*)");
          CLRS_Ch13_RBTree_Impl_rb_node lrn = *lrp;
          FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ la = rb_redden(ln.left);
          FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
          left_balanced = rb_balance(CLRS_Ch13_RBTree_Spec_Black, la, ln.key, lrn.left);
          FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
          right_black = new_node(v, CLRS_Ch13_RBTree_Spec_Black, lrn.right, r);
          KRML_HOST_FREE(lp);
          *lrp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = lrn.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = left_balanced,
                .right = right_black
              }
            );
          return
            (
              (FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_){
                .tag = FStar_Pervasives_Native_Some,
                .v = lrp
              }
            );
        }
        else
        {
          *lp = ln;
          return new_node(v, CLRS_Ch13_RBTree_Spec_Black, l, r);
        }
      }
      else
        return new_node(v, CLRS_Ch13_RBTree_Spec_Black, l, r);
    }
  }
}

FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
CLRS_Ch13_RBTree_Impl_rb_fuse(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ l,
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ r
)
{
  if (l.tag == FStar_Pervasives_Native_None)
    return r;
  else if (l.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *lp = l.v;
    if (r.tag == FStar_Pervasives_Native_None)
      return l;
    else if (r.tag == FStar_Pervasives_Native_Some)
    {
      CLRS_Ch13_RBTree_Impl_rb_node *rp = r.v;
      CLRS_Ch13_RBTree_Impl_rb_node ln = *lp;
      CLRS_Ch13_RBTree_Impl_rb_node rn = *rp;
      if (uu___is_Red(ln.color) && uu___is_Red(rn.color))
      {
        FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
        s = CLRS_Ch13_RBTree_Impl_rb_fuse(ln.right, rn.left);
        bool s_red = is_color(s, CLRS_Ch13_RBTree_Spec_Red);
        if (s_red)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *sp;
          if (s.tag == FStar_Pervasives_Native_Some)
            sp = s.v;
          else
            sp =
              KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
                "unreachable (pattern matches are exhaustive in F*)");
          CLRS_Ch13_RBTree_Impl_rb_node sn = *sp;
          *lp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = ln.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = ln.left,
                .right = sn.left
              }
            );
          *rp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = rn.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = sn.right,
                .right = rn.right
              }
            );
          *sp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = sn.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = l,
                .right = r
              }
            );
          return s;
        }
        else
        {
          *rp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = rn.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = s,
                .right = rn.right
              }
            );
          *lp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = ln.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = ln.left,
                .right = r
              }
            );
          return l;
        }
      }
      else if (uu___is_Black(ln.color) && uu___is_Black(rn.color))
      {
        FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
        s = CLRS_Ch13_RBTree_Impl_rb_fuse(ln.right, rn.left);
        bool s_red = is_color(s, CLRS_Ch13_RBTree_Spec_Red);
        if (s_red)
        {
          CLRS_Ch13_RBTree_Impl_rb_node *sp;
          if (s.tag == FStar_Pervasives_Native_Some)
            sp = s.v;
          else
            sp =
              KRML_EABORT(CLRS_Ch13_RBTree_Impl_rb_node *,
                "unreachable (pattern matches are exhaustive in F*)");
          CLRS_Ch13_RBTree_Impl_rb_node sn = *sp;
          *lp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = ln.key,
                .color = CLRS_Ch13_RBTree_Spec_Black,
                .left = ln.left,
                .right = sn.left
              }
            );
          *rp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = rn.key,
                .color = CLRS_Ch13_RBTree_Spec_Black,
                .left = sn.right,
                .right = rn.right
              }
            );
          *sp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = sn.key,
                .color = CLRS_Ch13_RBTree_Spec_Red,
                .left = l,
                .right = r
              }
            );
          return s;
        }
        else
        {
          *rp =
            (
              (CLRS_Ch13_RBTree_Impl_rb_node){
                .key = rn.key,
                .color = CLRS_Ch13_RBTree_Spec_Black,
                .left = s,
                .right = rn.right
              }
            );
          KRML_HOST_FREE(lp);
          return rb_balL(ln.left, ln.key, r);
        }
      }
      else if (uu___is_Red(ln.color))
      {
        *rp = rn;
        FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
        fused = CLRS_Ch13_RBTree_Impl_rb_fuse(ln.right, r);
        *lp =
          (
            (CLRS_Ch13_RBTree_Impl_rb_node){
              .key = ln.key,
              .color = CLRS_Ch13_RBTree_Spec_Red,
              .left = ln.left,
              .right = fused
            }
          );
        return l;
      }
      else
      {
        *lp = ln;
        FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
        fused = CLRS_Ch13_RBTree_Impl_rb_fuse(l, rn.left);
        *rp =
          (
            (CLRS_Ch13_RBTree_Impl_rb_node){
              .key = rn.key,
              .color = CLRS_Ch13_RBTree_Spec_Red,
              .left = fused,
              .right = rn.right
            }
          );
        return r;
      }
    }
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
CLRS_Ch13_RBTree_Impl_rb_del(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  if (tree.tag == FStar_Pervasives_Native_None)
    return tree;
  else if (tree.tag == FStar_Pervasives_Native_Some)
  {
    CLRS_Ch13_RBTree_Impl_rb_node *p = tree.v;
    CLRS_Ch13_RBTree_Impl_rb_node node = *p;
    if (Prims_op_LessThan(k, node.key))
    {
      bool l_was_black = is_color(node.left, CLRS_Ch13_RBTree_Spec_Black);
      FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
      new_left = CLRS_Ch13_RBTree_Impl_rb_del(node.left, k);
      if (l_was_black)
      {
        KRML_HOST_FREE(p);
        return rb_balL(new_left, node.key, node.right);
      }
      else
      {
        KRML_HOST_FREE(p);
        return new_node(node.key, CLRS_Ch13_RBTree_Spec_Red, new_left, node.right);
      }
    }
    else if (Prims_op_GreaterThan(k, node.key))
    {
      bool r_was_black = is_color(node.right, CLRS_Ch13_RBTree_Spec_Black);
      FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
      new_right = CLRS_Ch13_RBTree_Impl_rb_del(node.right, k);
      if (r_was_black)
      {
        KRML_HOST_FREE(p);
        return rb_balR(node.left, node.key, new_right);
      }
      else
      {
        KRML_HOST_FREE(p);
        return new_node(node.key, CLRS_Ch13_RBTree_Spec_Red, node.left, new_right);
      }
    }
    else
    {
      KRML_HOST_FREE(p);
      return CLRS_Ch13_RBTree_Impl_rb_fuse(node.left, node.right);
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_delete(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  t = CLRS_Ch13_RBTree_Impl_rb_del(tree, k);
  return rb_make_black(t);
}

void
CLRS_Ch13_RBTree_Impl_free_rbtree(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree
)
{
  if (!(tree.tag == FStar_Pervasives_Native_None))
    if (tree.tag == FStar_Pervasives_Native_Some)
    {
      CLRS_Ch13_RBTree_Impl_rb_node *p = tree.v;
      CLRS_Ch13_RBTree_Impl_rb_node node = *p;
      CLRS_Ch13_RBTree_Impl_free_rbtree(node.left);
      CLRS_Ch13_RBTree_Impl_free_rbtree(node.right);
      KRML_HOST_FREE(p);
    }
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ rb_new(void)
{
  return
    (
      (FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_){
        .tag = FStar_Pervasives_Native_None
      }
    );
}

static FStar_Pervasives_Native_option__krml_checked_int_t
rb_search_v(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  return CLRS_Ch13_RBTree_Impl_rb_search(tree, k);
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_insert_v(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  return rb_insert(tree, k);
}

static FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
rb_delete_v(
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree,
  krml_checked_int_t k
)
{
  return rb_delete(tree, k);
}

static void
free_valid_rbtree(FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree)
{
  CLRS_Ch13_RBTree_Impl_free_rbtree(tree);
}

typedef struct
__FStar_Pervasives_Native_option__krml_checked_int_t_FStar_Pervasives_Native_option__krml_checked_int_t_s
{
  FStar_Pervasives_Native_option__krml_checked_int_t fst;
  FStar_Pervasives_Native_option__krml_checked_int_t snd;
}
__FStar_Pervasives_Native_option__krml_checked_int_t_FStar_Pervasives_Native_option__krml_checked_int_t;

static bool test_rbtree_insert_search_delete(void)
{
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_ tree0 = rb_new();
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  tree1 = rb_insert_v(tree0, (krml_checked_int_t)3);
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  tree2 = rb_insert_v(tree1, (krml_checked_int_t)1);
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  tree3 = rb_insert_v(tree2, (krml_checked_int_t)2);
  FStar_Pervasives_Native_option__krml_checked_int_t
  r2 = rb_search_v(tree3, (krml_checked_int_t)2);
  __FStar_Pervasives_Native_option__krml_checked_int_t_FStar_Pervasives_Native_option__krml_checked_int_t
  scrut =
    { .fst = r2, .snd = { .tag = FStar_Pervasives_Native_Some, .v = (krml_checked_int_t)2 } };
  bool check1;
  if
  (
    scrut.fst.tag == FStar_Pervasives_Native_None && scrut.snd.tag == FStar_Pervasives_Native_None
  )
    check1 = true;
  else if
  (
    scrut.fst.tag == FStar_Pervasives_Native_Some && scrut.snd.tag == FStar_Pervasives_Native_Some
  )
  {
    krml_checked_int_t y = scrut.snd.v;
    krml_checked_int_t x = scrut.fst.v;
    check1 = x == y;
  }
  else
    check1 = false;
  FStar_Pervasives_Native_option__krml_checked_int_t
  r4 = rb_search_v(tree3, (krml_checked_int_t)4);
  __FStar_Pervasives_Native_option__krml_checked_int_t_FStar_Pervasives_Native_option__krml_checked_int_t
  scrut0 = { .fst = r4, .snd = { .tag = FStar_Pervasives_Native_None } };
  bool check2;
  if
  (
    scrut0.fst.tag == FStar_Pervasives_Native_None &&
      scrut0.snd.tag == FStar_Pervasives_Native_None
  )
    check2 = true;
  else if
  (
    scrut0.fst.tag == FStar_Pervasives_Native_Some &&
      scrut0.snd.tag == FStar_Pervasives_Native_Some
  )
  {
    krml_checked_int_t y = scrut0.snd.v;
    krml_checked_int_t x = scrut0.fst.v;
    check2 = x == y;
  }
  else
    check2 = false;
  FStar_Pervasives_Native_option___CLRS_Ch13_RBTree_Impl_rb_node_
  tree4 = rb_delete_v(tree3, (krml_checked_int_t)1);
  FStar_Pervasives_Native_option__krml_checked_int_t
  r1_after = rb_search_v(tree4, (krml_checked_int_t)1);
  __FStar_Pervasives_Native_option__krml_checked_int_t_FStar_Pervasives_Native_option__krml_checked_int_t
  scrut1 = { .fst = r1_after, .snd = { .tag = FStar_Pervasives_Native_None } };
  bool check3;
  if
  (
    scrut1.fst.tag == FStar_Pervasives_Native_None &&
      scrut1.snd.tag == FStar_Pervasives_Native_None
  )
    check3 = true;
  else if
  (
    scrut1.fst.tag == FStar_Pervasives_Native_Some &&
      scrut1.snd.tag == FStar_Pervasives_Native_Some
  )
  {
    krml_checked_int_t y = scrut1.snd.v;
    krml_checked_int_t x = scrut1.fst.v;
    check3 = x == y;
  }
  else
    check3 = false;
  FStar_Pervasives_Native_option__krml_checked_int_t
  r3_after = rb_search_v(tree4, (krml_checked_int_t)3);
  __FStar_Pervasives_Native_option__krml_checked_int_t_FStar_Pervasives_Native_option__krml_checked_int_t
  scrut2 =
    { .fst = r3_after, .snd = { .tag = FStar_Pervasives_Native_Some, .v = (krml_checked_int_t)3 } };
  bool check4;
  if
  (
    scrut2.fst.tag == FStar_Pervasives_Native_None &&
      scrut2.snd.tag == FStar_Pervasives_Native_None
  )
    check4 = true;
  else if
  (
    scrut2.fst.tag == FStar_Pervasives_Native_Some &&
      scrut2.snd.tag == FStar_Pervasives_Native_Some
  )
  {
    krml_checked_int_t y = scrut2.snd.v;
    krml_checked_int_t x = scrut2.fst.v;
    check4 = x == y;
  }
  else
    check4 = false;
  free_valid_rbtree(tree4);
  return check1 && check2 && check3 && check4;
}

bool CLRS_Ch13_RBTree_Main_main(void)
{
  return test_rbtree_insert_search_delete();
}

