/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-15 -add-include "krml/internal/compat.h" -bundle CLRS.Ch13.RBTree.Main=CLRS.Ch13.RBTree.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output _output/CLRS_Ch13_RBTree_Main.krml _output/CLRS_Ch13_RBTree_ImplTest.krml _output/CLRS_Ch13_RBTree_Impl.krml _output/CLRS_Ch13_RBTree_Spec.krml _output/FStar_Pervasives_Native.krml _output/FStar_Pervasives.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch13_RBTree_Main_H
#define CLRS_Ch13_RBTree_Main_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch13_RBTree_Main_main(void);


#define CLRS_Ch13_RBTree_Main_H_DEFINED
#endif /* CLRS_Ch13_RBTree_Main_H */
