/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch21.UnionFind.ImplTest=CLRS.Ch21.UnionFind.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims,C -tmpdir _output _output/CLRS_Ch21_UnionFind_ImplTest.krml _output/CLRS_Ch21_UnionFind_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch21_UnionFind_ImplTest.h"

static void make_set(size_t *parent, size_t *rank, size_t n)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t vi = i;
    parent[vi] = vi;
    rank[vi] = (size_t)0U;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
}

static void compress_path(size_t *parent, size_t x, size_t root, size_t n)
{
  size_t curr = x;
  size_t count = (size_t)0U;
  size_t vc0 = curr;
  size_t __anf00 = count;
  bool cond = !(vc0 == root) && __anf00 < n;
  while (cond)
  {
    size_t vc = curr;
    size_t par = parent[vc];
    parent[vc] = root;
    curr = par;
    size_t c = count;
    count = c + (size_t)1U;
    size_t vc0 = curr;
    size_t __anf0 = count;
    cond = !(vc0 == root) && __anf0 < n;
  }
  parent[x] = root;
}

static size_t find_root_imp(size_t *parent, size_t x)
{
  size_t curr = x;
  size_t bound = (size_t)0U;
  size_t p_init = parent[x];
  bool go = !(p_init == x);
  while (go)
  {
    size_t vc = curr;
    size_t p1 = parent[vc];
    curr = p1;
    size_t b = bound;
    bound = b + (size_t)1U;
    size_t p2 = parent[p1];
    go = !(p2 == p1);
  }
  return curr;
}

static size_t find_set(size_t *parent, size_t x, size_t n)
{
  size_t root = find_root_imp(parent, x);
  compress_path(parent, x, root, n);
  return root;
}

static void union0(size_t *parent, size_t *rank, size_t x, size_t y, size_t n)
{
  size_t root_x = find_set(parent, x, n);
  size_t root_y = find_set(parent, y, n);
  if (!(root_x == root_y))
  {
    size_t rank_x = rank[root_x];
    size_t rank_y = rank[root_y];
    if (rank_x < rank_y)
      parent[root_x] = root_y;
    else if (rank_x > rank_y)
      parent[root_y] = root_x;
    else
    {
      parent[root_y] = root_x;
      size_t new_rank = rank_x + (size_t)1U;
      rank[root_x] = new_rank;
    }
  }
}

bool CLRS_Ch21_UnionFind_ImplTest_sz_eq(size_t a, size_t b)
{
  return !(a < b || b < a);
}

bool CLRS_Ch21_UnionFind_ImplTest_test_union_find(void)
{
  size_t n = (size_t)3U;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *vp = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *parent = vp;
  KRML_CHECK_SIZE(sizeof (size_t), (size_t)3U);
  size_t *vr = KRML_HOST_CALLOC((size_t)3U, sizeof (size_t));
  size_t *rank = vr;
  make_set(parent, rank, n);
  size_t r0 = find_set(parent, (size_t)0U, n);
  size_t r1 = find_set(parent, (size_t)1U, n);
  size_t r2 = find_set(parent, (size_t)2U, n);
  bool
  pass1 =
    !(r0 < (size_t)0U || (size_t)0U < r0) && !(r1 < (size_t)1U || (size_t)1U < r1) &&
      !(r2 < (size_t)2U || (size_t)2U < r2);
  union0(parent, rank, (size_t)0U, (size_t)1U, n);
  size_t r0_ = find_set(parent, (size_t)0U, n);
  size_t r1_ = find_set(parent, (size_t)1U, n);
  size_t r2_ = find_set(parent, (size_t)2U, n);
  bool pass2 = !(r0_ < r1_ || r1_ < r0_) && !(r2_ < (size_t)2U || (size_t)2U < r2_);
  union0(parent, rank, (size_t)1U, (size_t)2U, n);
  size_t r0__ = find_set(parent, (size_t)0U, n);
  size_t r1__ = find_set(parent, (size_t)1U, n);
  size_t r2__ = find_set(parent, (size_t)2U, n);
  bool pass3 = !(r0__ < r1__ || r1__ < r0__) && !(r1__ < r2__ || r2__ < r1__);
  KRML_HOST_FREE(vp);
  KRML_HOST_FREE(vr);
  return pass1 && pass2 && pass3;
}

