/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch21.UnionFind.ImplTest=CLRS.Ch21.UnionFind.* -bundle FStar.*,Pulse.*,PulseCore.*,Prims,C -tmpdir _output _output/CLRS_Ch21_UnionFind_ImplTest.krml _output/CLRS_Ch21_UnionFind_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch21_UnionFind_ImplTest_H
#define CLRS_Ch21_UnionFind_ImplTest_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch21_UnionFind_ImplTest_sz_eq(size_t a, size_t b);

bool CLRS_Ch21_UnionFind_ImplTest_test_union_find(void);


#define CLRS_Ch21_UnionFind_ImplTest_H_DEFINED
#endif /* CLRS_Ch21_UnionFind_ImplTest_H */
