/* HANDWRITTEN FILE — This is the manually written test driver, */
/* not generated by F* + KaRaMeL.                               */

/*
  Test driver for CLRS Chapter 21 Disjoint Sets — C extraction test.

  Two layers of assurance:
  1. PROOF: Ghost Pulse assertions (erased at extraction) verify
     pure_find equivalences and disjoint-set invariants from the spec.
  2. RUNTIME: C-level checks below independently verify the concrete
     output values (find_set results, union merge/stability).
*/

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include "CLRS_Ch21_UnionFind_ImplTest.h"

int main(void) {
  printf("=== CLRS Ch21 Union-Find — Extracted tests ===\n\n");

  printf("--- Union-Find test (3-element forest) ---\n");
  if (!CLRS_Ch21_UnionFind_ImplTest_test_union_find()) {
    fprintf(stderr, "FAIL: Union-Find output mismatch\n");
    return 1;
  }
  printf("  PASS (proof: uf_inv verified; runtime: find/union checks passed)\n\n");

  printf("=== All ch21 tests passed ===\n");
  return 0;
}
