/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch09_PartialSelectionSort_Impl.h"

#include "Pulse_Lib_BoundedIntegers.h"

size_t
CLRS_Ch09_PartialSelectionSort_Impl_find_min_index_from(
  krml_checked_int_t *a,
  size_t start,
  size_t len
)
{
  size_t min_idx = start;
  size_t i = start + (size_t)1U;
  while (i < len)
  {
    size_t vi = i;
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less(a[vi], a[min_idx]))
      min_idx = vi;
    i = vi + (size_t)1U;
  }
  return min_idx;
}

krml_checked_int_t
CLRS_Ch09_PartialSelectionSort_Impl_select(krml_checked_int_t *a, size_t n, size_t k)
{
  size_t round = (size_t)0U;
  while (round < k)
  {
    size_t vround = round;
    size_t min_idx = CLRS_Ch09_PartialSelectionSort_Impl_find_min_index_from(a, vround, n);
    krml_checked_int_t val_round = a[vround];
    a[vround] = a[min_idx];
    a[min_idx] = val_round;
    round = vround + (size_t)1U;
  }
  return a[k - (size_t)1U];
}

