/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch09_PartialSelectionSort_Impl_H
#define CLRS_Ch09_PartialSelectionSort_Impl_H

#include "krmllib.h"

#include "krml/internal/compat.h"

typedef void *CLRS_Ch09_PartialSelectionSort_Impl_permutation;

typedef void *CLRS_Ch09_PartialSelectionSort_Impl_is_min_in_range;

typedef void *CLRS_Ch09_PartialSelectionSort_Impl_sorted_prefix;

typedef void *CLRS_Ch09_PartialSelectionSort_Impl_prefix_leq_suffix;

typedef void *CLRS_Ch09_PartialSelectionSort_Impl_complexity_bounded_select;

size_t
CLRS_Ch09_PartialSelectionSort_Impl_find_min_index_from(
  krml_checked_int_t *a,
  size_t start,
  size_t len
);

krml_checked_int_t
CLRS_Ch09_PartialSelectionSort_Impl_select(krml_checked_int_t *a, size_t n, size_t k);


#define CLRS_Ch09_PartialSelectionSort_Impl_H_DEFINED
#endif /* CLRS_Ch09_PartialSelectionSort_Impl_H */
