/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch09_Quickselect_Impl.h"

#include "Pulse_Lib_BoundedIntegers.h"

size_t
CLRS_Ch09_Quickselect_Impl_partition_in_range(krml_checked_int_t *a, size_t lo, size_t hi)
{
  size_t hi_m1 = hi - (size_t)1U;
  krml_checked_int_t pivot = a[hi_m1];
  size_t i_ref = lo;
  size_t j_ref = lo;
  while (j_ref < hi_m1)
  {
    size_t vj = j_ref;
    size_t vi = i_ref;
    krml_checked_int_t aj = a[vj];
    krml_checked_int_t ai = a[vi];
    bool should_swap = Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less_Equals(aj, pivot);
    j_ref = vj + (size_t)1U;
    krml_checked_int_t new_ai;
    if (should_swap)
      new_ai = aj;
    else
      new_ai = ai;
    krml_checked_int_t new_aj;
    if (should_swap)
      new_aj = ai;
    else
      new_aj = aj;
    a[vi] = new_ai;
    a[vj] = new_aj;
    if (should_swap)
      i_ref = vi + (size_t)1U;
  }
  size_t vi = i_ref;
  krml_checked_int_t ai = a[vi];
  a[vi] = pivot;
  a[hi_m1] = ai;
  return vi;
}

krml_checked_int_t
CLRS_Ch09_Quickselect_Impl_quickselect(krml_checked_int_t *a, size_t n, size_t k)
{
  size_t lo_ref = (size_t)0U;
  size_t hi_ref = n;
  bool go = n > (size_t)1U;
  while (go)
  {
    size_t vlo = lo_ref;
    size_t vhi = hi_ref;
    size_t p = CLRS_Ch09_Quickselect_Impl_partition_in_range(a, vlo, vhi);
    if (k < p)
    {
      hi_ref = p;
      go = p > vlo + (size_t)1U;
    }
    else if (p < k)
    {
      lo_ref = p + (size_t)1U;
      go = vhi > p + (size_t)1U + (size_t)1U;
    }
    else
    {
      lo_ref = k;
      hi_ref = k + (size_t)1U;
      go = false;
    }
  }
  return a[k];
}

