/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch09_Quickselect_Impl_H
#define CLRS_Ch09_Quickselect_Impl_H

#include "krmllib.h"

#include "krml/internal/compat.h"

typedef void *CLRS_Ch09_Quickselect_Impl_permutation;

typedef void *CLRS_Ch09_Quickselect_Impl_unchanged_outside;

typedef void *CLRS_Ch09_Quickselect_Impl_partition_ordered;

typedef void *CLRS_Ch09_Quickselect_Impl_complexity_bounded_quickselect;

size_t
CLRS_Ch09_Quickselect_Impl_partition_in_range(krml_checked_int_t *a, size_t lo, size_t hi);

krml_checked_int_t
CLRS_Ch09_Quickselect_Impl_quickselect(krml_checked_int_t *a, size_t n, size_t k);


#define CLRS_Ch09_Quickselect_Impl_H_DEFINED
#endif /* CLRS_Ch09_Quickselect_Impl_H */
