/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch09_SimultaneousMinMax_Spec_H
#define CLRS_Ch09_SimultaneousMinMax_Spec_H

#include "krmllib.h"

#include "krml/internal/compat.h"

typedef struct CLRS_Ch09_SimultaneousMinMax_Spec_minmax_result_s
{
  krml_checked_int_t min_val;
  krml_checked_int_t max_val;
}
CLRS_Ch09_SimultaneousMinMax_Spec_minmax_result;

typedef void *CLRS_Ch09_SimultaneousMinMax_Spec_complexity_bounded_minmax;

typedef void *CLRS_Ch09_SimultaneousMinMax_Spec_complexity_bounded_minmax_pairs;


#define CLRS_Ch09_SimultaneousMinMax_Spec_H_DEFINED
#endif /* CLRS_Ch09_SimultaneousMinMax_Spec_H */
