/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch09_SimultaneousMinMax_Impl.h"

#include "Pulse_Lib_BoundedIntegers.h"
#include "CLRS_Ch09_SimultaneousMinMax_Spec.h"

CLRS_Ch09_SimultaneousMinMax_Spec_minmax_result
CLRS_Ch09_SimultaneousMinMax_Impl_find_minmax(krml_checked_int_t *a, size_t len)
{
  krml_checked_int_t v0 = a[0U];
  krml_checked_int_t min = v0;
  krml_checked_int_t max = v0;
  size_t i = (size_t)1U;
  while (i < len)
  {
    size_t vi = i;
    krml_checked_int_t elem = a[vi];
    krml_checked_int_t vmax = max;
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less(elem, min))
      min = elem;
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater(elem, vmax))
      max = elem;
    i = vi + (size_t)1U;
  }
  return ((CLRS_Ch09_SimultaneousMinMax_Spec_minmax_result){ .min_val = min, .max_val = max });
}

CLRS_Ch09_SimultaneousMinMax_Spec_minmax_result
CLRS_Ch09_SimultaneousMinMax_Impl_find_minmax_pairs(krml_checked_int_t *a, size_t len)
{
  krml_checked_int_t v0 = a[0U];
  krml_checked_int_t min_ref = v0;
  krml_checked_int_t max_ref = v0;
  size_t i = (size_t)1U;
  if (len >= (size_t)2U)
  {
    krml_checked_int_t v1 = a[1U];
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less_Equals(v0, v1))
      max_ref = v1;
    else
      min_ref = v1;
    i = (size_t)2U;
  }
  while (i < len - (size_t)1U)
  {
    size_t vi = i;
    krml_checked_int_t a_i = a[vi];
    krml_checked_int_t a_next = a[vi + (size_t)1U];
    krml_checked_int_t vmin = min_ref;
    krml_checked_int_t vmax = max_ref;
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less_Equals(a_i, a_next))
    {
      if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less(a_i, vmin))
        min_ref = a_i;
      if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater(a_next, vmax))
        max_ref = a_next;
    }
    else
    {
      if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less(a_next, vmin))
        min_ref = a_next;
      if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater(a_i, vmax))
        max_ref = a_i;
    }
    i = vi + (size_t)2U;
  }
  size_t vi = i;
  if (vi < len)
  {
    krml_checked_int_t last = a[vi];
    krml_checked_int_t vmax = max_ref;
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less(last, min_ref))
      min_ref = last;
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater(last, vmax))
      max_ref = last;
  }
  return
    ((CLRS_Ch09_SimultaneousMinMax_Spec_minmax_result){ .min_val = min_ref, .max_val = max_ref });
}

