/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch09_PartialSelectionSort_ImplTest.h"

#include "CLRS_Ch09_PartialSelectionSort_Impl.h"
#include "internal/FStar_PulseCore_Prims_CLRS_Ch09_MinMax_Spec_CLRS_Ch09_PartialSelectionSort_Spec_CLRS_Ch09_Quickselect_Spec_CLRS_Common_Complexity.h"

bool CLRS_Ch09_PartialSelectionSort_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b)
{
  return !(Prims_op_LessThan(a, b) || Prims_op_LessThan(b, a));
}

bool CLRS_Ch09_PartialSelectionSort_ImplTest_test_select_k1(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)5;
  arr[1U] = (krml_checked_int_t)2;
  arr[2U] = (krml_checked_int_t)8;
  krml_checked_int_t
  result = CLRS_Ch09_PartialSelectionSort_Impl_select(arr, (size_t)3U, (size_t)1U);
  bool
  ok =
    !(Prims_op_LessThan(result, (krml_checked_int_t)2) ||
      Prims_op_LessThan((krml_checked_int_t)2,
        result));
  KRML_HOST_FREE(v);
  return ok;
}

bool CLRS_Ch09_PartialSelectionSort_ImplTest_test_select_k2(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)5;
  arr[1U] = (krml_checked_int_t)2;
  arr[2U] = (krml_checked_int_t)8;
  krml_checked_int_t
  result = CLRS_Ch09_PartialSelectionSort_Impl_select(arr, (size_t)3U, (size_t)2U);
  bool
  ok =
    !(Prims_op_LessThan(result, (krml_checked_int_t)5) ||
      Prims_op_LessThan((krml_checked_int_t)5,
        result));
  KRML_HOST_FREE(v);
  return ok;
}

bool CLRS_Ch09_PartialSelectionSort_ImplTest_test_select_k3(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)5;
  arr[1U] = (krml_checked_int_t)2;
  arr[2U] = (krml_checked_int_t)8;
  krml_checked_int_t
  result = CLRS_Ch09_PartialSelectionSort_Impl_select(arr, (size_t)3U, (size_t)3U);
  bool
  ok =
    !(Prims_op_LessThan(result, (krml_checked_int_t)8) ||
      Prims_op_LessThan((krml_checked_int_t)8,
        result));
  KRML_HOST_FREE(v);
  return ok;
}

