/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch09_MinMax_Impl.h"

#include "Pulse_Lib_BoundedIntegers.h"

krml_checked_int_t CLRS_Ch09_MinMax_Impl_find_minimum(krml_checked_int_t *a, size_t len)
{
  krml_checked_int_t min = a[0U];
  size_t i = (size_t)1U;
  while (i < len)
  {
    size_t vi = i;
    krml_checked_int_t curr = a[vi];
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Less(curr, min))
      min = curr;
    i = vi + (size_t)1U;
  }
  return min;
}

krml_checked_int_t CLRS_Ch09_MinMax_Impl_find_maximum(krml_checked_int_t *a, size_t len)
{
  krml_checked_int_t max = a[0U];
  size_t i = (size_t)1U;
  while (i < len)
  {
    size_t vi = i;
    krml_checked_int_t curr = a[vi];
    if (Pulse_Lib_BoundedIntegers_bounded_int_int.op_Greater(curr, max))
      max = curr;
    i = vi + (size_t)1U;
  }
  return max;
}

