/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "krmlinit.h"

#include "Pulse_Lib_BoundedIntegers.h"
#include "internal/FStar_PulseCore_Prims_CLRS_Ch09_MinMax_Spec_CLRS_Ch09_PartialSelectionSort_Spec_CLRS_Ch09_Quickselect_Spec_CLRS_Common_Complexity.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void)
{
  Pulse_Lib_BoundedIntegers_bounded_int_int =
    (
      (Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t){
        .op_Plus = (void *)0U,
        .op_Subtraction = (void *)0U,
        .op_Less = (void *)0U,
        .op_Less_Equals = (void *)0U,
        .op_Greater = (void *)0U,
        .op_Greater_Equals = (void *)0U,
        .op_Percent = (void *)0U,
        .op_Slash = (void *)0U
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_int_u32 =
    (
      (Pulse_Lib_BoundedIntegers_bounded_int__uint32_t){
        .op_Plus = (void *)0U,
        .op_Subtraction = (void *)0U,
        .op_Less = (void *)0U,
        .op_Less_Equals = (void *)0U,
        .op_Greater = (void *)0U,
        .op_Greater_Equals = (void *)0U,
        .op_Percent = (void *)0U,
        .op_Slash = (void *)0U
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_unsigned_u32 =
    (
      (Pulse_Lib_BoundedIntegers_bounded_unsigned__uint32_t){
        .base = {
          .op_Plus = (void *)0U, .op_Subtraction = (void *)0U, .op_Less = (void *)0U,
          .op_Less_Equals = (void *)0U, .op_Greater = (void *)0U, .op_Greater_Equals = (void *)0U,
          .op_Percent = (void *)0U, .op_Slash = (void *)0U
        },
        .max_bound = 0xffffffffU,
        .static_max_bound = true
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_int_u64 =
    (
      (Pulse_Lib_BoundedIntegers_bounded_int__uint64_t){
        .op_Plus = (void *)0U,
        .op_Subtraction = (void *)0U,
        .op_Less = (void *)0U,
        .op_Less_Equals = (void *)0U,
        .op_Greater = (void *)0U,
        .op_Greater_Equals = (void *)0U,
        .op_Percent = (void *)0U,
        .op_Slash = (void *)0U
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_unsigned_u64 =
    (
      (Pulse_Lib_BoundedIntegers_bounded_unsigned__uint64_t){
        .base = {
          .op_Plus = (void *)0U, .op_Subtraction = (void *)0U, .op_Less = (void *)0U,
          .op_Less_Equals = (void *)0U, .op_Greater = (void *)0U, .op_Greater_Equals = (void *)0U,
          .op_Percent = (void *)0U, .op_Slash = (void *)0U
        },
        .max_bound = 0xffffffffffffffffULL,
        .static_max_bound = true
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_int_nat =
    (
      (Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t){
        .op_Plus = (void *)0U,
        .op_Subtraction = (void *)0U,
        .op_Less = (void *)0U,
        .op_Less_Equals = (void *)0U,
        .op_Greater = (void *)0U,
        .op_Greater_Equals = (void *)0U,
        .op_Percent = (void *)0U,
        .op_Slash = (void *)0U
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_int_pos =
    (
      (Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t){
        .op_Plus = (void *)0U,
        .op_Subtraction = (void *)0U,
        .op_Less = (void *)0U,
        .op_Less_Equals = (void *)0U,
        .op_Greater = (void *)0U,
        .op_Greater_Equals = (void *)0U,
        .op_Percent = (void *)0U,
        .op_Slash = (void *)0U
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_int_size_t =
    (
      (Pulse_Lib_BoundedIntegers_bounded_int__size_t){
        .op_Plus = (void *)0U,
        .op_Subtraction = (void *)0U,
        .op_Less = (void *)0U,
        .op_Less_Equals = (void *)0U,
        .op_Greater = (void *)0U,
        .op_Greater_Equals = (void *)0U,
        .op_Percent = (void *)0U,
        .op_Slash = (void *)0U
      }
    );
  Pulse_Lib_BoundedIntegers_bounded_unsigned_size_t =
    (
      (Pulse_Lib_BoundedIntegers_bounded_unsigned__size_t){
        .base = {
          .op_Plus = (void *)0U, .op_Subtraction = (void *)0U, .op_Less = (void *)0U,
          .op_Less_Equals = (void *)0U, .op_Greater = (void *)0U, .op_Greater_Equals = (void *)0U,
          .op_Percent = (void *)0U, .op_Slash = (void *)0U
        },
        .max_bound = (size_t)0xffffU,
        .static_max_bound = false
      }
    );
}

