/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "Pulse_Lib_BoundedIntegers.h"

Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_int;

Pulse_Lib_BoundedIntegers_bounded_int__uint32_t Pulse_Lib_BoundedIntegers_bounded_int_u32;

Pulse_Lib_BoundedIntegers_bounded_unsigned__uint32_t
Pulse_Lib_BoundedIntegers_bounded_unsigned_u32;

Pulse_Lib_BoundedIntegers_bounded_int__uint64_t Pulse_Lib_BoundedIntegers_bounded_int_u64;

Pulse_Lib_BoundedIntegers_bounded_unsigned__uint64_t
Pulse_Lib_BoundedIntegers_bounded_unsigned_u64;

uint32_t Pulse_Lib_BoundedIntegers_add_u32(uint32_t x, uint32_t y)
{
  return x + y;
}

uint32_t Pulse_Lib_BoundedIntegers_sub_u32(uint32_t x, uint32_t y)
{
  return x - y;
}

krml_checked_int_t Pulse_Lib_BoundedIntegers_add_nat_1(krml_checked_int_t x)
{
  return Pulse_Lib_BoundedIntegers_bounded_int_int.op_Plus(x, (krml_checked_int_t)1);
}

krml_checked_int_t Pulse_Lib_BoundedIntegers_nat_as_int(krml_checked_int_t x)
{
  return x;
}

Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_nat;

krml_checked_int_t
Pulse_Lib_BoundedIntegers_add_nat(krml_checked_int_t x, krml_checked_int_t y)
{
  return Pulse_Lib_BoundedIntegers_bounded_int_nat.op_Plus(x, y);
}

krml_checked_int_t Pulse_Lib_BoundedIntegers_pos_as_int(krml_checked_int_t x)
{
  return x;
}

Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_pos;

Pulse_Lib_BoundedIntegers_bounded_int__size_t Pulse_Lib_BoundedIntegers_bounded_int_size_t;

Pulse_Lib_BoundedIntegers_bounded_unsigned__size_t
Pulse_Lib_BoundedIntegers_bounded_unsigned_size_t;

size_t Pulse_Lib_BoundedIntegers_size_t_plus_one(size_t x)
{
  return x + (size_t)1U;
}

