/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,PulseCore.*,Prims,CLRS.Ch09.MinMax.Spec,CLRS.Ch09.PartialSelectionSort.Spec,CLRS.Ch09.Quickselect.Spec,CLRS.Common.Complexity -faggressive-inlining -tmpdir _output _output/CLRS_Ch09_MinMax_Impl.krml _output/CLRS_Ch09_MinMax_ImplTest.krml _output/CLRS_Ch09_PartialSelectionSort_Impl.krml _output/CLRS_Ch09_PartialSelectionSort_ImplTest.krml _output/CLRS_Ch09_Quickselect_Impl.krml _output/CLRS_Ch09_Quickselect_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Impl.krml _output/CLRS_Ch09_SimultaneousMinMax_ImplTest.krml _output/CLRS_Ch09_SimultaneousMinMax_Spec.krml _output/Pulse_Lib_BoundedIntegers.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef Pulse_Lib_BoundedIntegers_H
#define Pulse_Lib_BoundedIntegers_H

#include "krmllib.h"

#include "krml/internal/compat.h"

typedef krml_checked_int_t Pulse_Lib_BoundedIntegers_fits_t;

typedef void *Pulse_Lib_BoundedIntegers_fits;

typedef struct Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t_s
{
  krml_checked_int_t (*op_Plus)(krml_checked_int_t x0, krml_checked_int_t x1);
  krml_checked_int_t (*op_Subtraction)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Less)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Less_Equals)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Greater)(krml_checked_int_t x0, krml_checked_int_t x1);
  bool (*op_Greater_Equals)(krml_checked_int_t x0, krml_checked_int_t x1);
  krml_checked_int_t (*op_Percent)(krml_checked_int_t x0, krml_checked_int_t x1);
  krml_checked_int_t (*op_Slash)(krml_checked_int_t x0, krml_checked_int_t x1);
}
Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t;

extern Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_int;

typedef void *Pulse_Lib_BoundedIntegers_ok;

typedef struct Pulse_Lib_BoundedIntegers_bounded_int__uint32_t_s
{
  uint32_t (*op_Plus)(uint32_t x0, uint32_t x1);
  uint32_t (*op_Subtraction)(uint32_t x0, uint32_t x1);
  bool (*op_Less)(uint32_t x0, uint32_t x1);
  bool (*op_Less_Equals)(uint32_t x0, uint32_t x1);
  bool (*op_Greater)(uint32_t x0, uint32_t x1);
  bool (*op_Greater_Equals)(uint32_t x0, uint32_t x1);
  uint32_t (*op_Percent)(uint32_t x0, uint32_t x1);
  uint32_t (*op_Slash)(uint32_t x0, uint32_t x1);
}
Pulse_Lib_BoundedIntegers_bounded_int__uint32_t;

extern Pulse_Lib_BoundedIntegers_bounded_int__uint32_t
Pulse_Lib_BoundedIntegers_bounded_int_u32;

typedef struct Pulse_Lib_BoundedIntegers_bounded_unsigned__uint32_t_s
{
  Pulse_Lib_BoundedIntegers_bounded_int__uint32_t base;
  uint32_t max_bound;
  bool static_max_bound;
}
Pulse_Lib_BoundedIntegers_bounded_unsigned__uint32_t;

extern Pulse_Lib_BoundedIntegers_bounded_unsigned__uint32_t
Pulse_Lib_BoundedIntegers_bounded_unsigned_u32;

typedef struct Pulse_Lib_BoundedIntegers_bounded_int__uint64_t_s
{
  uint64_t (*op_Plus)(uint64_t x0, uint64_t x1);
  uint64_t (*op_Subtraction)(uint64_t x0, uint64_t x1);
  bool (*op_Less)(uint64_t x0, uint64_t x1);
  bool (*op_Less_Equals)(uint64_t x0, uint64_t x1);
  bool (*op_Greater)(uint64_t x0, uint64_t x1);
  bool (*op_Greater_Equals)(uint64_t x0, uint64_t x1);
  uint64_t (*op_Percent)(uint64_t x0, uint64_t x1);
  uint64_t (*op_Slash)(uint64_t x0, uint64_t x1);
}
Pulse_Lib_BoundedIntegers_bounded_int__uint64_t;

extern Pulse_Lib_BoundedIntegers_bounded_int__uint64_t
Pulse_Lib_BoundedIntegers_bounded_int_u64;

typedef struct Pulse_Lib_BoundedIntegers_bounded_unsigned__uint64_t_s
{
  Pulse_Lib_BoundedIntegers_bounded_int__uint64_t base;
  uint64_t max_bound;
  bool static_max_bound;
}
Pulse_Lib_BoundedIntegers_bounded_unsigned__uint64_t;

extern Pulse_Lib_BoundedIntegers_bounded_unsigned__uint64_t
Pulse_Lib_BoundedIntegers_bounded_unsigned_u64;

uint32_t Pulse_Lib_BoundedIntegers_add_u32(uint32_t x, uint32_t y);

uint32_t Pulse_Lib_BoundedIntegers_sub_u32(uint32_t x, uint32_t y);

krml_checked_int_t Pulse_Lib_BoundedIntegers_add_nat_1(krml_checked_int_t x);

krml_checked_int_t Pulse_Lib_BoundedIntegers_nat_as_int(krml_checked_int_t x);

extern Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_nat;

krml_checked_int_t
Pulse_Lib_BoundedIntegers_add_nat(krml_checked_int_t x, krml_checked_int_t y);

krml_checked_int_t Pulse_Lib_BoundedIntegers_pos_as_int(krml_checked_int_t x);

extern Pulse_Lib_BoundedIntegers_bounded_int__krml_checked_int_t
Pulse_Lib_BoundedIntegers_bounded_int_pos;

typedef struct Pulse_Lib_BoundedIntegers_bounded_int__size_t_s
{
  size_t (*op_Plus)(size_t x0, size_t x1);
  size_t (*op_Subtraction)(size_t x0, size_t x1);
  bool (*op_Less)(size_t x0, size_t x1);
  bool (*op_Less_Equals)(size_t x0, size_t x1);
  bool (*op_Greater)(size_t x0, size_t x1);
  bool (*op_Greater_Equals)(size_t x0, size_t x1);
  size_t (*op_Percent)(size_t x0, size_t x1);
  size_t (*op_Slash)(size_t x0, size_t x1);
}
Pulse_Lib_BoundedIntegers_bounded_int__size_t;

extern Pulse_Lib_BoundedIntegers_bounded_int__size_t
Pulse_Lib_BoundedIntegers_bounded_int_size_t;

typedef struct Pulse_Lib_BoundedIntegers_bounded_unsigned__size_t_s
{
  Pulse_Lib_BoundedIntegers_bounded_int__size_t base;
  size_t max_bound;
  bool static_max_bound;
}
Pulse_Lib_BoundedIntegers_bounded_unsigned__size_t;

extern Pulse_Lib_BoundedIntegers_bounded_unsigned__size_t
Pulse_Lib_BoundedIntegers_bounded_unsigned_size_t;

size_t Pulse_Lib_BoundedIntegers_size_t_plus_one(size_t x);


#define Pulse_Lib_BoundedIntegers_H_DEFINED
#endif /* Pulse_Lib_BoundedIntegers_H */
