/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17-18 -add-include "krml/internal/compat.h" -bundle CLRS.Ch16.ActivitySelection.ImplTest=CLRS.Ch16.ActivitySelection.* -bundle CLRS.Ch16.Huffman.ImplTest=CLRS.Ch16.Huffman.*,Pulse.Lib.PriorityQueue,Pulse.Lib.ResizableVec,Pulse.Lib.TotalOrder,Pulse.Lib.Vec,Pulse.Lib.Box -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/c_extract _output/CLRS_Ch16_ActivitySelection_ImplTest.krml _output/CLRS_Ch16_ActivitySelection_Impl.krml _output/CLRS_Ch16_Huffman_ImplTest.krml _output/CLRS_Ch16_Huffman_Impl.krml _output/CLRS_Ch16_Huffman_Defs.krml _output/CLRS_Ch16_Huffman_PQForest.krml _output/Pulse_Lib_PriorityQueue.krml _output/Pulse_Lib_ResizableVec.krml _output/Pulse_Lib_TotalOrder.krml _output/Pulse_Lib_Vec.krml _output/Pulse_Lib_Box.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_CLRS_Ch16_Huffman_ImplTest_H
#define internal_CLRS_Ch16_Huffman_ImplTest_H

#include "krmllib.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"
#include "../CLRS_Ch16_Huffman_ImplTest.h"
#include "krml/internal/compat.h"
#include "fstar_support.h"

typedef struct CLRS_Ch16_Huffman_Defs_pq_entry_s
{
  krml_checked_int_t fst;
  size_t snd;
}
CLRS_Ch16_Huffman_Defs_pq_entry;

typedef struct CLRS_Ch16_Huffman_Defs_hnode_s CLRS_Ch16_Huffman_Defs_hnode;

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option___CLRS_Ch16_Huffman_Defs_hnode__tags;

typedef struct FStar_Pervasives_Native_option___CLRS_Ch16_Huffman_Defs_hnode__s
{
  FStar_Pervasives_Native_option___CLRS_Ch16_Huffman_Defs_hnode__tags tag;
  CLRS_Ch16_Huffman_Defs_hnode *v;
}
FStar_Pervasives_Native_option___CLRS_Ch16_Huffman_Defs_hnode_;

typedef struct CLRS_Ch16_Huffman_Defs_hnode_s
{
  krml_checked_int_t sym;
  krml_checked_int_t freq;
  FStar_Pervasives_Native_option___CLRS_Ch16_Huffman_Defs_hnode_ left;
  FStar_Pervasives_Native_option___CLRS_Ch16_Huffman_Defs_hnode_ right;
}
CLRS_Ch16_Huffman_Defs_hnode;

typedef struct FStar_Pervasives_Native_option___krml_checked_int_t___size_t__s
FStar_Pervasives_Native_option___krml_checked_int_t___size_t_;

typedef struct Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t__s
{
  FStar_Pervasives_Native_option___krml_checked_int_t___size_t_ **vec_box;
  size_t *size_box;
  size_t *cap_box;
}
Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_;

typedef struct FStar_Pervasives_Native_option___krml_checked_int_t___size_t__s
{
  FStar_Pervasives_Native_option___CLRS_Ch16_Huffman_Defs_hnode__tags tag;
  CLRS_Ch16_Huffman_Defs_pq_entry v;
}
FStar_Pervasives_Native_option___krml_checked_int_t___size_t_;

void
Pulse_Lib_PriorityQueue_sift_up___krml_checked_int_t___size_t_(
  FStar_Order_order
  (*uu___)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq,
  size_t idx
);

void
Pulse_Lib_PriorityQueue_sift_down___krml_checked_int_t___size_t_(
  FStar_Order_order
  (*uu___)(CLRS_Ch16_Huffman_Defs_pq_entry x0, CLRS_Ch16_Huffman_Defs_pq_entry x1),
  Pulse_Lib_ResizableVec_rvec_internal___krml_checked_int_t___size_t_ pq,
  size_t idx,
  size_t len
);


#define internal_CLRS_Ch16_Huffman_ImplTest_H_DEFINED
#endif /* internal_CLRS_Ch16_Huffman_ImplTest_H */
