/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17-18 -add-include "krml/internal/compat.h" -bundle CLRS.Ch16.ActivitySelection.ImplTest=CLRS.Ch16.ActivitySelection.* -bundle CLRS.Ch16.Huffman.ImplTest=CLRS.Ch16.Huffman.*,Pulse.Lib.PriorityQueue,Pulse.Lib.ResizableVec,Pulse.Lib.TotalOrder,Pulse.Lib.Vec,Pulse.Lib.Box -bundle FStar.*,Pulse.*,PulseCore.*,Prims -add-include "fstar_support.h" -tmpdir _output/c_extract _output/CLRS_Ch16_ActivitySelection_ImplTest.krml _output/CLRS_Ch16_ActivitySelection_Impl.krml _output/CLRS_Ch16_Huffman_ImplTest.krml _output/CLRS_Ch16_Huffman_Impl.krml _output/CLRS_Ch16_Huffman_Defs.krml _output/CLRS_Ch16_Huffman_PQForest.krml _output/Pulse_Lib_PriorityQueue.krml _output/Pulse_Lib_ResizableVec.krml _output/Pulse_Lib_TotalOrder.krml _output/Pulse_Lib_Vec.krml _output/Pulse_Lib_Box.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_PulseCore_Prims_H
#define internal_FStar_Pulse_PulseCore_Prims_H

#include "krmllib.h"

#include "krml/internal/compat.h"
#include "fstar_support.h"

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);

#define FStar_Order_Lt 0
#define FStar_Order_Eq 1
#define FStar_Order_Gt 2

typedef uint8_t FStar_Order_order;

bool FStar_Order_le(FStar_Order_order o);

bool FStar_Order_lt(FStar_Order_order o);


#define internal_FStar_Pulse_PulseCore_Prims_H_DEFINED
#endif /* internal_FStar_Pulse_PulseCore_Prims_H */
