/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch07_Quicksort_ImplTest.krml _output/CLRS_Ch07_Quicksort_Impl.krml _output/CLRS_Ch07_Partition_Impl.krml _output/CLRS_Ch07_Partition_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch07_Quicksort_ImplTest.h"

#include "CLRS_Ch07_Quicksort_Impl.h"

bool CLRS_Ch07_Quicksort_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b)
{
  return a == b;
}

bool CLRS_Ch07_Quicksort_ImplTest_test_quicksort_3(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  CLRS_Ch07_Quicksort_Impl_quicksort(arr, (size_t)3U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  bool
  ok = v0 == (krml_checked_int_t)1 && v1 == (krml_checked_int_t)2 && v2 == (krml_checked_int_t)3;
  KRML_HOST_FREE(v);
  return ok;
}

bool CLRS_Ch07_Quicksort_ImplTest_test_quicksort_with_complexity(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  CLRS_Ch07_Quicksort_Impl_quicksort_with_complexity(arr, (size_t)3U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  bool
  ok = v0 == (krml_checked_int_t)1 && v1 == (krml_checked_int_t)2 && v2 == (krml_checked_int_t)3;
  KRML_HOST_FREE(v);
  return ok;
}

bool CLRS_Ch07_Quicksort_ImplTest_test_quicksort_bounded(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  CLRS_Ch07_Quicksort_Impl_quicksort_bounded(arr, (krml_checked_int_t)0, (krml_checked_int_t)3);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  bool
  ok = v0 == (krml_checked_int_t)1 && v1 == (krml_checked_int_t)2 && v2 == (krml_checked_int_t)3;
  KRML_HOST_FREE(v);
  return ok;
}

