/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch07_Quicksort_ImplTest.krml _output/CLRS_Ch07_Quicksort_Impl.krml _output/CLRS_Ch07_Partition_Impl.krml _output/CLRS_Ch07_Partition_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch07_Quicksort_ImplTest_H
#define CLRS_Ch07_Quicksort_ImplTest_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch07_Quicksort_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b);

bool CLRS_Ch07_Quicksort_ImplTest_test_quicksort_3(void);

bool CLRS_Ch07_Quicksort_ImplTest_test_quicksort_with_complexity(void);

bool CLRS_Ch07_Quicksort_ImplTest_test_quicksort_bounded(void);


#define CLRS_Ch07_Quicksort_ImplTest_H_DEFINED
#endif /* CLRS_Ch07_Quicksort_ImplTest_H */
