/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch07_Quicksort_ImplTest.krml _output/CLRS_Ch07_Quicksort_Impl.krml _output/CLRS_Ch07_Partition_Impl.krml _output/CLRS_Ch07_Partition_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch07_Partition_Impl.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

static krml_checked_int_t op_Array_Access__krml_checked_int_t(krml_checked_int_t *a, size_t i)
{
  return a[i];
}

static void
op_Array_Assignment__krml_checked_int_t(krml_checked_int_t *a, size_t i, krml_checked_int_t v)
{
  a[i] = v;
}

static void swap(krml_checked_int_t *a, krml_checked_int_t i, krml_checked_int_t j)
{
  krml_checked_int_t vi = op_Array_Access__krml_checked_int_t(a, FStar_SizeT_uint_to_t(i));
  krml_checked_int_t vj = op_Array_Access__krml_checked_int_t(a, FStar_SizeT_uint_to_t(j));
  op_Array_Assignment__krml_checked_int_t(a, FStar_SizeT_uint_to_t(i), vj);
  op_Array_Assignment__krml_checked_int_t(a, FStar_SizeT_uint_to_t(j), vi);
}

static krml_checked_int_t
clrs_partition_with_ticks(krml_checked_int_t *a, krml_checked_int_t lo, krml_checked_int_t hi)
{
  krml_checked_int_t
  pivot =
    op_Array_Access__krml_checked_int_t(a,
      FStar_SizeT_uint_to_t(Prims_op_Subtraction(hi, (krml_checked_int_t)1)));
  krml_checked_int_t i_plus_1 = lo;
  krml_checked_int_t j = lo;
  krml_checked_int_t vj0 = j;
  bool cond = Prims_op_LessThan(vj0, Prims_op_Subtraction(hi, (krml_checked_int_t)1));
  while (cond)
  {
    krml_checked_int_t vj = j;
    krml_checked_int_t aj = op_Array_Access__krml_checked_int_t(a, FStar_SizeT_uint_to_t(vj));
    if (Prims_op_LessThanOrEqual(aj, pivot))
    {
      krml_checked_int_t vi_plus_1 = i_plus_1;
      swap(a, vi_plus_1, vj);
      i_plus_1 = Prims_op_Addition(vi_plus_1, (krml_checked_int_t)1);
      j = Prims_op_Addition(vj, (krml_checked_int_t)1);
    }
    else
      j = Prims_op_Addition(vj, (krml_checked_int_t)1);
    krml_checked_int_t vj0 = j;
    cond = Prims_op_LessThan(vj0, Prims_op_Subtraction(hi, (krml_checked_int_t)1));
  }
  krml_checked_int_t vi_plus_1 = i_plus_1;
  swap(a, vi_plus_1, Prims_op_Subtraction(hi, (krml_checked_int_t)1));
  return vi_plus_1;
}

krml_checked_int_t
CLRS_Ch07_Partition_Impl_clrs_partition_wrapper_with_ticks(
  krml_checked_int_t *a,
  krml_checked_int_t lo,
  krml_checked_int_t hi
)
{
  return clrs_partition_with_ticks(a, lo, hi);
}

