/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch07_Quicksort_ImplTest.krml _output/CLRS_Ch07_Quicksort_Impl.krml _output/CLRS_Ch07_Partition_Impl.krml _output/CLRS_Ch07_Partition_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch07_Partition_ImplTest.h"

#include "CLRS_Ch07_Partition_Impl.h"
#include "internal/FStar_Pulse_PulseCore_Prims.h"

bool CLRS_Ch07_Partition_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b)
{
  return a == b;
}

bool CLRS_Ch07_Partition_ImplTest_int_leq(krml_checked_int_t a, krml_checked_int_t b)
{
  return Prims_op_LessThanOrEqual(a, b);
}

bool CLRS_Ch07_Partition_ImplTest_test_partition_3(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  krml_checked_int_t
  p =
    CLRS_Ch07_Partition_Impl_clrs_partition_wrapper_with_ticks(arr,
      (krml_checked_int_t)0,
      (krml_checked_int_t)3);
  KRML_MAYBE_UNUSED_VAR(p);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  bool
  ok =
    Prims_op_LessThanOrEqual((krml_checked_int_t)1, v0) &&
      Prims_op_LessThanOrEqual(v0,
        (krml_checked_int_t)3)
    &&
      Prims_op_LessThanOrEqual((krml_checked_int_t)1, v1) &&
        Prims_op_LessThanOrEqual(v1,
          (krml_checked_int_t)3)
    &&
      Prims_op_LessThanOrEqual((krml_checked_int_t)1, v2) &&
        Prims_op_LessThanOrEqual(v2,
          (krml_checked_int_t)3);
  KRML_HOST_FREE(v);
  return ok;
}

