/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch07_Quicksort_ImplTest.krml _output/CLRS_Ch07_Quicksort_Impl.krml _output/CLRS_Ch07_Partition_Impl.krml _output/CLRS_Ch07_Partition_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch07_Partition_Impl_H
#define CLRS_Ch07_Partition_Impl_H

#include "krmllib.h"

#include "krml/internal/compat.h"

krml_checked_int_t
CLRS_Ch07_Partition_Impl_clrs_partition_wrapper_with_ticks(
  krml_checked_int_t *a,
  krml_checked_int_t lo,
  krml_checked_int_t hi
);


#define CLRS_Ch07_Partition_Impl_H_DEFINED
#endif /* CLRS_Ch07_Partition_Impl_H */
