/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch07_Quicksort_ImplTest.krml _output/CLRS_Ch07_Quicksort_Impl.krml _output/CLRS_Ch07_Partition_Impl.krml _output/CLRS_Ch07_Partition_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/CLRS_Ch07_Quicksort_Impl.h"

#include "CLRS_Ch07_Partition_Impl.h"
#include "internal/FStar_Pulse_PulseCore_Prims.h"

void
CLRS_Ch07_Quicksort_Impl_clrs_quicksort_with_ticks(
  krml_checked_int_t *a,
  krml_checked_int_t lo,
  krml_checked_int_t hi
)
{
  if (Prims_op_LessThan(lo, hi))
  {
    krml_checked_int_t p = CLRS_Ch07_Partition_Impl_clrs_partition_wrapper_with_ticks(a, lo, hi);
    CLRS_Ch07_Quicksort_Impl_clrs_quicksort_with_ticks(a, lo, p);
    CLRS_Ch07_Quicksort_Impl_clrs_quicksort_with_ticks(a,
      Prims_op_Addition(p, (krml_checked_int_t)1),
      hi);
  }
}

static void clrs_quicksort(krml_checked_int_t *a, krml_checked_int_t lo, krml_checked_int_t hi)
{
  CLRS_Ch07_Quicksort_Impl_clrs_quicksort_with_ticks(a, lo, hi);
}

void CLRS_Ch07_Quicksort_Impl_quicksort_with_complexity(krml_checked_int_t *a, size_t len)
{
  if (len > (size_t)1U)
    CLRS_Ch07_Quicksort_Impl_clrs_quicksort_with_ticks(a,
      (krml_checked_int_t)0,
      FStar_SizeT_v(len));
}

void CLRS_Ch07_Quicksort_Impl_quicksort(krml_checked_int_t *a, size_t len)
{
  if (len > (size_t)1U)
    clrs_quicksort(a, (krml_checked_int_t)0, FStar_SizeT_v(len));
}

void
CLRS_Ch07_Quicksort_Impl_quicksort_bounded(
  krml_checked_int_t *a,
  krml_checked_int_t lo,
  krml_checked_int_t hi
)
{
  clrs_quicksort(a, lo, hi);
}

