/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch26.MaxFlow.ImplTest=CLRS.Ch26.MaxFlow.* -tmpdir _output _output/CLRS_Ch26_MaxFlow_ImplTest.krml _output/CLRS_Ch26_MaxFlow_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef CLRS_Ch26_MaxFlow_ImplTest_H
#define CLRS_Ch26_MaxFlow_ImplTest_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch26_MaxFlow_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b);

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_completeness(void);

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_disconnected_completeness(void);

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_3v(void);

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_diamond(void);

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_bottleneck(void);


#define CLRS_Ch26_MaxFlow_ImplTest_H_DEFINED
#endif /* CLRS_Ch26_MaxFlow_ImplTest_H */
