/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch26.MaxFlow.ImplTest=CLRS.Ch26.MaxFlow.* -tmpdir _output _output/CLRS_Ch26_MaxFlow_ImplTest.krml _output/CLRS_Ch26_MaxFlow_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch26_MaxFlow_ImplTest.h"

#include "internal/Prims.h"

static krml_checked_int_t int_max = (krml_checked_int_t)2147483647;

static void
bfs_init(
  krml_checked_int_t *color,
  krml_checked_int_t *pred,
  krml_checked_int_t *dist,
  size_t n,
  size_t source
)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t vi = i;
    color[vi] = (krml_checked_int_t)0;
    pred[vi] = (krml_checked_int_t)-1;
    dist[vi] = (krml_checked_int_t)-1;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
  color[source] = (krml_checked_int_t)1;
  dist[source] = (krml_checked_int_t)0;
}

static void
maybe_discover(
  krml_checked_int_t *capacity,
  krml_checked_int_t *flow,
  krml_checked_int_t *color,
  krml_checked_int_t *pred,
  krml_checked_int_t *dist,
  size_t *queue,
  size_t n,
  size_t u,
  size_t vv,
  size_t *q_tail
)
{
  size_t vt = *q_tail;
  krml_checked_int_t cv = color[vv];
  size_t idx_fwd = u * n + vv;
  size_t idx_bwd = vv * n + u;
  krml_checked_int_t cap_val = capacity[idx_fwd];
  krml_checked_int_t flow_fwd = flow[idx_fwd];
  krml_checked_int_t flow_bwd = flow[idx_bwd];
  krml_checked_int_t res_fwd = Prims_op_Subtraction(cap_val, flow_fwd);
  if
  (
    cv == (krml_checked_int_t)0 &&
      (Prims_op_GreaterThan(res_fwd, (krml_checked_int_t)0) ||
        Prims_op_GreaterThan(flow_bwd,
          (krml_checked_int_t)0))
  )
  {
    krml_checked_int_t du = dist[u];
    color[vv] = (krml_checked_int_t)1;
    pred[vv] = FStar_SizeT_v(u);
    dist[vv] = Prims_op_Addition(du, (krml_checked_int_t)1);
    queue[vt] = vv;
    *q_tail = vt + (size_t)1U;
  }
}

static void
bfs_explore_neighbors(
  krml_checked_int_t *capacity,
  krml_checked_int_t *flow,
  krml_checked_int_t *color,
  krml_checked_int_t *pred,
  krml_checked_int_t *dist,
  size_t *queue,
  size_t n,
  size_t u,
  size_t *q_tail
)
{
  size_t v = (size_t)0U;
  size_t __anf0 = v;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t vv = v;
    maybe_discover(capacity, flow, color, pred, dist, queue, n, u, vv, q_tail);
    v = vv + (size_t)1U;
    size_t __anf0 = v;
    cond = __anf0 < n;
  }
}

static bool
bfs_residual(
  krml_checked_int_t *capacity,
  krml_checked_int_t *flow,
  krml_checked_int_t *color,
  krml_checked_int_t *pred,
  krml_checked_int_t *dist,
  size_t *queue,
  size_t n,
  size_t source,
  size_t sink
)
{
  bfs_init(color, pred, dist, n, source);
  queue[0U] = source;
  size_t q_head = (size_t)0U;
  size_t q_tail = (size_t)1U;
  size_t vh0 = q_head;
  size_t vt0 = q_tail;
  bool cond = vh0 < vt0;
  while (cond)
  {
    size_t vh = q_head;
    size_t u = queue[vh];
    q_head = vh + (size_t)1U;
    bfs_explore_neighbors(capacity, flow, color, pred, dist, queue, n, u, &q_tail);
    color[u] = (krml_checked_int_t)2;
    size_t vh0 = q_head;
    size_t vt = q_tail;
    cond = vh0 < vt;
  }
  krml_checked_int_t sink_color = color[sink];
  return sink_color != (krml_checked_int_t)0;
}

static krml_checked_int_t
find_bottleneck_imp(
  krml_checked_int_t *capacity,
  krml_checked_int_t *flow,
  krml_checked_int_t *pred,
  size_t n,
  size_t source,
  size_t sink
)
{
  size_t current = sink;
  krml_checked_int_t bottleneck = int_max;
  size_t c = current;
  bool cond = !(c == source);
  while (cond)
  {
    size_t vc = current;
    krml_checked_int_t u_int = pred[vc];
    if (Prims_op_GreaterThanOrEqual(u_int, (krml_checked_int_t)0))
    {
      size_t u = FStar_SizeT_uint_to_t(u_int);
      size_t idx_fwd = u * n + vc;
      size_t idx_bwd = vc * n + u;
      krml_checked_int_t cap_val = capacity[idx_fwd];
      krml_checked_int_t flow_fwd = flow[idx_fwd];
      krml_checked_int_t flow_bwd = flow[idx_bwd];
      krml_checked_int_t res_fwd = Prims_op_Subtraction(cap_val, flow_fwd);
      krml_checked_int_t vbn = bottleneck;
      if (Prims_op_GreaterThan(res_fwd, (krml_checked_int_t)0))
      {
        if (Prims_op_LessThan(res_fwd, vbn))
          bottleneck = res_fwd;
      }
      else if
      (Prims_op_GreaterThan(flow_bwd, (krml_checked_int_t)0) && Prims_op_LessThan(flow_bwd, vbn))
        bottleneck = flow_bwd;
      current = u;
    }
    else
      current = source;
    size_t c = current;
    cond = !(c == source);
  }
  return bottleneck;
}

static void
augment_imp(
  krml_checked_int_t *capacity,
  krml_checked_int_t *flow,
  krml_checked_int_t *pred,
  size_t n,
  size_t source,
  size_t sink,
  krml_checked_int_t bn
)
{
  size_t current = sink;
  size_t c = current;
  bool cond = !(c == source);
  while (cond)
  {
    size_t vc = current;
    krml_checked_int_t u_int = pred[vc];
    if (Prims_op_GreaterThanOrEqual(u_int, (krml_checked_int_t)0))
    {
      size_t u = FStar_SizeT_uint_to_t(u_int);
      size_t idx_fwd = u * n + vc;
      size_t idx_bwd = vc * n + u;
      krml_checked_int_t cap_val = capacity[idx_fwd];
      krml_checked_int_t flow_fwd = flow[idx_fwd];
      if (Prims_op_GreaterThan(Prims_op_Subtraction(cap_val, flow_fwd), (krml_checked_int_t)0))
      {
        flow[idx_fwd] = Prims_op_Addition(flow_fwd, bn);
        current = u;
      }
      else
      {
        krml_checked_int_t flow_bwd = flow[idx_bwd];
        flow[idx_bwd] = Prims_op_Subtraction(flow_bwd, bn);
        current = u;
      }
    }
    else
      current = source;
    size_t c = current;
    cond = !(c == source);
  }
}

static bool check_valid_caps_fn(krml_checked_int_t *capacity, size_t nn)
{
  size_t i = (size_t)0U;
  bool result = true;
  size_t vi0 = i;
  bool vr0 = result;
  bool cond = vr0 && vi0 < nn;
  while (cond)
  {
    size_t vi = i;
    krml_checked_int_t c = capacity[vi];
    if (Prims_op_LessThan(c, (krml_checked_int_t)0))
      result = false;
    i = vi + (size_t)1U;
    size_t vi0 = i;
    bool vr = result;
    cond = vr && vi0 < nn;
  }
  return result;
}

static krml_checked_int_t compute_sum_out_fn(krml_checked_int_t *arr, size_t n, size_t v)
{
  krml_checked_int_t acc = (krml_checked_int_t)0;
  size_t j = (size_t)0U;
  size_t __anf00 = j;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t jv = j;
    size_t idx = v * n + jv;
    krml_checked_int_t fval = arr[idx];
    krml_checked_int_t __anf0 = acc;
    acc = Prims_op_Addition(__anf0, fval);
    j = jv + (size_t)1U;
    size_t __anf00 = j;
    cond = __anf00 < n;
  }
  return acc;
}

static krml_checked_int_t compute_sum_in_fn(krml_checked_int_t *arr, size_t n, size_t v)
{
  krml_checked_int_t acc = (krml_checked_int_t)0;
  size_t u = (size_t)0U;
  size_t __anf00 = u;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t uv = u;
    size_t idx = uv * n + v;
    krml_checked_int_t fval = arr[idx];
    krml_checked_int_t __anf0 = acc;
    acc = Prims_op_Addition(__anf0, fval);
    u = uv + (size_t)1U;
    size_t __anf00 = u;
    cond = __anf00 < n;
  }
  return acc;
}

static krml_checked_int_t
compute_flow_value_fn(krml_checked_int_t *flow, size_t n, size_t source)
{
  krml_checked_int_t sum_out = compute_sum_out_fn(flow, n, source);
  krml_checked_int_t sum_in = compute_sum_in_fn(flow, n, source);
  return Prims_op_Subtraction(sum_out, sum_in);
}

static void zero_init_flow(krml_checked_int_t *flow, size_t nn)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < nn;
  while (cond)
  {
    size_t vi = i;
    flow[vi] = (krml_checked_int_t)0;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < nn;
  }
}

static krml_checked_int_t
max_flow(
  krml_checked_int_t *capacity,
  krml_checked_int_t *flow,
  size_t n,
  size_t source,
  size_t sink
)
{
  size_t nn = n * n;
  zero_init_flow(flow, nn);
  krml_checked_int_t cap_sum = compute_sum_out_fn(capacity, n, source);
  KRML_MAYBE_UNUSED_VAR(cap_sum);
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), n);
  krml_checked_int_t *color_v = KRML_HOST_CALLOC(n, sizeof (krml_checked_int_t));
  krml_checked_int_t *color = color_v;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), n);
  krml_checked_int_t *pred_v = KRML_HOST_MALLOC(sizeof (krml_checked_int_t) * n);
  if (pred_v != NULL)
    for (uint32_t _i = 0U; _i < n; ++_i)
      pred_v[_i] = (krml_checked_int_t)-1;
  krml_checked_int_t *pred = pred_v;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), n);
  krml_checked_int_t *dist_v = KRML_HOST_MALLOC(sizeof (krml_checked_int_t) * n);
  if (dist_v != NULL)
    for (uint32_t _i = 0U; _i < n; ++_i)
      dist_v[_i] = (krml_checked_int_t)-1;
  krml_checked_int_t *dist = dist_v;
  KRML_CHECK_SIZE(sizeof (size_t), n);
  size_t *queue_v = KRML_HOST_CALLOC(n, sizeof (size_t));
  size_t *queue = queue_v;
  bool continue_loop = true;
  krml_checked_int_t iters = (krml_checked_int_t)0;
  krml_checked_int_t flow_val = (krml_checked_int_t)0;
  while (continue_loop)
  {
    krml_checked_int_t __anf0 = iters;
    iters = Prims_op_Addition(__anf0, (krml_checked_int_t)1);
    bool found = bfs_residual(capacity, flow, color, pred, dist, queue, n, source, sink);
    if (found)
    {
      krml_checked_int_t bn = find_bottleneck_imp(capacity, flow, pred, n, source, sink);
      augment_imp(capacity, flow, pred, n, source, sink, bn);
      krml_checked_int_t new_fv = compute_flow_value_fn(flow, n, source);
      flow_val = new_fv;
    }
    else
      continue_loop = false;
  }
  krml_checked_int_t result = flow_val;
  KRML_HOST_FREE(color_v);
  KRML_HOST_FREE(pred_v);
  KRML_HOST_FREE(dist_v);
  KRML_HOST_FREE(queue_v);
  return result;
}

bool CLRS_Ch26_MaxFlow_ImplTest_int_eq(krml_checked_int_t a, krml_checked_int_t b)
{
  return a == b;
}

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_completeness(void)
{
  size_t n = (size_t)2U;
  size_t nn = n * n;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *cv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *capacity = cv;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *fv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *flow = fv;
  capacity[1U] = (krml_checked_int_t)7;
  bool caps_ok = check_valid_caps_fn(capacity, nn);
  if (caps_ok)
  {
    krml_checked_int_t flow_val = max_flow(capacity, flow, n, (size_t)0U, (size_t)1U);
    krml_checked_int_t f00 = flow[0U];
    krml_checked_int_t f01 = flow[1U];
    krml_checked_int_t f10 = flow[2U];
    krml_checked_int_t f11 = flow[3U];
    bool
    pass =
      f01 == (krml_checked_int_t)7 && f00 == (krml_checked_int_t)0 && f10 == (krml_checked_int_t)0
      && f11 == (krml_checked_int_t)0
      && flow_val == (krml_checked_int_t)7;
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return pass;
  }
  else
  {
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return false;
  }
}

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_disconnected_completeness(void)
{
  size_t n = (size_t)2U;
  size_t nn = n * n;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *cv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *capacity = cv;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *fv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *flow = fv;
  bool caps_ok = check_valid_caps_fn(capacity, nn);
  if (caps_ok)
  {
    krml_checked_int_t flow_val = max_flow(capacity, flow, n, (size_t)0U, (size_t)1U);
    krml_checked_int_t f00 = flow[0U];
    krml_checked_int_t f01 = flow[1U];
    krml_checked_int_t f10 = flow[2U];
    krml_checked_int_t f11 = flow[3U];
    bool
    pass =
      f00 == (krml_checked_int_t)0 && f01 == (krml_checked_int_t)0 && f10 == (krml_checked_int_t)0
      && f11 == (krml_checked_int_t)0
      && flow_val == (krml_checked_int_t)0;
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return pass;
  }
  else
  {
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return false;
  }
}

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_3v(void)
{
  size_t n = (size_t)3U;
  size_t nn = n * n;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *cv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *capacity = cv;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *fv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *flow = fv;
  capacity[1U] = (krml_checked_int_t)10;
  capacity[n + (size_t)2U] = (krml_checked_int_t)5;
  capacity[2U] = (krml_checked_int_t)15;
  bool caps_ok = check_valid_caps_fn(capacity, nn);
  if (caps_ok)
  {
    krml_checked_int_t flow_val = max_flow(capacity, flow, n, (size_t)0U, (size_t)2U);
    bool pass = flow_val == (krml_checked_int_t)20;
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return pass;
  }
  else
  {
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return false;
  }
}

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_diamond(void)
{
  size_t n = (size_t)4U;
  size_t nn = n * n;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *cv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *capacity = cv;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *fv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *flow = fv;
  capacity[1U] = (krml_checked_int_t)10;
  capacity[2U] = (krml_checked_int_t)10;
  capacity[n + (size_t)3U] = (krml_checked_int_t)10;
  capacity[(size_t)2U * n + (size_t)3U] = (krml_checked_int_t)10;
  bool caps_ok = check_valid_caps_fn(capacity, nn);
  if (caps_ok)
  {
    krml_checked_int_t flow_val = max_flow(capacity, flow, n, (size_t)0U, (size_t)3U);
    bool pass = flow_val == (krml_checked_int_t)20;
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return pass;
  }
  else
  {
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return false;
  }
}

bool CLRS_Ch26_MaxFlow_ImplTest_test_max_flow_bottleneck(void)
{
  size_t n = (size_t)3U;
  size_t nn = n * n;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *cv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *capacity = cv;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), nn);
  krml_checked_int_t *fv = KRML_HOST_CALLOC(nn, sizeof (krml_checked_int_t));
  krml_checked_int_t *flow = fv;
  capacity[1U] = (krml_checked_int_t)100;
  capacity[n + (size_t)2U] = (krml_checked_int_t)1;
  bool caps_ok = check_valid_caps_fn(capacity, nn);
  if (caps_ok)
  {
    krml_checked_int_t flow_val = max_flow(capacity, flow, n, (size_t)0U, (size_t)2U);
    bool pass = flow_val == (krml_checked_int_t)1;
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return pass;
  }
  else
  {
    KRML_HOST_FREE(cv);
    KRML_HOST_FREE(fv);
    return false;
  }
}

