/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch12.BST.TestMain=CLRS.Ch12.BST.ImplTest,CLRS.Ch12.BST.Impl -bundle CLRS.Ch12.BSTArray.TestMain=CLRS.Ch12.BSTArray.ImplTest,CLRS.Ch12.BSTArray.Impl -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch12_BST_TestMain.krml _output/CLRS_Ch12_BST_ImplTest.krml _output/CLRS_Ch12_BST_Impl.krml _output/FStar_Pervasives.krml _output/FStar_Pervasives_Native.krml _output/CLRS_Ch12_BSTArray_TestMain.krml _output/CLRS_Ch12_BSTArray_ImplTest.krml _output/CLRS_Ch12_BSTArray_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_CLRS_Ch12_BST_TestMain_H
#define internal_CLRS_Ch12_BST_TestMain_H

#include "krmllib.h"

#include "../CLRS_Ch12_BST_TestMain.h"
#include "krml/internal/compat.h"

typedef struct CLRS_Ch12_BST_Impl_bst_node_s CLRS_Ch12_BST_Impl_bst_node;

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node__tags;

typedef struct FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node__s
{
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node__tags tag;
  CLRS_Ch12_BST_Impl_bst_node *v;
}
FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_;

typedef struct CLRS_Ch12_BST_Impl_bst_node_s
{
  krml_checked_int_t key;
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ left;
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ right;
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ p;
}
CLRS_Ch12_BST_Impl_bst_node;

bool
CLRS_Ch12_BST_Impl_tree_search(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  krml_checked_int_t k
);

krml_checked_int_t
CLRS_Ch12_BST_Impl_tree_minimum(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  CLRS_Ch12_BST_Impl_bst_node *bp
);

krml_checked_int_t
CLRS_Ch12_BST_Impl_tree_maximum(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  CLRS_Ch12_BST_Impl_bst_node *bp
);

FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
CLRS_Ch12_BST_Impl_tree_insert(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  krml_checked_int_t k,
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ parent
);

FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_
CLRS_Ch12_BST_Impl_tree_delete(
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree,
  krml_checked_int_t k,
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ parent
);

void
CLRS_Ch12_BST_Impl_free_bst(FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node_ tree);


#define internal_CLRS_Ch12_BST_TestMain_H_DEFINED
#endif /* internal_CLRS_Ch12_BST_TestMain_H */
