/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch12.BST.TestMain=CLRS.Ch12.BST.ImplTest,CLRS.Ch12.BST.Impl -bundle CLRS.Ch12.BSTArray.TestMain=CLRS.Ch12.BSTArray.ImplTest,CLRS.Ch12.BSTArray.Impl -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/c _output/CLRS_Ch12_BST_TestMain.krml _output/CLRS_Ch12_BST_ImplTest.krml _output/CLRS_Ch12_BST_Impl.krml _output/FStar_Pervasives.krml _output/FStar_Pervasives_Native.krml _output/CLRS_Ch12_BSTArray_TestMain.krml _output/CLRS_Ch12_BSTArray_ImplTest.krml _output/CLRS_Ch12_BSTArray_Impl.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_CLRS_Ch12_BSTArray_TestMain_H
#define internal_CLRS_Ch12_BSTArray_TestMain_H

#include "krmllib.h"

#include "internal/CLRS_Ch12_BST_TestMain.h"
#include "../CLRS_Ch12_BSTArray_TestMain.h"
#include "krml/internal/compat.h"

typedef struct FStar_Pervasives_Native_option__size_t_s
{
  FStar_Pervasives_Native_option___CLRS_Ch12_BST_Impl_bst_node__tags tag;
  size_t v;
}
FStar_Pervasives_Native_option__size_t;


#define internal_CLRS_Ch12_BSTArray_TestMain_H_DEFINED
#endif /* internal_CLRS_Ch12_BSTArray_TestMain_H */
