/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-15 -add-include "krml/internal/compat.h" -bundle CLRS.Ch11.HashTable.ImplTest=CLRS.Ch11.HashTable.Impl[rename=CLRS_Ch11_HashTable_ImplTest] -bundle FStar.*,Pulse.*,Prims,PulseCore.*,LowStar.* -add-include "fstar_support.h" -tmpdir _output _output/CLRS_Ch11_HashTable_Impl.krml _output/CLRS_Ch11_HashTable_ImplTest.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_Prims_PulseCore_LowStar_H
#define internal_FStar_Pulse_Prims_PulseCore_LowStar_H

#include "krmllib.h"

#include "krml/internal/compat.h"
#include "fstar_support.h"

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Modulus(krml_checked_int_t x, krml_checked_int_t y);


#define internal_FStar_Pulse_Prims_PulseCore_LowStar_H_DEFINED
#endif /* internal_FStar_Pulse_Prims_PulseCore_LowStar_H */
