/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch02.InsertionSort.ImplTest+CLRS.Ch02.InsertionSort.Impl=CLRS.Ch02.InsertionSort.*,CLRS.Common.*[rename=InsertionSort] -bundle CLRS.Ch02.MergeSort.ImplTest+CLRS.Ch02.MergeSort.Impl=CLRS.Ch02.MergeSort.*[rename=MergeSort] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/csrc _output/CLRS_Ch02_InsertionSort_ImplTest.krml _output/CLRS_Ch02_InsertionSort_Impl.krml _output/CLRS_Ch02_MergeSort_ImplTest.krml _output/CLRS_Ch02_MergeSort_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_PulseCore_Prims_H
#define internal_FStar_Pulse_PulseCore_Prims_H

#include "krmllib.h"

#include "krml/internal/compat.h"

extern bool Prims_op_LessThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_FStar_Pulse_PulseCore_Prims_H_DEFINED
#endif /* internal_FStar_Pulse_PulseCore_Prims_H */
