/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch25.FloydWarshall.ImplTest+CLRS.Ch25.FloydWarshall.NegCycleDetect+CLRS.Ch25.FloydWarshall.Impl=CLRS.*,Prims,FStar.*,Pulse.*,PulseCore.*[rename=CLRS_Ch25_FloydWarshall] -no-prefix CLRS.Ch25.FloydWarshall.Impl -no-prefix CLRS.Ch25.FloydWarshall.NegCycleDetect -no-prefix CLRS.Ch25.FloydWarshall.ImplTest -tmpdir _extract _output/CLRS_Ch25_FloydWarshall_Impl.krml _output/CLRS_Ch25_FloydWarshall_NegCycleDetect.krml _output/CLRS_Ch25_FloydWarshall_ImplTest.krml _output/CLRS_Ch25_FloydWarshall_Spec.krml
  F* version: <unknown>
  KaRaMeL version: 7bdb6cb2fd7661f4a0dade9ccae810451cb51746
 */

#ifndef CLRS_Ch25_FloydWarshall_H
#define CLRS_Ch25_FloydWarshall_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool test_floyd_warshall_impl(void);

bool test_neg_cycle_check_true(void);

bool test_neg_cycle_check_false(void);

bool test_floyd_warshall_safe_impl(void);

bool check_no_negative_cycle(krml_checked_int_t *dist, size_t n);

void floyd_warshall_safe(krml_checked_int_t *dist, size_t n);

void floyd_warshall(krml_checked_int_t *dist, size_t n);


#define CLRS_Ch25_FloydWarshall_H_DEFINED
#endif /* CLRS_Ch25_FloydWarshall_H */
