/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch25.FloydWarshall.ImplTest+CLRS.Ch25.FloydWarshall.NegCycleDetect+CLRS.Ch25.FloydWarshall.Impl=CLRS.*,Prims,FStar.*,Pulse.*,PulseCore.*[rename=CLRS_Ch25_FloydWarshall] -no-prefix CLRS.Ch25.FloydWarshall.Impl -no-prefix CLRS.Ch25.FloydWarshall.NegCycleDetect -no-prefix CLRS.Ch25.FloydWarshall.ImplTest -tmpdir _extract _output/CLRS_Ch25_FloydWarshall_Impl.krml _output/CLRS_Ch25_FloydWarshall_NegCycleDetect.krml _output/CLRS_Ch25_FloydWarshall_ImplTest.krml _output/CLRS_Ch25_FloydWarshall_Spec.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "CLRS_Ch25_FloydWarshall.h"

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);

static krml_checked_int_t inf = (krml_checked_int_t)1000000;

bool test_floyd_warshall_impl(void)
{
  size_t n = (size_t)3U;
  krml_checked_int_t *dv = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *dist = dv;
  dist[0U] = (krml_checked_int_t)0;
  dist[1U] = (krml_checked_int_t)5;
  dist[2U] = inf;
  dist[3U] = (krml_checked_int_t)50;
  dist[4U] = (krml_checked_int_t)0;
  dist[5U] = (krml_checked_int_t)15;
  dist[6U] = (krml_checked_int_t)30;
  dist[7U] = inf;
  dist[8U] = (krml_checked_int_t)0;
  floyd_warshall(dist, n);
  krml_checked_int_t v0 = dist[0U];
  krml_checked_int_t v1 = dist[1U];
  krml_checked_int_t v2 = dist[2U];
  krml_checked_int_t v3 = dist[3U];
  krml_checked_int_t v4 = dist[4U];
  krml_checked_int_t v5 = dist[5U];
  krml_checked_int_t v6 = dist[6U];
  krml_checked_int_t v7 = dist[7U];
  krml_checked_int_t v8 = dist[8U];
  bool
  pass =
    !(Prims_op_LessThan(v0, (krml_checked_int_t)0) || Prims_op_LessThan((krml_checked_int_t)0, v0))
    &&
      !(Prims_op_LessThan(v1, (krml_checked_int_t)5) || Prims_op_LessThan((krml_checked_int_t)5, v1))
    &&
      !(Prims_op_LessThan(v2, (krml_checked_int_t)20) ||
        Prims_op_LessThan((krml_checked_int_t)20,
          v2))
    &&
      !(Prims_op_LessThan(v3, (krml_checked_int_t)45) ||
        Prims_op_LessThan((krml_checked_int_t)45,
          v3))
    &&
      !(Prims_op_LessThan(v4, (krml_checked_int_t)0) || Prims_op_LessThan((krml_checked_int_t)0, v4))
    &&
      !(Prims_op_LessThan(v5, (krml_checked_int_t)15) ||
        Prims_op_LessThan((krml_checked_int_t)15,
          v5))
    &&
      !(Prims_op_LessThan(v6, (krml_checked_int_t)30) ||
        Prims_op_LessThan((krml_checked_int_t)30,
          v6))
    &&
      !(Prims_op_LessThan(v7, (krml_checked_int_t)35) ||
        Prims_op_LessThan((krml_checked_int_t)35,
          v7))
    &&
      !(Prims_op_LessThan(v8, (krml_checked_int_t)0) || Prims_op_LessThan((krml_checked_int_t)0, v8));
  KRML_HOST_FREE(dv);
  return pass;
}

bool test_neg_cycle_check_true(void)
{
  size_t n = (size_t)3U;
  krml_checked_int_t *dv = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *dist = dv;
  dist[0U] = (krml_checked_int_t)0;
  dist[1U] = (krml_checked_int_t)5;
  dist[2U] = inf;
  dist[3U] = (krml_checked_int_t)50;
  dist[4U] = (krml_checked_int_t)0;
  dist[5U] = (krml_checked_int_t)15;
  dist[6U] = (krml_checked_int_t)30;
  dist[7U] = inf;
  dist[8U] = (krml_checked_int_t)0;
  bool ok = check_no_negative_cycle(dist, n);
  KRML_HOST_FREE(dv);
  return ok;
}

bool test_neg_cycle_check_false(void)
{
  size_t n = (size_t)3U;
  krml_checked_int_t *dv = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *dist = dv;
  dist[0U] = (krml_checked_int_t)-1;
  dist[1U] = (krml_checked_int_t)5;
  dist[2U] = inf;
  dist[3U] = (krml_checked_int_t)50;
  dist[4U] = (krml_checked_int_t)0;
  dist[5U] = (krml_checked_int_t)15;
  dist[6U] = (krml_checked_int_t)30;
  dist[7U] = inf;
  dist[8U] = (krml_checked_int_t)0;
  bool ok = check_no_negative_cycle(dist, n);
  KRML_HOST_FREE(dv);
  if (ok)
    return false;
  else
    return true;
}

bool test_floyd_warshall_safe_impl(void)
{
  size_t n = (size_t)3U;
  krml_checked_int_t *dv = KRML_HOST_CALLOC((size_t)9U, sizeof (krml_checked_int_t));
  krml_checked_int_t *dist = dv;
  dist[0U] = (krml_checked_int_t)0;
  dist[1U] = (krml_checked_int_t)5;
  dist[2U] = inf;
  dist[3U] = (krml_checked_int_t)50;
  dist[4U] = (krml_checked_int_t)0;
  dist[5U] = (krml_checked_int_t)15;
  dist[6U] = (krml_checked_int_t)30;
  dist[7U] = inf;
  dist[8U] = (krml_checked_int_t)0;
  floyd_warshall_safe(dist, n);
  krml_checked_int_t v0 = dist[0U];
  krml_checked_int_t v1 = dist[1U];
  krml_checked_int_t v2 = dist[2U];
  krml_checked_int_t v3 = dist[3U];
  krml_checked_int_t v4 = dist[4U];
  krml_checked_int_t v5 = dist[5U];
  krml_checked_int_t v6 = dist[6U];
  krml_checked_int_t v7 = dist[7U];
  krml_checked_int_t v8 = dist[8U];
  bool
  pass =
    !(Prims_op_LessThan(v0, (krml_checked_int_t)0) || Prims_op_LessThan((krml_checked_int_t)0, v0))
    &&
      !(Prims_op_LessThan(v1, (krml_checked_int_t)5) || Prims_op_LessThan((krml_checked_int_t)5, v1))
    &&
      !(Prims_op_LessThan(v2, (krml_checked_int_t)20) ||
        Prims_op_LessThan((krml_checked_int_t)20,
          v2))
    &&
      !(Prims_op_LessThan(v3, (krml_checked_int_t)45) ||
        Prims_op_LessThan((krml_checked_int_t)45,
          v3))
    &&
      !(Prims_op_LessThan(v4, (krml_checked_int_t)0) || Prims_op_LessThan((krml_checked_int_t)0, v4))
    &&
      !(Prims_op_LessThan(v5, (krml_checked_int_t)15) ||
        Prims_op_LessThan((krml_checked_int_t)15,
          v5))
    &&
      !(Prims_op_LessThan(v6, (krml_checked_int_t)30) ||
        Prims_op_LessThan((krml_checked_int_t)30,
          v6))
    &&
      !(Prims_op_LessThan(v7, (krml_checked_int_t)35) ||
        Prims_op_LessThan((krml_checked_int_t)35,
          v7))
    &&
      !(Prims_op_LessThan(v8, (krml_checked_int_t)0) || Prims_op_LessThan((krml_checked_int_t)0, v8));
  KRML_HOST_FREE(dv);
  return pass;
}

bool check_no_negative_cycle(krml_checked_int_t *dist, size_t n)
{
  size_t v = (size_t)0U;
  bool ok = true;
  size_t __anf0 = v;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t vv = v;
    size_t idx = vv * n + vv;
    krml_checked_int_t d_vv = dist[idx];
    if (Prims_op_LessThan(d_vv, (krml_checked_int_t)0))
      ok = false;
    v = vv + (size_t)1U;
    size_t __anf0 = v;
    cond = __anf0 < n;
  }
  return ok;
}

void floyd_warshall_safe(krml_checked_int_t *dist, size_t n)
{
  floyd_warshall(dist, n);
}

void floyd_warshall(krml_checked_int_t *dist, size_t n)
{
  size_t k = (size_t)0U;
  size_t __anf00 = k;
  bool cond = __anf00 < n;
  while (cond)
  {
    size_t vk = k;
    size_t i = (size_t)0U;
    size_t __anf00 = i;
    bool cond0 = __anf00 < n;
    while (cond0)
    {
      size_t vi = i;
      size_t j = (size_t)0U;
      size_t idx_ik = vi * n + vk;
      krml_checked_int_t d_ik = dist[idx_ik];
      size_t __anf0 = j;
      bool cond = __anf0 < n;
      while (cond)
      {
        size_t vj = j;
        size_t idx_ij = vi * n + vj;
        size_t idx_kj = vk * n + vj;
        krml_checked_int_t d_ij = dist[idx_ij];
        krml_checked_int_t d_kj = dist[idx_kj];
        krml_checked_int_t via_k = Prims_op_Addition(d_ik, d_kj);
        krml_checked_int_t new_val;
        if (Prims_op_LessThan(via_k, d_ij))
          new_val = via_k;
        else
          new_val = d_ij;
        dist[idx_ij] = new_val;
        j = vj + (size_t)1U;
        size_t __anf0 = j;
        cond = __anf0 < n;
      }
      i = vi + (size_t)1U;
      size_t __anf00 = i;
      cond0 = __anf00 < n;
    }
    k = vk + (size_t)1U;
    size_t __anf0 = k;
    cond = __anf0 < n;
  }
}

