/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch02.InsertionSort.ImplTest+CLRS.Ch02.InsertionSort.Impl=CLRS.Ch02.InsertionSort.*,CLRS.Common.*[rename=InsertionSort] -bundle CLRS.Ch02.MergeSort.ImplTest+CLRS.Ch02.MergeSort.Impl=CLRS.Ch02.MergeSort.*[rename=MergeSort] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/csrc _output/CLRS_Ch02_InsertionSort_ImplTest.krml _output/CLRS_Ch02_InsertionSort_Impl.krml _output/CLRS_Ch02_MergeSort_ImplTest.krml _output/CLRS_Ch02_MergeSort_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "InsertionSort.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

bool CLRS_Ch02_InsertionSort_ImplTest_test_insertion_sort_3(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  CLRS_Ch02_InsertionSort_Impl_insertion_sort(arr, (size_t)3U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  bool
  pass =
    v0 == (krml_checked_int_t)1 && v1 == (krml_checked_int_t)2 && v2 == (krml_checked_int_t)3;
  KRML_HOST_FREE(v);
  return pass;
}

bool CLRS_Ch02_InsertionSort_ImplTest_test_insertion_sort_empty(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)0U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  CLRS_Ch02_InsertionSort_Impl_insertion_sort(arr, (size_t)0U);
  KRML_HOST_FREE(v);
  return true;
}

bool CLRS_Ch02_InsertionSort_ImplTest_test_insertion_sort_single(void)
{
  krml_checked_int_t *v = KRML_HOST_MALLOC(sizeof (krml_checked_int_t));
  if (v != NULL)
    v[0U] = (krml_checked_int_t)42;
  krml_checked_int_t *arr = v;
  CLRS_Ch02_InsertionSort_Impl_insertion_sort(arr, (size_t)1U);
  krml_checked_int_t v0 = arr[0U];
  bool pass = v0 == (krml_checked_int_t)42;
  KRML_HOST_FREE(v);
  return pass;
}

void CLRS_Ch02_InsertionSort_Impl_insertion_sort(krml_checked_int_t *a, size_t len)
{
  if (!(len == (size_t)0U))
  {
    size_t j = (size_t)1U;
    size_t __anf0 = j;
    bool cond = __anf0 < len;
    while (cond)
    {
      size_t vj = j;
      krml_checked_int_t key = a[vj];
      size_t i = vj;
      bool cont = true;
      if (vj > (size_t)0U)
      {
        krml_checked_int_t prev = a[vj - (size_t)1U];
        cont = Prims_op_GreaterThan(prev, key);
      }
      else
        cont = false;
      while (cont)
      {
        size_t vi = i;
        krml_checked_int_t val_prev = a[vi - (size_t)1U];
        krml_checked_int_t val_curr = a[vi];
        a[vi - (size_t)1U] = val_curr;
        a[vi] = val_prev;
        i = vi - (size_t)1U;
        size_t new_i = vi - (size_t)1U;
        if (new_i > (size_t)0U)
        {
          krml_checked_int_t new_prev = a[new_i - (size_t)1U];
          cont = Prims_op_GreaterThan(new_prev, key);
        }
        else
          cont = false;
      }
      j = vj + (size_t)1U;
      size_t __anf0 = j;
      cond = __anf0 < len;
    }
  }
}

