# HANDWRITTEN FILE — This is NOT generated by F* or KaRaMeL.
#
# Standalone Makefile for CLRS Ch02 extracted C snapshot
#
# This directory is self-contained: it includes all KaRaMeL-generated C
# code, vendored krmllib headers/runtime, and the handwritten test driver.
#
# Usage:
#   make          # build and run tests
#   make build    # build only
#   make test     # build and run
#   make clean    # remove build artifacts

CC       ?= cc
CFLAGS   ?= -std=c11 -Wall -g -fwrapv \
            -D_BSD_SOURCE -D_DEFAULT_SOURCE \
            -Wno-unused-variable -Wno-unused-parameter \
            -Wno-parentheses

INCLUDES = -I . -I krmllib/

EXE      = test_ch02

SOURCES  = test_main.c \
           InsertionSort.c \
           MergeSort.c \
           krmllib/c/prims.c \
           krmllib/c/fstar_int32.c

.PHONY: all build test clean

all: test

build: $(EXE)

$(EXE): $(SOURCES)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $(SOURCES)

test: $(EXE)
	./$(EXE)

clean:
	rm -f $(EXE)
