/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch02.InsertionSort.ImplTest+CLRS.Ch02.InsertionSort.Impl=CLRS.Ch02.InsertionSort.*,CLRS.Common.*[rename=InsertionSort] -bundle CLRS.Ch02.MergeSort.ImplTest+CLRS.Ch02.MergeSort.Impl=CLRS.Ch02.MergeSort.*[rename=MergeSort] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/csrc _output/CLRS_Ch02_InsertionSort_ImplTest.krml _output/CLRS_Ch02_InsertionSort_Impl.krml _output/CLRS_Ch02_MergeSort_ImplTest.krml _output/CLRS_Ch02_MergeSort_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef MergeSort_H
#define MergeSort_H

#include "krmllib.h"

#include "krml/internal/compat.h"

bool CLRS_Ch02_MergeSort_ImplTest_test_merge_sort_3(void);

bool CLRS_Ch02_MergeSort_ImplTest_test_merge_sort_empty(void);

bool CLRS_Ch02_MergeSort_ImplTest_test_merge_sort_single(void);

void CLRS_Ch02_MergeSort_Impl_merge(krml_checked_int_t *a, size_t lo, size_t mid, size_t hi);

void CLRS_Ch02_MergeSort_Impl_merge_sort(krml_checked_int_t *a, size_t len);


#define MergeSort_H_DEFINED
#endif /* MergeSort_H */
