/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../FStar/karamel/krml -skip-makefiles -skip-compilation -skip-linking -warn-error -2-9-11-15-17 -add-include "krml/internal/compat.h" -bundle CLRS.Ch02.InsertionSort.ImplTest+CLRS.Ch02.InsertionSort.Impl=CLRS.Ch02.InsertionSort.*,CLRS.Common.*[rename=InsertionSort] -bundle CLRS.Ch02.MergeSort.ImplTest+CLRS.Ch02.MergeSort.Impl=CLRS.Ch02.MergeSort.*[rename=MergeSort] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -tmpdir _output/csrc _output/CLRS_Ch02_InsertionSort_ImplTest.krml _output/CLRS_Ch02_InsertionSort_Impl.krml _output/CLRS_Ch02_MergeSort_ImplTest.krml _output/CLRS_Ch02_MergeSort_Impl.krml ../../FStar/karamel/krmllib/.extract/FStar_Order.krml ../../FStar/karamel/krmllib/.extract/FStar_Pervasives_Native.krml ../../FStar/karamel/krmllib/.extract/FStar_Seq_Base.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/MergeSort.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

bool CLRS_Ch02_MergeSort_ImplTest_test_merge_sort_3(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)3U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  arr[0U] = (krml_checked_int_t)3;
  arr[1U] = (krml_checked_int_t)1;
  arr[2U] = (krml_checked_int_t)2;
  CLRS_Ch02_MergeSort_Impl_merge_sort(arr, (size_t)3U);
  krml_checked_int_t v0 = arr[0U];
  krml_checked_int_t v1 = arr[1U];
  krml_checked_int_t v2 = arr[2U];
  bool
  pass =
    v0 == (krml_checked_int_t)1 && v1 == (krml_checked_int_t)2 && v2 == (krml_checked_int_t)3;
  KRML_HOST_FREE(v);
  return pass;
}

bool CLRS_Ch02_MergeSort_ImplTest_test_merge_sort_empty(void)
{
  krml_checked_int_t *v = KRML_HOST_CALLOC((size_t)0U, sizeof (krml_checked_int_t));
  krml_checked_int_t *arr = v;
  CLRS_Ch02_MergeSort_Impl_merge_sort(arr, (size_t)0U);
  KRML_HOST_FREE(v);
  return true;
}

bool CLRS_Ch02_MergeSort_ImplTest_test_merge_sort_single(void)
{
  krml_checked_int_t *v = KRML_HOST_MALLOC(sizeof (krml_checked_int_t));
  if (v != NULL)
    v[0U] = (krml_checked_int_t)42;
  krml_checked_int_t *arr = v;
  CLRS_Ch02_MergeSort_Impl_merge_sort(arr, (size_t)1U);
  krml_checked_int_t v0 = arr[0U];
  bool pass = v0 == (krml_checked_int_t)42;
  KRML_HOST_FREE(v);
  return pass;
}

static void
copy_range(
  krml_checked_int_t *src,
  krml_checked_int_t *dst,
  size_t src_lo,
  size_t dst_lo,
  size_t len
)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < len;
  while (cond)
  {
    size_t vi = i;
    krml_checked_int_t v = src[src_lo + vi];
    dst[dst_lo + vi] = v;
    i = vi + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < len;
  }
}

void CLRS_Ch02_MergeSort_Impl_merge(krml_checked_int_t *a, size_t lo, size_t mid, size_t hi)
{
  size_t l1 = mid - lo;
  size_t l2 = hi - mid;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), l1);
  krml_checked_int_t *tmp1_v = KRML_HOST_CALLOC(l1, sizeof (krml_checked_int_t));
  krml_checked_int_t *tmp1 = tmp1_v;
  KRML_CHECK_SIZE(sizeof (krml_checked_int_t), l2);
  krml_checked_int_t *tmp2_v = KRML_HOST_CALLOC(l2, sizeof (krml_checked_int_t));
  krml_checked_int_t *tmp2 = tmp2_v;
  copy_range(a, tmp1, lo, (size_t)0U, l1);
  copy_range(a, tmp2, mid, (size_t)0U, l2);
  size_t i = (size_t)0U;
  size_t j = (size_t)0U;
  size_t k = (size_t)0U;
  size_t __anf1 = i;
  size_t __anf00 = j;
  bool cond = __anf1 < l1 || __anf00 < l2;
  while (cond)
  {
    size_t vi = i;
    size_t vj = j;
    size_t vk = k;
    if (vi == l1)
    {
      krml_checked_int_t v = tmp2[vj];
      a[lo + vk] = v;
      j = vj + (size_t)1U;
      k = vk + (size_t)1U;
    }
    else if (vj == l2)
    {
      krml_checked_int_t v = tmp1[vi];
      a[lo + vk] = v;
      i = vi + (size_t)1U;
      k = vk + (size_t)1U;
    }
    else
    {
      krml_checked_int_t v1 = tmp1[vi];
      krml_checked_int_t v2 = tmp2[vj];
      if (Prims_op_LessThanOrEqual(v1, v2))
      {
        a[lo + vk] = v1;
        i = vi + (size_t)1U;
        k = vk + (size_t)1U;
      }
      else
      {
        a[lo + vk] = v2;
        j = vj + (size_t)1U;
        k = vk + (size_t)1U;
      }
    }
    size_t __anf1 = i;
    size_t __anf0 = j;
    cond = __anf1 < l1 || __anf0 < l2;
  }
  KRML_HOST_FREE(tmp1_v);
  KRML_HOST_FREE(tmp2_v);
}

void CLRS_Ch02_MergeSort_Impl_merge_sort_aux(krml_checked_int_t *a, size_t lo, size_t hi)
{
  size_t len = hi - lo;
  if (!(len < (size_t)2U))
  {
    size_t mid = lo + len / (size_t)2U;
    CLRS_Ch02_MergeSort_Impl_merge_sort_aux(a, lo, mid);
    CLRS_Ch02_MergeSort_Impl_merge_sort_aux(a, mid, hi);
    CLRS_Ch02_MergeSort_Impl_merge(a, lo, mid, hi);
  }
}

void CLRS_Ch02_MergeSort_Impl_merge_sort(krml_checked_int_t *a, size_t len)
{
  if (!(len <= (size_t)1U))
    CLRS_Ch02_MergeSort_Impl_merge_sort_aux(a, (size_t)0U, len);
}

